[1단계 - Payments module] - 쿠키(김진호) 미션 제출합니다.
woowacourse/react-modules pull request #15
Opened 2024-05-02 08:13 UTC by jinhokim98

안녕하세요 유조! 6기 FE 리뷰이 쿠키입니다.
이번에도 리뷰 잘 부탁드립니다.

## 배포주소

- [스토리북](https://jinhokim98.github.io/react-modules/)
- [modal npm link](https://www.npmjs.com/package/cookie-nice-modal)
- [card hooks npm link](https://www.npmjs.com/package/cookie-nice-card-hooks)

## 구조

이번에는 구조 설명을 npm readme에 적어두어서 링크로 대체하겠습니다.
* 모달 [cookie-nice-modal](https://www.npmjs.com/package/cookie-nice-modal)
* hooks [cookie-nice-card-hooks](https://www.npmjs.com/package/cookie-nice-card-hooks)

## 🤔고민한 점과 질문

1. css library에 대한 고민

처음에 페어와 함께 모달을 만들면서 emotion, styled-components 중 어떤 것을 사용할까 고민했습니다.
하지만 이 프로그램을 사용하는 사용자가 일반 사용자가 아니라 개발자인 만큼 위 라이브러리를 사용함으로써 다른 사용자에게 위 스타일 라이브러리를 강제하게 되어버리는 것이 아닐까 해서 설치하지 않아도 되는 module.css 방식을 선택했습니다. 너무 과한 생각이었는지, 아니면 적절한 생각이었는지에 대한 유조의 의견이 궁금합니다!

2. custom hooks의 인터페이스에 대한 고민
이 역시 라이브러리를 사용하는 사용자가 개발자이기 때문에 이에 대해 고민이 많았습니다.
페어와 함께 인터페이스를 설계하면서 이번 미션의 훅들은 `필드의 유효성을 검증하는 훅` 이라고 명시가 되어있기 때문에 handleChange, handleBlur라고 적어도 유효성을 검사하는 기능을 포함하고 있다고 추측할 수 있다고 생각해서 이름을 지었습니다. 
내부 사정을 모르는 사용자가  `필드의 유효성을 검증하는 훅` 이라는 기능을 보고 이 훅을 본다고 가정했을 때 사용자가 쉽게 예측을 할 수 있을지에 대해 고민입니다.

전반적으로 내부 구현을 모르는 사용자가 모달과 훅을 사용한다고 가정할 때 인터페이스만 보고도 어떻게 작동하는지, 예측이 가능한 지에 대한 피드백을 해주시면 감사하겠습니다👍👍

2024-05-02 16:30 UTC, yujo11 requested changes
안녕하세요 쿠키~

다시 만나서 반갑습니다 ㅎㅎ 이번 미션도 잘 부탁드려요

전체적으로 코드를 깔끔하게 잘 작성해주셔서 코멘트 남길 부분이 많지 않았는데 코멘트 남긴 내용들 읽어보시고 궁금한 점 있으시면 추가로 질문 주시면 좋을거 같습니다 ㅎㅎ 👍 👍 👍 

>CSS 라이브러리 선택에 대한 고민

라이브러리를 추가한다면 조금 더 쉽게 스타일 적용이 가능했겠지만 사용하는 유저의 프로젝트에 의존성이 추가되기 떄문에 저는 좋은 선택을 하셨다고 생각합니다 ㅎㅎ 

>Custom Hooks의 인터페이스에 대한 고민

저는 개인적으로 handleChange나 handleBlur의 경우 이름만 보고는 에러 처리까지 해줄거라는 생각이 잘 안 들었는데요. 사실 잘 만든 Hook이라도 인터페이스 만으로 모든 사용법을 알기는 어려운데요. 그래서 적절한 설명이 중요한거 같습니다.

지금은 Hook에서 모든 에러처리까지 담당해주고 있지만 사용하는 유저의 입장에서는 블랙박스 영역에서 에러에 대한 처리가 이뤄진다는 생각이 들 수도 있을거 같아요. 이런 부분들에 대해서도 고민 해보시면 좋을거 같네요! 많이 사용되는 [react-use](https://github.com/streamich/react-use) 같은 곳에서 어떤 형태로 hook을 만들어 제공하는지도 같이 참고해보시면 좋을거 같습니다

미션 진행하느라 고생 많으셨습니다~~ 👍 👍 👍

2024-05-02 16:30 UTC, yujo11 commented on hooks/src/lib/useInputs.ts
> +      [name]: validationResult,
name으로 판별을 한다면 hook의 설명에도 해당 내용이 들어가야 할거 같은데 못 본거 같네요 ㅎㅎ

2024-05-02 16:30 UTC, yujo11 commented on hooks/src/lib/useInputs.ts
> +  };
validation 결과에 따른 로직이 섞여 있는데 이 부분을 개선해 볼 수 있을까요?

2024-05-02 16:30 UTC, yujo11 commented on hooks/src/lib/useExpiryYear.ts
> +  };
depth가 깊어지고 조건문이 많아져 코드 읽기가 어려운데 읽기 좋게 개선해보시면 좋을거 같네용

2024-05-02 16:30 UTC, yujo11 commented on hooks/src/lib/useCardHolder.ts
> +  const isValidHolderFormat = /^(?=\S)(?!.*\s\s).*\s+(?=\S).*$/.test(value);
이건 어떤 조건을 검증하기 위한 정규식일까요?

2024-05-04 13:07 UTC, jinhokim98 commented on components/.eslintrc.cjs
> +    "plugin:prettier/recommended",
아 prettier를 제일 마지막에 둬야하군요..! 감사합니다

2024-05-04 13:13 UTC, jinhokim98 commented on components/.prettierrc.cjs
처음에 cjs로 설정되어있었어서 신경 쓰지 않았었는데 덕분에 js와 cjs의 차이에 대해 알아볼 수 있었어요!

일반 js는 흔히 작성하는 자바스크립트 파일이고, cjs는 nodejs에서 사용하는 모듈 시스템입니다. cjs로 export할 땐 module.exports로 export 하고 다른 파일에서 import할 땐 require을 사용해서 import 해야한다고 합니다!

2024-05-04 13:15 UTC, jinhokim98 commented on components/README.md
> +- position (ModalPosition) : 모달의 위치 (`center`) 또는 (`bottom`)
오호 옆이나 밑에서 스르륵 나오는 컴포넌트를 Drawer라고 하는군요!!
지금까지 개발하면서 사이드바라고 컴포넌트를 지어왔었는데 Drawer도 고려해보겠습니다!

2024-05-04 13:17 UTC, jinhokim98 commented on components/README.md
> +- buttonPosition (ButtonPosition): 닫기 버튼과 확인 버튼의 배치를 결정할 수 있습니다. (확인 버튼이 오른쪽, 아래가 정배) ('row', 'row-reverse', 'column', 'column-reverse')
아ㅋㅋㅋ 이거 페어와 함께 기능을 생각하면서 확인 버튼과 취소 버튼의 default 배치를 어떻게 가져갈까 논의하다가 가로로 배치됐을 땐 확인 버튼이 오른쪽에 있는 것이 자연스럽고, 세로로 배치됐을 땐 확인 버튼이 아래에 있는 것이 자연스럽다고 생각했습니다.
그래서 이게 정배지하고 재미있게 적어놨던 것 같네요😊

2024-05-04 13:18 UTC, jinhokim98 commented on components/README.md
> +- isOpen: boolean : 모달이 열려있는지 여부
반환값이 boolean이라 is가 붙어야 한다고 생각했었는데 open 자체도 충분히 열린 상태라는 것을 인지할 수 있을 것 같네용

2024-05-04 13:19 UTC, jinhokim98 commented on components/src/lib/Modal.module.css
> +    font-size: 18px;
앗 그러네요!! 변수로 관리하는 방식으로 변경해볼게요!

2024-05-04 13:21 UTC, jinhokim98 commented on components/src/lib/Modal.tsx
> +    };
useEffect의 return은 `clean-up` function으로 컴포넌트가 `unmount`될 때 실행되는 함수입니다.
임의로 document에 addEventListener를 달아주었으니, 컴포넌트가 unmount 될 때 달아준 이벤트를 지워주었습니다!

2024-05-04 13:22 UTC, jinhokim98 commented on hooks/src/tests/usePassword.test.ts
> +  it('입력값이 2자리가 아니라면 에러이다', () => {
앗! 맞네요 무슨 에러가 발생하는지도 같이 적어줬다면 좋을 것 같아요

2024-05-04 13:34 UTC, jinhokim98 commented on hooks/src/lib/useInputs.ts
> +      [name]: validationResult,
아 이게 event.target.name이 아니라 저 함수의 두 번째 파라미터로 name을 받아서 사용하는 방식이라 괜찮을 것 같다고 생각했습니다!
그래도 주석이나 다른 방식으로 이름을 받는다 의 의미를 추가했으면 더 좋았을 것 같네용

2024-05-04 13:35 UTC, jinhokim98 commented on hooks/src/lib/useCardHolder.ts
> +  const isValidHolderFormat = /^(?=\S)(?!.*\s\s).*\s+(?=\S).*$/.test(value);
성과 이름의 구조처럼 문자열과 문자열 사이에 공백이 1개 존재하며, 연속으로 2개는 불가하다는 의미입니다.. 조금 복잡하네요;;

2024-05-06 07:26 UTC, jinhokim98 commented on hooks/src/tests/usePassword.test.ts
> +  it('초기값이 올바르지 않은 값이라면 결과는 빈 값이다.', () => {
개선해봤습니다!
[81ae9a8](https://github.com/woowacourse/react-modules/pull/15/commits/81ae9a8c6e6d5eb67537a7597f5b8aa07184715f)

2024-05-06 07:27 UTC, jinhokim98 commented on hooks/src/lib/useInputs.ts
> +  };
개선해봤습니다!
[c93cfdc](https://github.com/woowacourse/react-modules/pull/15/commits/c93cfdc883bba454b4bab6eae0c8d498ee3028ea)

2024-05-06 07:27 UTC, jinhokim98 commented on hooks/src/lib/useExpiryYear.ts
> +  };
개선해봤습니다!
[e68666a](https://github.com/woowacourse/react-modules/pull/15/commits/e68666ac401cfa44364ae99fc66a593d6fa59633)

2024-05-06 07:32 UTC, jinhokim98 commented
안녕하세요 유조! 즐거운 연휴 보내고 계신가요?
저도 이번 연휴를 조금 즐기느라 리뷰 반영이 늦었습니다..😥

이번 리팩터링에서 주로 챙긴 점은 커스텀 확대입니다.

모달 컴포넌트는 기존의 props로 모달 헤더, 컨텐츠, 푸터의 정보를 모두 내려주는 방식에서 합성 컴포넌트 방식으로 변경해서 각 컴포넌트에 맞는 props를 내려줄 수 있도록 변경해봤습니다.
그래서 모달의 헤더를 사용하지 않고 싶을 경우나, 헤더를 제일 아래에 내려서 사용할 수 있도록 확장성을 넓혀봤습니다.

훅의 경우에는 custom한 validation 로직을 외부에서 넣어줄 수 있도록 확장해봤습니다.
넣어주지 않을 경우 기존의 로직이 돌아가면서 외부에서 custom 로직을 넣어주면 custom 규칙대로 돌아가도록 설정해줘서, 좀 더 다양한 경우에도 사용할 수 있도록 개선해봤습니다!

이번에도 리뷰를 반영한 부분에는 커밋 번호를 달아두었고, 리뷰에 대한 제 의견은 리코멘트로 달아뒀습니다!

2024-05-06 13:16 UTC, yujo11 commented on components/.prettierrc.cjs
소소하게 면접 때도 자주 등장하는 질문이니 각 모듈 간의 차이점을 정확히 숙지하고 계시면 좋겠네요 ㅎㅎ 👍

2024-05-06 13:18 UTC, yujo11 commented on hooks/src/lib/useCardHolder.ts
> +  const isValidHolderFormat = /^(?=\S)(?!.*\s\s).*\s+(?=\S).*$/.test(value);
이런 복잡한 정규식 같은 경우는 읽기가 어렵기 때문에 적절하게 주석으로 내용을 남겨주셔도 좋을거 같아요 ㅎㅎ

2024-05-06 13:28 UTC, yujo11 approved these changes
안녕하세요 쿠키

연휴를 즐기셨군요 ㅋㅋㅋㅋㅋ 우테코 과정이 길기 때문에 잘 쉬는 것도 중요하다고 생각합니다 👍 👍 👍 

기존 코멘트와 더불어 몇 가지 개선할만한 부분들 코멘트로 남겼는데 다음 step 진행하시면서 반영해보시면 좋을거 같습니다!

고생 많으셨습니다 쿠키 다음 step에서 만나요~~ 👍 👍 👍

2024-05-06 13:28 UTC, yujo11 commented on components/.eslintrc.cjs
> +    "plugin:prettier/recommended",
👍 👍 👍

2024-05-06 13:28 UTC, yujo11 commented on components/src/index.css
> +  --title-line-height: 26.06px;
오 아주 좋네요 ㅎㅎ 👍 👍 👍 그런데 `titls-size`와 `title-font-size`는 어떻게 다른걸까요? 🤔

2024-05-06 13:28 UTC, yujo11 commented on components/src/lib/components/footer/buttons/CloseButton.tsx
`CloseButton`과 `ConfirmButton`의 생김새가 매우 유사한데 공통되는 부분을 추상화해서 사용해보셔도 좋을거 같네용

2024-05-06 13:28 UTC, yujo11 commented on components/src/lib/hooks/useCloseOnESC.tsx
document 전체에 이벤트 리스너를 등록하는 대신에 Modal이 나올 때 Modal의 Background 영역을 같이 나오게 해서 해당 영역에 이벤트 리스너를 등록해서 핸들링 하는 방법도 있을거 같네요!

2024-05-06 13:28 UTC, yujo11 commented on components/README.md
> +      open={isOpen}
👍 👍 👍

2024-05-06 13:28 UTC, yujo11 commented on components/src/lib/Modal.tsx
>  };
명칭 좋네요 👍 👍 👍

2024-05-06 13:28 UTC, merged