[1단계 - 페이먼츠 모듈] 렛서(김다은) 미션 제출합니다.
woowacourse/react-modules pull request #18
Opened 2024-05-02 08:20 UTC by llqqssttyy

안녕하세요, 케빈! 처음 뵙겠습니다.😊
리뷰 잘 부탁드립니다!

## 배포 주소
- [[storybook]](https://66334371d18cfe614f457905-mtsnkptgjw.chromatic.com/)
- [[llqqssttyy-react-modules-components]](https://www.npmjs.com/package/llqqssttyy-react-modules-components)
- [[llqqssttyy-react-modules-hooks]](https://www.npmjs.com/package/llqqssttyy-react-modules-hooks)

<br/>

## 학습 목표
- 재사용 가능한 모듈화된 컴포넌트(모달, 커스텀 훅)를 개발하고 npm에 배포할 수 있다.
- Storybook과 RTL을 활용한 컴포넌트 문서화 및 테스트 시나리오를 작성할 수 있다.

<br/>

## 설계 의도
### 모달 컴포넌트 라이브러리
- 사용자가 모달의 요소를 합성하여 어떤 레이아웃이든 만들 수 있도록 합성 컴포넌트 패턴을 적용한 모달 컴포넌트를 제공합니다.
- 페이먼츠 앱에서 손 쉽게 사용할 수 있도록 페이먼츠 피그마 시안의 레이아웃을 따르는 `BasicBottomModal`과 `BasicCenterModal` 컴포넌트를 제공합니다.

### Hooks 라이브러리
- 카드 등록에 필요한 입력 필드에 따라 유효성 검사, 상태 관리 책임을 모듈화 한 hook을 제공합니다.
- 사용자는 error 케이스에 대한 에러 메시지를 props로 제공하고, 아래의 상태 및 함수를 제공받을 수 있습니다.
	- value
	- error
	- errorMessage
	- handleChange
	- handleBlur
	- updateValue

<br/>

---

#### 질문 있어요 👋
현재 제작된 훅은 props로 errorMessage 객체만을 보내주고 있기 때문에 각 필드에서 내부적으로 상태가 어떻게 관리되는지 바깥에서는 알기 어렵습니다. 
예를 들어, `useExpiryDate`를 사용하기 위해서는 'expiryDate 상태가  `month`와 `year`로 구성된 객체로 관리된다'라는 지식이 필요합니다. 
```tsx 
// 사용 예시
import useExpiryDate from '../lib/useExpiryDate';

export default function CardExpiryDate() {
const { expiryDate, handleChange, handleBlur, errorMessage, error } = useExpiryDate({
  validationErrors: {
    empty: '정보를 입력해 주세요.',
    number: '숫자를 입력해 주세요.',
    year: '유효하지 않은 연도입니다.',
    month: '유효하지 않은 달입니다.',
    date: '유효기간이 만료된 카드는 등록할 수 없습니다.',
  },
});

return (
  <div>
    <input
    maxLength={2}
    name={`${error.month}`}
    value={expiryDate.month}
    type="text"
    onChange={(e) => handleChange(e, 'month')}
    onBlur={(e) => handleBlur(e, 'month')}
    />
		
    <input
    value={expiryDate.year}
    maxLength={2}
    name={`${error.year}`}
    type="text"
    onChange={(e) => handleChange(e, 'year')}
    onBlur={(e) => handleBlur(e, 'year')}
    />
    <div>오류:{errorMessage}</div>
  </div>
  );
}
```
케빈이 생각했을 때 이 라이브러리의 사용성은 어떤가요? 

<br/>

#### 이런 점은 개선할 예정이에요😅
hooks 라이브러리를 만들다 보니 각 훅에서 유효성 검사 로직을 수행하고 value 및 error state를 관리하는 중복 로직이 보였습니다. 하지만 각자 관리하는 value의 타입이 배열, 문자열, 객체로 상이해 어떤 훅들은 한 차례 더 추상화가 가능했고, 어떤 훅들은 추상화를 하지 못했습니다. 
시간이 부족해 작업을 미처 다 끝내지 못해 추상화 레벨을 통일시키지 못한 채 제출했지만 이를 개선하는 작업을 할 예정입니다!

2024-05-02 16:51 UTC, JeongBin0227 commented
[스토리북]
<img width="278" alt="image" src="https://github.com/woowacourse/react-modules/assets/45503248/b53201a0-aa96-4f59-b700-701214757a59">

굳이 2파트로 나누지 않고 controls로 구분해도 될거 같아요

2024-05-02 16:56 UTC, JeongBin0227 commented
> 현재 제작된 훅은 props로 errorMessage 객체만을 보내주고 있기 때문에 각 필드에서 내부적으로 상태가 어떻게 관리되는지 바깥에서는 알기 어렵습니다.
> 예를 들어, useExpiryDate를 사용하기 위해서는 'expiryDate 상태가 month와 year로 구성된 객체로 관리된다'라는 지식이 필요합니다.

우선 렛서가 만든 코드의 장점을 생각해보면 반환 값(expiryDate, handleChange, handleBlur, errorMessage, error 등)을 통해 명확하게 기능을 구분해주는거 같아요. 이렇게 되면 사용자가 어떻게 사용할수있는지 바로 파악이 가능합니다. 또한 사용자가 직접 오류 메시지를 정의할 수 있도록 하여 커스텀이 쉽게 만든게 좋아보여요 👍 
단점을 보면 말씀하신대로 객체로 관리되는지에 대한 정보가 라이브러리 사용자에게 명확히 제공되어야 할거 같아요. 현재의 구현에서는 사용자가 이 내부 구조를 사전에 알고 있어야 하므로, 문서화를 통해 이 부분을 명확히 제공되어야 할거같아요. 현재 handleChange와 handleBlur는 expiryDate의 month와 year를 직접 조작하는걸로 보이는데, 이 함수들을 더 범용적으로 사용할 수 있도록 일반화하거나, 라이브러리 사용자가 좀 더 세밀하게 제어할 수 있도록 바꾸어 보면 어떨까요?

2024-05-02 17:16 UTC, JeongBin0227 commented
저는 개인적으로 묘듈 즉 라이브러리를 만드는 미션을 통해 어떤걸 얻고 싶은지에 따라 코멘트가 달라질거 같아요
라이브러리를 만들어보고 배포해보자라는 미션이면 충분히 잘하셨지만,
라이브러리 의도에 맞게 만들어보자 라고 했을때, 아쉬움이 많은 미션이었습니다.

렛서가 자주 쓰는 라이브러리를 생각해보면, 좋을거 같은데, 어떤이유로 라이브러리를 쓰시나요?
대부분 사람들이 라이브러리를 쓰는 이유는 좀더 편리하고, 직접 복잡한 로직과 컴포넌트를 구현하지 않기 위해 라이브러리를 사용합니다. 또한 커스텀도 잘되어야겠지용. 이런 부분을 중심으로 다시한번더 라이브러리에 대해서 고민해보면 좋을거 같아요.

렛서가 좋아하는 라이브러리가 있다면 그 라이브러리들의 코드를 보는것도 많은 도움이 될거 같아요!

2024-05-02 17:17 UTC, JeongBin0227 commented
모달을 Compound Component Pattern 으로 제공해주셨는데, 이유가 있을까요?

2024-05-02 17:22 UTC, JeongBin0227 requested changes
안녕하세요 렛서 만나서 반가워요~

전체적으로 코드가 깔끔해서 보기 좋았습니다 👍 
훅도 굉장히 자세하게 나누어서 하나하나 만들어주셨는데, 그러다 보니 불필요한 로직들이나 중복로직이 많이 포함되어있는게 보였던거 같아요. 그래서 렛서가 생각하는 훅의 존재이유나 훅을 개발하면서 어떤 생각을 가지고 작성하셨을까 궁금증이 들었습니다~ 여기에 대해서 답해주시면 좋을거 같아요

미션하느라 고생하셨습니다~ 💯 전체적으로 잘하신거 같아요!

2024-05-02 17:22 UTC, JeongBin0227 commented on components/src/lib/Modal/BasicBottomModal/index.tsx
> +        <div>{props.children}</div>
div가 굳이 필요없어 보입니다

2024-05-02 17:22 UTC, JeongBin0227 commented on components/src/lib/Modal/index.tsx
> +  };
이 코드를 이해하기 좀 어려웠는데 이렇게 바꿔도 될거 같아요
```
const onClick = (e: MouseEvent<HTMLDivElement>) => {
  if (e.currentTarget === e.target) {
    closeModal();
  }
};
```

2024-05-02 17:22 UTC, JeongBin0227 commented on components/src/lib/Modal/index.tsx
> +export default Modal;
CloseButton, CloseIconButton, CloseBoxButton 모든 컴포넌트들에서 closeModal을 호출하는 동일한 onClick 핸들러를 사용하고 있는데, 이를 하나로 만들어서 같이 사용하게 하면어떨까요?

2024-05-02 17:22 UTC, JeongBin0227 commented on components/src/lib/Modal/index.tsx
> +            [styles[type]]: type && isOpen,
styles[type] 이 없는 경우도 예외처리 되면 좋겠네요
ex)
```
className={clsx(className, styles.modal, type ? styles[type] : styles.default, { [styles.open]: isOpen })}

```

2024-05-02 17:22 UTC, JeongBin0227 commented on components/src/lib/Modal/style.module.css
> +  height: 100%;
여기 중복 설정됐어요~

2024-05-02 17:22 UTC, JeongBin0227 commented on components/src/lib/Modal/style.module.css
> +  }
여기 중복 설정이 좀 있네요
```
.modal button {
  background-color: transparent;
  padding: 0;
  border: none;
  outline: none;
}
```
차라리 이렇게 해도 될거 같아요

2024-05-02 17:22 UTC, JeongBin0227 commented on components/src/lib/Modal/style.module.css
> +  opacity: 35%;
질문) opacity 에 퍼센트도 되나요? 0~1의 값만 입력해야하는줄 알았습니다
https://developer.mozilla.org/ko/docs/Web/CSS/opacity

2024-05-02 17:22 UTC, JeongBin0227 commented on components/src/lib/hooks/useModal.ts
> +  return { open: open, openModal, closeModal };
이름이 같으면 그냥 내보내도 됩니당

```
return { open, openModal, closeModal };

```

2024-05-02 17:22 UTC, JeongBin0227 commented on hooks/src/lib/useCVC.ts
> +    isValid: !!errorMessage,
이 로직이 맞을까요? 그냥 읽다보면 isValid인데 왜 !!errorMessage 이지 라는 생각이 듭니다
반대가 아닌가요?

2024-05-02 17:22 UTC, JeongBin0227 commented on hooks/src/lib/useCVC.ts
> +}
이런 함수나 훅의 작동방식이 복잡할 경우, 상단에 이런식으로 기입해두면 파일 자체가 문서가 될수도 있어요 👍 (영어나 한글은 기호에 맞게 작성해주시면 됩니다(
```
/**
 * useCVC - A custom hook for managing CVC input validation.
 * @param {UseCardModuleProps<ValidationErrors>} props - Props containing validation error messages.
 * @returns {object} Object containing CVC value, setters, validators, and error message.
 */
```

2024-05-02 17:22 UTC, JeongBin0227 commented on hooks/src/lib/useCardHolder.ts
> +  const totalValidators = [blurEventValidators[0], ...changeEventValidators, blurEventValidators[1]];
totalValidators 로 제공해주시는 이유가 있을까요?
모든 유효성 검사를 한 번에 처리해야 하는 경우에만 사용되지 않는다면, 이 배열을 제거하고 필요한 곳에서 각각의 배열을 따로 제공하고 사용하는 것이 좀더 확장성에 유리할거 같아요

2024-05-06 15:38 UTC, llqqssttyy commented on components/src/lib/Modal/index.tsx
> +  };
이런 간단한 방법이 있었네요.👀 제안 감사드립니다!
적용했습니다. [[커밋]](https://github.com/woowacourse/react-modules/pull/18/commits/2278fd0c312e4803cb29a702cd404834f558b6ef)

2024-05-07 02:00 UTC, llqqssttyy commented on components/src/lib/Modal/style.module.css
> +  opacity: 35%;
저도 이번에 페어를 통해 처음 알게 되었는데요, opacity 값에 percentage도 작성 가능하다고 합니다!

0부터 1 사이의 값을 입력하는 것 보다 지원하는 브라우저가 적긴 하지만 mdn에도 있는 표준인 것 같습니다~ 

**참고 자료**
[MDN: opacity](https://developer.mozilla.org/en-US/docs/Web/CSS/opacity#syntax)
[Can I use - opacity](https://caniuse.com/css-opacity) 
[Can I use - opacity: support for percentage opacity values](https://caniuse.com/mdn-css_properties_opacity_percentages)

2024-05-07 07:09 UTC, llqqssttyy commented on components/src/lib/Modal/index.tsx
> +            [styles[type]]: type && isOpen,
className에 기본 값을 줄 수도 있군요! 반영했습니다. 감사합니다.☺️

[[커밋]](https://github.com/woowacourse/react-modules/pull/18/commits/f035e469ec3cd3b37e9d53714afd27f02a9acbb6)

2024-05-07 07:10 UTC, llqqssttyy commented on hooks/src/lib/useCVC.ts
> +}
설명까지 추가하니 더욱 라이브러리 같아졌네요. 좋은 피드백 감사합니다!

2024-05-07 07:14 UTC, llqqssttyy commented on hooks/src/lib/useCardHolder.ts
> +  const totalValidators = [blurEventValidators[0], ...changeEventValidators, blurEventValidators[1]];
사용자가 바깥에서 전체 validator를 사용하는 시나리오를 상상하면서 추가했는데, 리팩토링하는 과정에서 totalValidators를 제거하고 사용자가 아래와 같이 validator를 커스텀 할 수 있도록 수정했습니다!

```tsx
const cvcResult = useCVC<HTMLInputElement>({
    initialValue: '',
    validations: {
      onChange: {
        number: '숫자만 입력 가능해요.',
      },
      onBlur: {
        empty: '값을 입력해주세요.',
        length: '세자리 숫자여야 합니다.',
      },
    },
  });
```

2024-05-07 07:31 UTC, llqqssttyy commented
안녕하세요, 케빈! 리뷰 반영에 오랜 시간이 걸려 죄송합니다.🥲
리뷰를 받고 제가 제작한 라이브러리가 무엇을 위한 라이브러리인지 다시 한 번 돌아 보는 시간을 가졌습니다.
이에 따라 방향성을 다시 잡았고, 많은 수정을 거쳐서 files changed가 많습니다.😂
아래에 변경 사항을 요약했으니 참고해 주세요.☺️

### 배포 링크
#### [스토리북](https://66334371d18cfe614f457905-tdvnytuqxf.chromatic.com/)
#### [llqqssttyy-react-modules-components](https://www.npmjs.com/package/llqqssttyy-react-modules-components)
#### [llqqssttyy-react-modules-hooks](https://www.npmjs.com/package/llqqssttyy-react-modules-hooks)

<br/>

---

주요한 변경사항은 다음과 같습니다.

### Components library
> #### 라이브러리의 목적
> 페이먼츠 앱의 [디자인](https://www.figma.com/file/An5VnS9dFQerjA6ezKiePk/[%ED%81%AC%EB%A3%A8]-%EB%A0%88%EB%B2%A82-%EB%AF%B8%EC%85%98-%EB%94%94%EC%9E%90%EC%9D%B8?type=design&node-id=2729-1322&mode=design&t=do5MFCZGUUX4uad9-0)을 따르는 모달 컴포넌트를 제공한다. 합성 컴포넌트 패턴을 사용하여 사용자가 원하는 레이아웃을 구현할 수 있다.
- 기존 모달 라이브러리는 style이 전혀 들어가지 않는 modal과 해당 modal을 사용하여 페이먼츠 앱의 디자인을 따르는 Basic*-Modal로 구성되어 있었습니다.
- 해당 라이브러리의 사용자를 '페이먼츠 앱을 개발하는 개발자'로 특정하니 style이 내장된 UI 라이브러리라는 방향성이 더 맞다고 생각되었습니다.
- 따라서 합성 컴포넌트로 제공되는 모달에 style을 추가하고, Basic*-Modal을 제거했습니다.

<br/>

### Hooks library
> #### 라이브러리의 목적
> 페이먼츠 앱의 카드 추가 form에서 요구되는 필드에 대한 커스텀 훅을 제공한다. 유효성 검사 로직과 상태 관리를 추상화한다.

- 기존 라이브러리보다 커스텀의 여지를 넓혔습니다.
	- input 상태의 초기값
	- validator들의 실행 타이밍 및 validation 에러 메시지를 커스텀
		```tsx
		const cvcResult = useCVC<HTMLInputElement>({
	    initialValue: '',
	    validations: {
	      onChange: {
	        number: '숫자만 입력 가능해요.',
	      },
	      onBlur: {
	        empty: '값을 입력해주세요.',
	        length: '세자리 숫자여야 합니다.',
	      },
	    },
	  });
	  ```


- `useSingleInput`, `useMultipleInput` 커스텀 훅을 추가. 기존의 커스텀 훅에서 반복되는 로직을 제거 및 사용자가 다른 필드에 대한 훅을 생성할 수 있도록 함.

<br/>

---

### 반영한 피드백
- [x] button 컴포넌트를 하나로 통일. [[코멘트]](https://github.com/woowacourse/react-modules/pull/18#discussion_r1587985913)
- [x] 조건부 className에서 기본 값 지정해 주기.  [[코멘트]](https://github.com/woowacourse/react-modules/pull/18#discussion_r1587987073)
- [x] onClick 가독성 개선 [[코멘트]](https://github.com/woowacourse/react-modules/pull/18#discussion_r1587984687)
- [x] 함수나 훅의 작동 방식을 설명하는 jsdoc 주석 활용하기 [[코멘트]](https://github.com/woowacourse/react-modules/pull/18#discussion_r1587999977)

중복 코드, 불필요한 코드 등 자잘한 수정 사항입니다.
- [x] 불필요한 div 제거 [[코멘트]](https://github.com/woowacourse/react-modules/pull/18#discussion_r1587982336)
- [x] 중복 설정된 css 제거 [[코멘트1]](https://github.com/woowacourse/react-modules/pull/18#discussion_r1587990583) [[코멘트2]](https://github.com/woowacourse/react-modules/pull/18#discussion_r1587992356)
- [x] `{ open: open, ... }` 단축하여 작성 [[코멘트]](https://github.com/woowacourse/react-modules/pull/18#discussion_r1587994715)

아래 리스트는 리팩토링에 따라 사라져 자연스럽게 반영된 피드백입니다! 참고해주세요.
- [x] modalTitle도 React Node로 받기 [[코멘트]](https://github.com/woowacourse/react-modules/pull/18#discussion_r1587981532)
- [x] isValid 값 계산 오류 수정 [[코멘트]](https://github.com/woowacourse/react-modules/pull/18#discussion_r1587997471)
- [x] `totalValidator` 배열 제거 [[코멘트]](https://github.com/woowacourse/react-modules/pull/18#discussion_r1588009810)

2024-05-07 07:35 UTC, llqqssttyy commented
> 훅도 굉장히 자세하게 나누어서 하나하나 만들어주셨는데, 그러다 보니 불필요한 로직들이나 중복로직이 많이 포함되어있는게 보였던거 같아요. 그래서 렛서가 생각하는 훅의 존재이유나 훅을 개발하면서 어떤 생각을 가지고 작성하셨을까 궁금증이 들었습니다~ 여기에 대해서 답해주시면 좋을거 같아요

케빈이 여쭤봐주신 내용에 대해서 생각을 해보았습니다. 

제가 생각하는 훅의 존재 이유는 컴포넌트의 다양한 관심사를 분리하기 위함입니다. 예를 들어 Input이라는 컴포넌트가 있다면 해당 함수엔 이런 내용이 있을 것입니다.
  - input의 값을 저장하는 상태
  - 입력된 값이 유효한지 검사하는 코드
  - UI와 관련한 코드

이러한 관심사가 모두 Input이라는 컴포넌트(함수)에 몰려 있다면, SelectBox라는 새로운 컴포넌트가 생길 때 이 코드를 재사용할 수 없을 것입니다.
하지만 useInput이라는 훅을 만들어 입력 필드의 값을 관리하고, useValidation이라는 훅을 만들어 유효성 검사를 진행하는 로직을 만든다면 SelectBox 뿐만 아니라 다른 입력 컴포넌트를 만들어도 해당 로직을 재사용할 수 있을 것입니다. 
결론적으로 훅은 관심사를 분리하기 위해 존재하고, 이를 구현하면서 재사용성도 챙길 수 있는 것이라고 생각합니다!

---

위의 내용을 정리한 뒤 제 코드를 돌아 보니 부족한 부분이 보여서 리팩토링을 진행했습니다.
  - 카드 모듈에 대한 훅에서 state 관리 책임을 분리(useSingleInput, useMultipleInput)
  - useValidation이 validate 함수를 반환하도록 수정

2024-05-07 16:21 UTC, JeongBin0227 approved these changes
안녕하세요 렛서!

코멘트한 부분과 

> 카드 모듈에 대한 훅에서 state 관리 책임을 분리(useSingleInput, useMultipleInput)
> useValidation이 validate 함수를 반환하도록 수정

부분을 중점적으로 확인했는데 대체로 코드가 깔끔해진거 같아요 👍 

1단계는 여기서 머지하도록 하겠습니다 2단계에서 만나요~ 💯

2024-05-07 16:21 UTC, merged