[1단계 - 페이먼츠 모듈] 시모(심호림) 미션 제출합니다.
woowacourse/react-modules pull request #24
Opened 2024-05-02 08:32 UTC by simorimi

모달 배포: https://www.npmjs.com/package/harrysimodal

커스텀 훅 배포: https://www.npmjs.com/package/hook-simo-harry

안녕하세요 호프? 다시 만나뵙게 되어 정말 반갑네요! 레벨 1 로또 미션에서 만났었을 때 당시 친절하고 꼼꼼하게 봐주셔서 정말 감사했습니다. 이번에 리뷰어를 확인하는데 또 다시 호프여서 반갑고 좋았네요! 이번에도 피드백 부탁드리겠습니다. 감사합니다 🙂

## `예비군!`

호프! 제가 다음주 5/7~5/9까지 예비군 동원훈련을 다녀오게 되었습니다. 🥲 다음주 목요일부터 제출 권장인데 예비군 기간 외에 최대한 시간들 활용해서 다다음주 월요일 6시 전까지 제출하는 것을 목표로 해보겠습니다! 조금 늦더라도 기다려주시면 감사하겠습니다.. 충성 ㅠ

## 모달

### 의도

모달의 경우 레벨 1 때 부터 익히 다뤘던 부분이라 익숙했습니다. 이번 페어와 진행하면서 컴포넌트 합성에 관해서 배울 수 있었습니다. 컴포넌트 합성을 이용한 이유는 모달만을 호출해도 모달에 꼭 포함되어야 할 backdrop등을 좀 더 쉽게 사용할 수 있도록 하기위해서 합성을 하였습니다. 모달 컴포넌트의 경우 아래의 그림과 같이 컴포넌트화 하였습니다.

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/f17aaf97-c334-4865-afbc-d7711240ea7b/a0c21353-2eca-4818-a0db-70e4e2c57788/Untitled.png)

모달에는 암흑 부분인 backDrop과 내용에 해당하는 container로 구분하였습니다. backDrop을 클릭하면 모달창이 닫치는 기능도 추가하였습니다. 

container의 경우 props로 position(top, center, bottom)을 받도록 하였습니다. 

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/f17aaf97-c334-4865-afbc-d7711240ea7b/e3e50995-b3be-4251-850f-853d7e61b150/Untitled.png)

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/f17aaf97-c334-4865-afbc-d7711240ea7b/a4914068-ccd5-45e4-8176-848fae01e9bc/Untitled.png)

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/f17aaf97-c334-4865-afbc-d7711240ea7b/dc9dc2df-cb70-4861-b19d-32c944503fc1/Untitled.png)

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/f17aaf97-c334-4865-afbc-d7711240ea7b/55a395ee-1bd2-44c8-8dfd-1011ded3874c/Untitled.png)

center의 경우가 우리가 흔히 보는 모달창의 경우를 의미합니다. 

bottom의 경우는 모바일에서 모달을 편히 사용하기위하여 아래에서 위치하도록 고려하였습니다. 

top의 경우에는 통신이 끊기는 에러 등을 표현할 떄 상단에 위치하면 좋겠다고 판단하여 넣게 되었습니다. 

container 안에는 header, content, modalButtonContainer로 구성 되었습니다. 여기서 content의 경우는 사용자가 원하는 디자인과 내용이 있을 것이라는 판단에 children 속성으로 받기만 하도록 하였습니다. 이 외 header와 modalButtonContainer의 경우는 모달의 container에서 대부분이 비슷한 스타일을 적용한다는 생각에 해당 부분은 컴포넌트를 작성하여 제공해주도록 하였습니다. 헤더에는 title과 closeButton을 가지고 있습니다. buttonContainer의 경우 direction을  props로 받아 버튼의 나열 방향을 결정할 수 있도록 하였습니다. 버튼이 2개일지라도 row로 둘 수도 있고 column으로 둘 수도 있다고 판단하여 props를 결정하게 되었습니다. 

해당 컴포넌트 대부분 children으로 자식 요소를 받을 수 있게 하여 유연함을 증대하는 방향으로 구현하였습니다. 왜냐하면, 저희가 제공하는 의도이 에외도 conanaer와 backdrop만 이용하고싶은 경우 등 사용자가 원하는 방법이 있다고 판단하였기 때문입니다.

### 어려웠던 점

모달 자체의 제작과 배포에는 그래도 크게 어려웠던 점은 없었습니다. 다행히 이전 레벨 2의 첫 미션을 진행하면서 리액트를 활용하여 컴포넌트를 생성하는 것에 적응을 하였던터라 괜찮았습니다. 또 준이 제공한 react-basecamp에서 배포 및 활용에 대한 설명이 잘 되어있었기에 잘 따라갈 수 있었습니다. 

## 커스텀 훅

### 의도

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/f17aaf97-c334-4865-afbc-d7711240ea7b/c3d387d5-d1fc-44c4-9517-e57b5eb2a700/Untitled.png)

useCardNumbers

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/f17aaf97-c334-4865-afbc-d7711240ea7b/0299b43f-5790-4020-a127-370afc35d4d9/Untitled.png)

useExpiryDate

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/f17aaf97-c334-4865-afbc-d7711240ea7b/23732aa6-3a79-4626-b8dd-9f9fa103ee2c/Untitled.png)

useCardHolderName

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/f17aaf97-c334-4865-afbc-d7711240ea7b/1b68d148-8c2f-44f6-bde4-5a3dce86bd0a/Untitled.png)

useCVC

![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/f17aaf97-c334-4865-afbc-d7711240ea7b/5f2e9e69-0622-4782-9675-57c5d646bc55/Untitled.png)

useCardPassword

커스텀 훅을 위와 같이 5개와 각각 컴포넌트의 유효성을 검증하는 validation 훅 총 10개의 커스텀 훅을 구현하였습니다. 이번 미션의 요구사항인 `페이먼츠 카드의 다양한 정보에 대한 유효성 검사 로직을 여러 개의 작은 커스텀 훅으로 분리하고, 필요에 따라 조합하여 사용할 수 있도록 한다.` 의 부분을 보고서 이렇게 validation과 본 훅을 분리하였습니다. 그래서 유효성 검사를 담당하는 커스텀 훅을 생성하였고 이러한 유효성 검사 로직을 조합하여 사용하는 본 훅을 구현하게 되었습니다. 이에 더하여 첫번째 미션인 payments 에서 해당 라이브러리를 가져와 나의 코드에 적용해보려면 어떻게 하는게 좋을까라는 고민의 결과에서도 이렇게 로직을 분리하는 것이 validation만을 필요로 하다면 가지고 와서 나의 각 필드별 훅에 조합한 이후 부수적으로 필요한 것들이 있다면 추가하면 좋겠다는 생각에 분리하게 되었습니다. 

### 어려웠던 점

해당 미션을 구현하면서 어려웠던 점은 타인의 코드를 읽고 이해하는 것이 참 쉽지않구나라는 것을 느꼈습니다. payments 미션의 코드가 페어와 많이 달랐기에 해당 커스텀 훅 라이브러리를 구성하는 것에도 생각의 차이가 있었습니다. 기존에 각자 구현했던 커스텀 훅이 있다보니 해당 커스텀 훅과 거리가 멀어질수록 payments에서 해당 라이브러리를 가져올 경우 수정이 많이 일어나기에 이러한 중간점을 찾는 것이 쉽지않았습니다. 토론한 결과 페어의 코드가 validation의 경우 본 미션구현에 좀 더 합당하다고 납득하였고 페어의 코드를 기반으로 커스텀 훅 라이브러리를 작성하기로 결정하였습니다. 그렇다보니 페어의 코드를 학습해야하는 상황이였는데 페어의 코드를 이해하는 과정이 쉽지 않았습니다. 타인의 코드가 눈에 잘 들어오지않는 것은 당연할 뿐더러 페어의 경우 제가 경험해보지 못했던 코드들이 다수 있어서 더욱 어려움이 심화되었습니다. 예를 들어, 페어의 경우

```tsx
const [cardNumbers, setCardNumbers] = useState<
    Record<CardNumberKeys, string>
  >({
    first: "",
    second: "",
    third: "",
    fourth: "",
  });
```

이처럼 객체 자체를 초기값으로 설정하고 

```tsx
setCardNumbers((prevValue) => {
      return {
        ...prevValue,
        [name]: value,
      };
    });
```

객체의 불변성을 유지하면서 해당 값을 업데이트 하는 로직을 이러한 방법으로 구현하였는데, 개인적으로 이렇게 코드를 구현하는 것을 처음 접했기에 다소 당황했던 부분도 있었습니다. 그러다보니 학습 및 이해하는 시간이 저에게는 필요했습니다. 이해의 깊이를 중간에 따라가지 못하여 다시 보기를 반복하다보니 시간이 자꾸 지체된다는 점이 페어에게 미안함이 느껴지더라고요. 그러면서 괜시리 스스로의 이해력의 부족함을 탓하기도 했던 것 같습니다. 그랬던 점이 조금 힘들기는 하더라고요! 경험의 차이로 인해 코드를 이해하는 힘이 다르기도 하겠지만 서도 이러한 감정이 드는 것은 부정할 수 없네요. 이번 미션을 하면서 유독 그러한 감정이 크게 느껴졌던 것 같아 조금 힘들었습니다. 허허. 시간이 지나면 저 또한 유능해지기를 바라며 열심히 학습해야겠습니다. 

긴 글 읽어주셔서 감사합니다! 의도와 개인적인 감정에 대한 글도 섞여있었네요. 현업과 타인의 코드리뷰를 모두 하시느라 많이 힘드실 것 같네요! 슬슬 날도 더워지는데 화이팅 하셨으면 좋겠습니다! 💪

2024-05-02 12:37 UTC, moonheekim0118 requested changes
안녕하세요 시모! 저도 다시 만나뵙게 되어 너무 반가워요 😊 그간 잘 지내셨나요?ㅎㅎ
미션 해주시느라 고생 많으셨습니다 👏 👏 

PR 본문에도 어떤 생각과 고민을 가지고 미션을 진행하셨는지 적어주셔서 감사해요 :)
일단 컴포넌트를 분리해주신 기준이나, 커스텀 훅을 분리해주신 기준은 정말 적절하다고 생각했습니다. 이미 잘해주셔서 관련해서 코멘트를 남길만한게 많이없었네요ㅎㅎ

그리고 다른 사람이 쓴 코드를 이해하고 새로운걸 배워나가는건 늘 어려운 것 같습니다. 특히나 미션이라는 한정된 시간 속에서 익숙하지 않은 코드와 친해지며, 몰랐던 부분까지 이해하는건 정말 힘들죠 🥲  
나중에 개발자로 업무를 하시게 되시면 타인이 쓴 코드를 정말x1000 많이 마주하게 되실텐데요, 미리부터 하신 요 경험이 언젠가 꼭 빛을 발할거라고 생각합니다ㅎㅎ

그리고 저도 예전엔 다른 사람의 코드 베이스로 작업하는게 참 힘들었던 기억이 있는데요, 다시 생각해보면 힘들었던만큼 제 지식의 넓이나 사고의 유연함을 늘리는 좋은 계기가 되었더라고요. 부족한 점을 부족한대로 평생 두는 것 보다, 이런 계기로 부족함을 빨리 깨달을 수 있다는건 정말 럭키한 것 아니겠어요?!🤭 
아마 고생하셨던 만큼 얻어가시는게 정말 많으실거라 생각합니다ㅎㅎ

몇가지 코멘트 남겼는데 확인해주시고 재요청 주세요! 

(+ 일정 공유해주셔서 감사합니다 🫡 그러면 최대한 1단계 머지는 5/6 안으로 끝내보시죠! )

2024-05-02 12:37 UTC, moonheekim0118 commented on hooks/src/lib/useCardHolderName/useCardHolderNameValidation.ts
> +      setErrorText("알파벳을 입력해 주세요.");
여기에도 만들어주신 상수 (VALIDATION_MESSAGES) 적용해주심 좋을 것 같아요 :)

2024-05-02 12:37 UTC, moonheekim0118 commented on hooks/src/lib/useCardNumbers/useCardNumbers.ts
> +  };
만약 사용자가 name을 first,second,third,fourth 로 설정하지 않으면 어떻게 되나요?
해당 상황에 대한 예외처리가 추가되면 좋을 것 같습니다!

또한 input의 name 속성을 기준으로 각 필드의 상태를 업데이트 하는건 사용자에게 너무 책임을 너무 전가시키는 것 같은데요,
사용자가 더 간단하게 각 필드의 업데이트 함수를 호출하게끔 하는 방법은 없을까요?

2024-05-02 12:37 UTC, moonheekim0118 commented on hooks/src/lib/validators/cardInputValidator.ts
> +  },
정규표현식은 그 자체로 봐서는 어떤걸 의미하는지 바로 파악이 어렵기 때문에, 
정규표현식의 내용을 주석으로 추가해주시면 협업시 되움이 됩니다 :)

2024-05-02 12:37 UTC, moonheekim0118 commented on hooks/src/lib/validators/cardInputValidator.ts
> +    return number >= min && number <= max ? true : false;
```suggestion
    return number >= min && number <= max;
```
다른 곳도 마찬가지이네용!

2024-05-03 05:29 UTC, simorimi commented on hooks/src/lib/validators/cardInputValidator.ts
> +    return number >= min && number <= max ? true : false;
그렇네요. 해당 부분은 true, false를 뱉는 것이 의미가 없겠네요! 코드를 읽을 당시에는 자연스럽게 이해의 초점만 맞춰서 보다보니 이렇게 리팩토링에 대해서는 크게 생각을 못했던 것 같네요! 좋은 피드백 감사합니다! :)

2024-05-03 05:37 UTC, simorimi commented on hooks/src/lib/validators/cardInputValidator.ts
> +  },
주석의 활용을 이런식으로 할 수 있군요! 피드백 덕분에 협업의 관점을 더욱 생각해보게 되었네요. 늘 읽기 좋은 코드라는 것이 협업을 위해서 또 미래의 나를 위해서 한다는 사실을 더욱 인지하도록 노력해야겠습니다. 좋은 피드백 감사합니다 :)

2024-05-03 06:08 UTC, simorimi commented on hooks/src/lib/useCardHolderName/useCardHolderNameValidation.ts
> +      setErrorText("알파벳을 입력해 주세요.");
그렇습니다!.. 이 부분은 제출하고 나서 페어와 얘기도중 발견하였습니다. 허허. 놓친 부분들이 꽤나 많군요! 조금 더 신경을 쓰겠습니다. 좋은 피드백 감사합니다! :)

2024-05-05 09:28 UTC, simorimi commented on hooks/src/lib/useCardNumbers/useCardNumbers.ts
> +  };
name에 대한 설정없이 더 간단하게 호출하는 방법이 무엇이 있을까 고민하였습니다. 그 결과, 사용자가 해당 커스텀 훅을 호출할 때 각 필드별 핸들러를 호출할 수 있도록 즉,  name에 대한 속성없이 각 필드별 onChange props에 핸들러만 넣어주면 값을 업데이트 할 수 있도록 하였습니다. 이를 위하여 전체 객체로 상태를 업데이트하던 useCardNumbers useCardNumber이라는 커스텀 혹으로 분리하여 각 필드별로 상태를 받을 수 있도록 수정하였습니다!

2024-05-05 14:08 UTC, simorimi commented on hooks/src/lib/useCardNumbers/useCardNumbers.ts
> +  };
추가로 expiryDate 또한 위의 경우에 해당하기에 각 커스텀 훅으로 분리해보았습니다. 이 경우 cardNumber 보다 고려할 사항이 많아서 month와 year 그리고 두 값을 모두 고려하여 유효기간을 검증하는 훅까지 여러 훅으로 분리하였는데요. 생각보다 커스텀 훅이 많이 늘어나게 되었는데 제가 생각하기에는 각 유효함을 검증한 다음 전체가 지나지 않은 년도인지를 판단하기위해서는 적절하다고 생각하는데 분리의 정도가 적절한지 호프의 의견이 궁금하네요!

2024-05-05 14:26 UTC, simorimi commented on components/src/lib/Modal/Button.tsx
> +const StyledButton = styled.button<{ $theme: ButtonColor }>`
아니요! 저의 원래 선호는 스타일 코드를 분리하는 것을 선호합니다! 이번에 이렇게 한 곳으로 모은 것은 페어의 의견을 따라가게 되어서 그렇습니다. 그 당시 저의 생각으로는 둘이 의견이 다른 상황에서 크게 부딪칠 부분은 아니라는 생각에 한 곳에 있는 것을 분리하는데 그렇게 오래 걸리지않으니 나중에 헤어지고 분리하면 되겠다고 생각하였습니다!

2024-05-05 16:31 UTC, simorimi commented on components/src/lib/Modal/Button.tsx
> +  children: React.ReactNode;
ReactNode의 경우 ReactElement보다 큰 범주로 ReactElement에 더불어 number, string, boolean, null, undefined 등을 추가로 가질 수 있는 타입입니다!. 해당 타입을 이번 페어 과정을 통하여 처음 알게 되었는데 처음에는 jsx.Element 형식으로 사용하려고 하였습니다. 그러던 중 페어가 해당 타입을 사용하면 <> </>로 묶는 과정 필요없이 사용할 수 있다고 소개해주어 사용하게 되었는데요. 해당 부분에서는 주로 jsx.Element를 받으니 타입을 너무 넓게 가질 필요는 없어보이네요! 질문해주시지 않았더라면 모르고 넘어갔을 부분이었을텐데 감사합니다! :)

2024-05-05 18:01 UTC, simorimi commented on components/src/lib/Modal/Button.tsx
> +  dark: `
좋은 글이네요! 해당 글을 읽어보면서 함수를 이용하거나 여러 속성들을 바꿀 때 css helper를 이용하면 좋겠다는 기준이 나름 생긴 것 같습니다! 좋은 피드백 감사합니다! :)

2024-05-05 18:23 UTC, simorimi commented on components/src/lib/Modal/Button.tsx
> +export interface ButtonProps {
버튼의 타입을 기존의 버튼속성에서 확장하니 훨씬 좋네요! 이렇게 제공한다면 사용자 입장에서 훨씬 더 유연하게 사용할 수 있을 것 같다는 생각이 들었습니다! 좋은 피드백 감사합니다! :)

2024-05-05 18:49 UTC, simorimi commented on components/src/lib/Modal/CloseButton.tsx
> +    />
의미를 명확하게 전달할 수 있는 테그를 우선적으로 쓰는게 좋군요! 좋은 피드백 감사합니다! 이 부분에 대해서 해당 엑스 이미지를 사용하기위하여 고민 끝에 button 테그 안에 img 테그를 넣는 방식으로 했는데 이것은 어떠한가요? button의 의미를 명확하게 전달한다고 볼 수 있나요?

2024-05-05 19:07 UTC, simorimi commented on components/README.md
> +    <Modal>
좋은 피드백 감사합니다! modal에 props로 isOpen이라는 boolean 값을 받은 뒤 boolean의 true, false 여부에 따라 display를 block이나 none으로 해주면 해결이 되네요! 이렇게 방법을 권유하시는 이유가 조건부 렌더링을 할 때 보다 사용자가 훨씬 편하게 사용할 수 있기 때문인가요?

2024-05-05 19:19 UTC, simorimi commented on components/src/lib/Modal/Container.tsx
> +  box-sizing: border-box;
GlobalStyle을 추가하면서 여기에 styled-reset의 reset을 추가 해보았습니다! 처음에는 해당 부분에 대해서는 사용자가 자신의 프로젝트를 진행할 때 각자 reset-css를 가지고 있을 것이라고 예상해 추가하지않는게 맞지않을까라고 생각하여 추가하지 않았습니다. 그러나 피드백 받아보고 생각해보니 제공자 측에서 해당 부분들을 제공해주어야 사용자 입장에서 혼란을 덜 겪을 수 있지않을까라는 생각이 드네요! 사용자가 reset-css를 가지고있든 말든 해당 부분을 가진채 제공해주어야 reset-css가 없는 경우에도 혼란이 없이 사용할 수 있을 것 같네요 좋은 피드백 감사합니다! :)

2024-05-05 20:01 UTC, simorimi commented on components/src/lib/Modal/Modal.tsx
> +  width: 376px;
모달의 컨테이너가 fix 값이 아니라 absolute로 되어있다보니 modal 자체에서 움직여서 그랬던 것 같습니다! 처음에 이렇게 absolute 값으로 하려고 했던 것은 modal 크기의 %로 따라가고자 하였었으나 생각해보니 modal의 크기를 결정하는게 더 이상하게 느껴지더라고요. modal의 크기는 정해진 것이 아니라 실제 화면을 따라가는게 자연스럽다고 느껴지며 backdrop과 container의 경우 position fixed 여야 자연스러운 모달의 화면을 볼 수 있다고 생각이 들었습니다. 그래서 modal의 position이나 width를 제거하는 방향으로 수정하였습니다. 현재 모달을 키면 화면 width에 맞춰서 결정되어집니다! 이게 더 자연스러운 방향이라 생각하여 수정하였고 기존의 값을 고정하는 것 보다 해당 방법을 이용하는 것이 훨씬 유연하게 이용할 수 있을 것이라는 생각하에 해당 방향으로 수정하였습니다! 좋은 피드백 감사합니다! :)

2024-05-05 20:27 UTC, simorimi commented on components/src/lib/Modal/Button.tsx
> +      background-color: #1f1f1f;
payments 미션에서 themeProvider를 사용해보면서 편리함을 느꼈었습니다! 이번 미션에서는 그렇게 복잡하지않아서 해당 작업을 해주지 않았었는데 유연한 대응을 위해서 미리 해보는 것도 괜찮을 것 같네요 좋은 피드백 감사합니다! :)

2024-05-06 10:18 UTC, moonheekim0118 commented on components/src/lib/Modal/Button.tsx
> +  children: React.ReactNode;
오 상세한 설명 감사합니다 👍 👍

2024-05-06 10:20 UTC, moonheekim0118 commented on components/src/lib/Modal/Button.tsx
> +const StyledButton = styled.button<{ $theme: ButtonColor }>`
아하 배경을 알려주셔서 감사합니다 :) 저도 사실 분리하는걸 선호합니다. 결국 파일 분리를 통해서 스타일과 컴포넌트의 관심사가 분리된다구 생각해서요ㅎㅎ

2024-05-06 10:22 UTC, moonheekim0118 commented on components/src/lib/Modal/Container.tsx
> +  box-sizing: border-box;
오 그런 히스토리가 있었군요!
저도 라이브러리 자체에서 어느정도 reset-css가 적용되어있어야한다구 생각합니다ㅎㅎ
사용자가 제어하는 style 영역과 라이브러리 컴포넌트의 style 영역은 별개로 분리되는게 맞다고 생각해서요.
의견 나누어주셔서 감사합니다 👍

2024-05-06 10:25 UTC, moonheekim0118 commented on components/README.md
> +    <Modal>
저는 그렇게 생각했어요ㅎㅎ 해당 라이브러리 사용처에서, 제공된 컴포넌트를 더 선언적으로 사용 할 수 없을까?하는 관점에서 말씀드렸었습니다 :)

혹시 리액트의 Suspense 나 ErrorBoundary 와 같은 컴포넌트들을 아시나요?
해당 컴포넌트들이 어떤식으로 사용되는지와 연결지어서 생각해봐주셔도 좋을 것 같아요. :)

2024-05-06 10:37 UTC, moonheekim0118 commented on hooks/src/lib/useCardNumbers/useCardNumbers.ts
> +  };
아하 
month 검증 / year 검증 /  date 검증 이렇게 나눠진 것 같은데, 저도 이 정도 분리는 적절하다고 생각이 듭니다 👍 
추가로 너무 훅이 많아서 복잡한 것 같으면 훅에 주석을 추가해주셔도 좋겠네용ㅎㅎ
처음보는 사람은 date 검증과 month, year 검증이 각각 어떤 차이인지 잘 모를 수도 있겠다 싶어서요.

2024-05-06 10:49 UTC, moonheekim0118 approved these changes
안녕하세요 시모! 반영해주신 사항 확인했습니다 👏 👏 연휴에도 작업해주시느라 고생 많으셨어요 :)

질문 주신 부분에 대해서 코멘트 남겨놨고, 추가로 소소한 코멘트 몇가지 남겼으니 확인 부탁드려요!
남겨드린 코멘트가 크리티컬 하지는 않은 것 같아서 다음 단계에 같이 반영해주시면 되겠습니다 😄 

추가로 2단계에서는 UI 컴포넌트 라이브러리 코드 샌드박스 링크를 리드미에 첨부해봐주셔도 좋을 것 같아요. :) (그리고 스토리북 배포 링크도 추가해주실 수 있으실까요?)

그럼 고생하셨습니다! 다음 단계에서 뵈어요 👋

2024-05-06 10:49 UTC, moonheekim0118 commented on hooks/src/lib/useExpiryDate/useExpiryDateValidation.ts
> +      return true;
그나저나 여기 return true/false 는 어디에 사용되나요?
제가 봤을 대는 해당 함수 리턴값을 활용하는 곳이 없는 것 같아서요!

2024-05-06 10:49 UTC, moonheekim0118 commented on hooks/src/lib/useExpiryDate/useExpiryDateValidation.ts
> +      )
parseInt 활용해주신 이유가 있을까요?
Number() vs parseInt 의 차이점을 알아보셔도 좋을 것 같아요 :)

2024-05-06 10:49 UTC, moonheekim0118 commented on components/package.json
> -  "description": "npm modules",
변경된 사항 배포 되었을까요?! 
배포되었다면 버전 업 시켜주세용ㅎㅎ

2024-05-06 10:49 UTC, moonheekim0118 commented on components/src/theme.ts
> +
Theme 사용 좋아요 👍   더 나아가서 light, dark 테마별로 컬러값들을 분리해서 관리해봐도 좋을 것 같아요 :) 
아래는 그냥 예시입니다ㅎㅎ

```tsx
  color: {
    light: {
        text: '#1f1f1f';
        background: '#fffff';
    },
    dark: {
        text: '#ffffff';
        background: '#1f1f1f';
    }
  },
```

2024-05-06 10:49 UTC, moonheekim0118 commented on components/src/styled.d.ts
오 굿ㅎㅎ 👍 
요건 타입스크립트의 어떤 기능을 이용해서 가능한걸까요?

2024-05-06 10:49 UTC, moonheekim0118 commented on components/src/lib/Modal/Modal.tsx
> +};
저는 isOpen 관련해서 dipslay:none, block 처리까지 안가도 요렇게 조건부 렌더링을 라이브러리 컴포넌트 내부에서 처리해주면 되지 않을까 생각했습니다ㅎㅎ

```suggestion
const Modal = ({ isOpen, children }: ModalProps) => {
  return {isOpen ? <Styled.Modal>{children}</Styled.Modal> : null };
};
```

2024-05-06 10:50 UTC, merged

2024-05-10 08:07 UTC, simorimi commented on hooks/src/lib/useExpiryDate/useExpiryDateValidation.ts
> +      return true;
모여져있던 로직을 분리하는 과정에 남겨둔 것 같네요.. 하하 early return의 용도로 해당 부분이 필요는 하나 호프의 말씀대로 boolean 값을 뱉을 이유는 없어보입니다! 꼼꼼히 봐주셔서 정말 감사합니다! 조금 더 코드의 의미를 생각하면서 짜봐야겠네요 :)

2024-05-10 08:22 UTC, simorimi commented on hooks/src/lib/useExpiryDate/useExpiryDateValidation.ts
> +      )
이 부분에 대해서도 페어의 의견을 따라갔었습니다. 사실 이 부분에 대해서는 토론의 과정을 못 나눈 것 같네요. parseInt를 처음 보는 상황이었고 코드에 대한 토론보다는 이해에 초점이 맞춰지다보니 해당 부분을 왜 사용했는지에 대해서 짚고넘어가지 못했었습니다. 호프의 피드백 덕분에 해당 부분에 대해서 한번 생각해보게 되었네요. 사실 해당 코드들은 전부 문자열을 10진수의 숫자로 바꿔주는 부분이다보니 굳이  parseInt를 사용할 필요없이 Number를 활용하여도 충분히 10진수로 바꿔주기에  parseInt를 사용할 이유가 타당해보이지 않네요. 만약 10진수가 아니라 다른 진수로 바꾸는 과정이었다면 당연히 parseInt를 사용하는 것이 타당할텐데 말이죠. 그 이외에 문자열이 섞여있을 떄 어느정도까지 parsing하는지의 차이와 소수점 이하의 값 처리에 대한 차이도 알아볼 수 있었습니다! 좋은 피드백 감사합니다 :)

2024-05-10 08:23 UTC, simorimi commented on components/package.json
> -  "description": "npm modules",
넹 이번 step2 진행 후 배포 하겠습니다! 피드백 감사합니다 ㅎㅎ

2024-05-10 08:27 UTC, simorimi commented on components/src/lib/Modal/Modal.tsx
> +};
오 해당 방법은 전혀 생각해보지 못했었네요. 조건 연산자를 return 마다 적용해 줄 생각은 전혀 못했었습니다. 늘 전체 불러 오는 곳에서만 해당 부분을 적용하다보니 이러한 접근에 대해서 의식하지 못했었네요! 좋은 피드백 정말 감사합니다!!

2024-05-10 08:53 UTC, simorimi commented on components/src/theme.ts
> +
처음에 저의 생각은 해당 부분에서 text의 색상은 theme.color.white 이런식으로 보여주는 것이 낫겠다는 생각을 했었습니다. 코드를 읽는 사람이 아 text는 흰색이구나 이렇게요. 그런데 피드백 받고서 생각해보니 해당 방법보다 더 선언적으로 관리하는 것이 더 좋을 수 있겠다는 생각이 드네요! 어떻게 보면 무슨 색인지 아는 것보다 어떤 부분의 색인지를 아는 것이 더 나을 것 같다는 생각이 듭니다! 좋은 피드백 감사합니다! :)

2024-05-10 09:44 UTC, simorimi commented on components/src/styled.d.ts
declare를 통해 모듈을 선언하는 행위인데 해당 방법을 통해서 모듈 안에 타입을 정의하거나 재정의하는 작업을 할 수 있습니다! 이를 통해 styled-components 모듈의 DefaultTheme 안에 속성들을 추가하여 스타일 컴포넌트를 활용할 때 theme를 불러올 수 있습니다! 이처럼 theme에 속성들을 추가하기위하여 해당 방법을 이용하였습니다!