[1단계 - 페이먼츠 모듈] 에프이(박철민) 미션 제출합니다.
woowacourse/react-modules pull request #28
Opened 2024-05-02 08:36 UTC by chysis

안녕하세요 하루! 에프이입니다. 

파란과 함께 재사용 가능한 모듈화된 모달 컴포넌트와 카드 유효성 검사 커스텀 훅을 구현하고, npm에 배포했습니다.

지금까지는 `npm install`만 해왔는데, 직접 만든 컴포넌트와 훅을 배포해보니 굉장히 재밌네요! 더불어 버전 관리까지 하니 정말로 서비스하는 느낌이 듭니다.😊

하지만 주어진 요구사항대로 페이지를 만드는 것이 아닌, 다른 페이지에서 유연하게 사용될 수 있도록 작은 단위의 컴포넌트와 훅을 만들어야 했기 때문에 많이 어려웠던 것 같습니다. 라이브러리가 사용자에게 어느 정도까지 메서드와 값을 제공해야 하는지가 주된 고민이었어요. 특히 커스텀 훅의 경우 어느 정도까지 작은 단위로 분리해야 할지 감을 잡기가 힘들었습니다. 그래서 우선은 `input form 단위`로 유효성 검사 훅을 분리했습니다.

카드 input form마다 제공할 수 있는 에러 메시지를 모두 배열에 담아 사용자에게 제공하고, 사용자가 필요한 메시지를 골라서 렌더링할 수 있게 했습니다. 메시지를 모두 제공하긴 하지만 0번 인덱스에 논리적으로 가장 먼저 보여져야 할 메시지를 담았습니다(유효성 검사 순서와 관련 있습니다).

## **🌐**배포 주소

모달: [[바로가기](https://www.npmjs.com/package/fe-custom-modal)](https://www.npmjs.com/package/fe-custom-modal)

모달 storybook: [[바로가기](https://6631dad3ab74b00107d09938-mbvlnyhhgn.chromatic.com/?path=/story/modal-center--modal-with-buttons-and-title)](https://6631dad3ab74b00107d09938-mbvlnyhhgn.chromatic.com/?path=/story/modal-center--modal-with-buttons-and-title)

커스텀 훅: [[바로가기](https://www.npmjs.com/package/fe-card-validation-hooks)](https://www.npmjs.com/package/fe-card-validation-hooks)

## 📚구현 내용

### modal

- modal 컴포넌트가 prop으로 받는 속성들을 모두 README에 적어두었습니다.
- `children`, `modalPosition`, `cancelButton`을 필수로 받습니다.
- `title`, `subtitle`, `confirmButton`, `cancelButton`, `backgroundColor`, `borderRadius`는 optional parameter입니다.
    - 확인 버튼과 취소 버튼은 prop이 전달되면 렌더링됩니다. 기본 상태에서는 버튼 없는 모달이 만들어집니다.
    - title, subtitle의 position도 결정할 수 있습니다.

### hooks

- 총 6개의 커스텀 훅을 제공합니다.
    - useCardNumberValidation
    - useExpiryDateValidation
    - useCVCValidation
    - useCardHolderValidation
    - useCardPasswordValidation
    - useCardTypeValidation - 비자카드와 마스터카드 결정
- 각 훅별로 `반환하는 값과 그 타입`, `사용 예시`, `반환 에러 문자열`을 제공합니다.
- `useCVCValidation`의 경우 CVC번호가 3자리 또는 4자리인 카드가 있다는 점을 고려해서 `maxLength`를 인자로 받아 유효성 검사합니다.
- `useCardPasswordValidation`의 경우 앞 두 자리 뿐 아니라 전체 비밀번호를 받는 상황을 고려해서 `maxLength`를 인자로 받아 유효성 검사합니다.
- `useCardHolderValidation`의 경우 사용자가 원하는 길이만큼 유효성 검사할 수 있도록 `maxLength`를 인자로 받습니다.

## ⁉️고민한 내용

- 하나의 input에 여러 개의 에러가 발생할 수 있는데, 그 중 하나의 에러 메시지만 사용자에게 제공할지, 모든 메시지를 제공할지 고민했습니다. 그 결과 모든 메시지를 제공하는 것으로 결정했습니다.
- 모달 컴포넌트의 storybook의 docs에서 화면이 제대로 보이지 않는 현상이 발견되었습니다. 아직 해결하지 못했습니다.

## ❓질문

### styled-components vs. CSS Module

- 모달 컴포넌트의 경우 props에 따라 스타일링을 다르게 해줘야 했기 때문에 styled-component로 구현하는 것이 편리했습니다. 하지만 styled-components 의존성이 추가로 필요하기 때문에 사용자가 이를 원하지 않을 수 있다는 점에서 의존성이 필요 없는 CSS Module을 적용했습니다.
- CSS Module로 분기 처리를 하다 보니 불가피하게 `inline style`을 적용해야 했고, 결과적으로 코드의 복잡도가 증가했습니다.
- styled-component를 포기하면서 개발자의 입장에서 편리함을 어느 정도 내려놓게 되었지만 사용자의 입장을 조금 더 생각할 수 있었는데요, 적정선을 어느 정도로 잡아야 할지 잘 모르겠습니다. 하루의 의견을 듣고 싶어요🤔

아직 재사용성을 높이기 위해 어떤 사고를 가지고 어떤 시도들을 할 수 있을지 감이 잘 오지 않네요...☹️ 가감없는 피드백 부탁드려요!
감사합니다.

2024-05-02 16:54 UTC, 365kim commented on components/README.md
> +- [ ] npm publish
🚀

2024-05-02 16:55 UTC, 365kim commented on components/src/index.css
>  }
앗 이 스타일을 `*`로 설정해주신 이유가 있을까요?

2024-05-02 16:57 UTC, 365kim commented on components/package.json
> +    "dev": "vite --host",
> chore: 페어 프로그래밍을 위한 script 수정

커밋 메시지 너무 친절해요 🥹 다른 커밋들도 너무 알기쉽게 잘 작성해주셨네요 👍 감사합니다

2024-05-02 17:05 UTC, 365kim commented on hooks/package.json
> +    "paran-fe-card-validation-hooks": "^0.0.1",
`"paran-fe-card-validation-hooks"` 혹시 이 패키지는 무엇인가요? 로컬에서 설치가 안되는데 도움 부탁드려보아용

<img width="968" alt="Screenshot 2024-05-03 at 2 04 10 AM" src="https://github.com/woowacourse/react-modules/assets/60066472/e820e742-bcec-4d8e-bceb-ac7b2198fe1c">

<img width="399" alt="image" src="https://github.com/woowacourse/react-modules/assets/60066472/03bbd1ff-c991-4cd1-985c-e77df2cc081e">

2024-05-02 17:08 UTC, 365kim commented on components/src/lib/interfaces.ts
> +}
킁킁.. 어디선가 고수의 향기가.. 킁킁..

2024-05-02 17:10 UTC, 365kim commented on components/src/lib/Modal.module.css
> +.container-center {
> style(Modal): 모달 컴포넌트 스타일 작성

사소한데 일반적인 커밋 컨벤션에서의 `style:`은 CSS 스타일 코드를 의미하지 않고, 코드의 포맷팅 등을 의미합니다. 프론트엔드에서 스타일을 다루다보니 조금 헷갈리는데 아래 내용을 참고해주시면 좋을 것 같습니다.

- style (formatting, missing semi colons, …)
- 참고: https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#heading=h.t7ifoyph8bd3

2024-05-02 17:12 UTC, 365kim commented on components/src/lib/Modal.tsx
> +          </span>
닫기 버튼의 접근성 속성도 챙겨볼 수 있을까용?

2024-05-02 17:15 UTC, 365kim commented on components/src/lib/Modal.tsx
> +        </div>
`draw-*` 함수 대신 리액트 컴포넌트로 작성해보는 것은 어떨까요?

2024-05-02 17:17 UTC, 365kim commented on components/README.md
> +- font-size? `default: 18px`
코드가 아닌 문서에서는 `(optional)` 이렇게 명시해주면 어떨까요? 문서이다보니 `?`는 살짜쿵 단순 물음표 처럼 읽혀서 제안드려보아요

![Screenshot 2024-05-03 at 2 16 55 AM](https://github.com/woowacourse/react-modules/assets/60066472/e788190c-9266-423c-af8e-4a85e0cd93e5)

2024-05-02 17:22 UTC, 365kim commented on hooks/src/lib/useCVCValidation.ts
> +      errors.push(`${maxLength}자로 입력해주세요.`);
> 하나의 input에 여러 개의 에러가 발생할 수 있는데, 그 중 하나의 에러 메시지만 사용자에게 제공할지, 모든 메시지를 제공할지 고민했습니다. 그 결과 모든 메시지를 제공하는 것으로 결정했습니다.

오 이렇게 세심하게 고민해주시다니 👍

`'숫자, n자 이상' 조건으로 입력해주세요.` 처럼 묶어서 표현하는 경우도 본 것 같네요 :)

2024-05-02 17:24 UTC, 365kim commented on hooks/src/lib/useCardNumberValidation.ts
> +  errorMessage?: string[];
배열이라면 변수 네이밍도 복수형으로 하면 어떨까요?

2024-05-02 17:27 UTC, 365kim commented on hooks/src/lib/useCardTypeValidation.ts
> +}
뎁스 없이 type alias로 타이핑하는 방법이 아니라, `cardType`이라는 키값을 가지도록 타이핑 해주신 이유가 궁금합니당 :)

2024-05-02 17:28 UTC, 365kim commented on hooks/src/lib/useCardTypeValidation.ts
> +    ) {
이정도로 if문 조건식이 길어지면 가독성을 위해 로컬 변수로 한번 선언해줘도 좋을 것 같습니다 :)

2024-05-02 17:30 UTC, 365kim commented on hooks/src/test/useCVCValidation.test.ts
> +  it('아직 아무 입력도 수행되지 않았을 때 true를 반환해야 함', () => {
테스트 이름만 보면 (무언가의) true 반환 여부만 테스트할 것 같은데, errorMessage의 길이도 검증하고 있네요. 이것을 포괄하도록 테스트 이름을 변경해보면 어떨까요?

2024-05-02 17:31 UTC, 365kim commented on hooks/src/lib/constants.ts
> +};
전반적으로 코드가 정말 정말 깔끔하네요. 상수화도 잘되어있고, 네이밍 센스도 좋으시고, 매우 일관적으로 전개되어서 가독성 최고에요 👏

2024-05-02 17:32 UTC, 365kim commented on hooks/README.md
> +```tsx
👍

2024-05-02 17:33 UTC, 365kim commented on hooks/README.md
> +  ))}
여긴 왠지 return으로 감싸져야할 것 같은데 맞을까용?

2024-05-02 17:34 UTC, 365kim commented on hooks/package.json
> +  "description": "custom card validation hooks",
👍

2024-05-02 17:35 UTC, 365kim commented on hooks/package.json
>    "types": "dist/index.d.ts",
라이브러리 사용자는 어떤 타입정보를 제공받을 수 있을까요?

2024-05-02 17:47 UTC, 365kim commented on components/src/stories/ModalBottom.stories.ts
> +    cancelButton: { content: '취소', onCancel: () => {} },
요구사항이 확장되어, 버튼을 위 아래로 나열해야한다면 어떻게 대응하면 좋을까요?

![image](https://github.com/woowacourse/react-modules/assets/60066472/d4423698-d7e5-48d8-b299-6c5529a1f8a1)

2024-05-02 17:48 UTC, 365kim commented on components/src/stories/ModalBottom.stories.ts
> +    children: 'Children will go here',
🛝

2024-05-02 17:51 UTC, 365kim commented on components/src/stories/ModalCenter.stories.ts
> +  tags: ['autodocs'],
> 모달 컴포넌트의 storybook의 docs에서 화면이 제대로 보이지 않는 현상이 발견되었습니다. 아직 해결하지 못했습니다.

오 이건 혹시 코파일럿이 작성한 코드인가요? 

아래 문서의 설정을 참고해주셔도 좋을 것 같습니다 :)

- https://storybook.js.org/docs/writing-docs/autodocs

2024-05-02 18:00 UTC, 365kim commented on components/src/stories/ModalCenter.stories.ts
> +  tags: ['autodocs'],
또 요구사항이 확장되어서, 모달의 크기를 구체적으로 지정할 수 있어야하면 어떻게 대응하면 좋을까요?

2024-05-02 18:04 UTC, 365kim commented on components/src/stories/ModalCenter.stories.ts
> +const meta = {
스토리북에서 모달을 열고 닫는 동작을 확인할 수 있으면 좋겠습니다.

2024-05-02 18:04 UTC, 365kim commented on components/src/stories/ModalCenter.stories.ts
> +import '../index.css';
`index.css`를 개별 스토리 파일을 생성할 때마다 import하지 않고, 한번만 import 하는 방법이 있을까요?

2024-05-02 18:08 UTC, 365kim commented on components/src/lib/Modal.tsx
> +            <h1
헤딩 태그 챙겨주신 것 좋네요 👍

피그마 시안의 "카드사 선택", "약관에 동의해주세요"를 문서 최상단 헤딩인 h1으로 볼 수 있을까요?

- 참고: https://developer.mozilla.org/ko/docs/Web/HTML/Element/Heading_Elements

> 페이지 당 하나의 \<h1\>만 사용하세요. 여러 개를 써도 오류는 나지 않겠지만, 단일 \<h1\>이 모범 사례로 꼽힙니다. 논리적으로 생각했을 때도, \<h1\>은 가장 중요한 제목이므로 전체 페이지의 목적을 설명해야 할 것입니다. 두 개의 제목을 가진 책이나, 여러 개의 이름을 가진 영화는 볼 수 없죠! 또한 스크린 리더 사용자와 SEO에도 더 적합합니다.

2024-05-02 18:23 UTC, 365kim commented on components/src/lib/Modal.tsx
> +              style={{ fontSize: title.fontSize || '18px', color: title.color || 'black' }}
> 하지만 styled-components 의존성이 추가로 필요하기 때문에 사용자가 이를 원하지 않을 수 있다는 점에서 의존성이 필요 없는 CSS Module을 적용했습니다.

라이브러리 라는 특수성을 잘 고려하여 판단해주신 것 같습니다. 👍

> CSS Module로 분기 처리를 하다 보니 불가피하게 inline style을 적용해야 했고, 결과적으로 코드의 복잡도가 증가했습니다.
styled-component를 포기하면서 개발자의 입장에서 편리함을 어느 정도 내려놓게 되었지만 사용자의 입장을 조금 더 생각할 수 있었는데요, 적정선을 어느 정도로 잡아야 할지 잘 모르겠습니다. 하루의 의견을 듣고 싶어요🤔

기술적 의사결정에 대한 기준을 무엇을 삼을지 고민된다는 말씀으로 이해했어요. 

DX, 유지보수성 중요하지요. 라이트한 라이브러리를 만드는 것도 중요하고요. 상충되는 지점 사이에 균형을 찾는 것은 참 어려운 일이에요. 다르는 이미 좋은 기술적 의사결정을 내려주셨지요. styled-components를 의존성에 포함시키는 결정을 할 수도 있었음에도 말이에요. 앞으로도 지금처럼 상황에 맞추어 다르가 생각하시기에 더 유리하다고, 더 적합하다고 생각되는 방향으로 결정해주시면 좋을 것 같습니다.

선택한 결과에 따라 새로운 불편한 점이 생겼다면, 그것을 해소할 수 있는 다른 방법이나 도구는 없을지 찾아보는 방법도 있을 것 같습니다.

2024-05-02 18:27 UTC, 365kim requested changes
에프이, 안녕하세요

1단계 작업해주신 것 잘봤습니다. 
코드가 정말 깔끔하고... 일관성 있으면서 또, 인터페이스 설계에서 노련미(?)가 느껴지네요 👍

몇 가지 코멘트 남겼는데 천천히 확인해보시고 반영 완료되시면 리뷰 재요청 부탁드릴게요.
수고하셨습니다 👏

2024-05-03 05:12 UTC, chysis commented on hooks/package.json
> +    "paran-fe-card-validation-hooks": "^0.0.1",
파일을 각자 이름으로 배포하기 이전에 공동으로 배포하려고 했을 때 붙였던 이름입니다! 제가 미처 확인을 못했네요😅 재배포했습니다!

2024-05-03 05:31 UTC, chysis commented on components/src/index.css
>  }
reset.css로 제공되는 파일을 그대로 가져와서 사용했기 때문에 별다른 이유는 없었습니다😅
말씀해주셔서 생각해볼 기회가 된 것 같아요. 모달에서는 버튼이나 이미지 요소에만 드래그가 안 되는 것이 좋을 것 같아 선택적으로 적용해보았습니다 ㅎㅎ

2024-05-03 05:50 UTC, chysis commented on components/src/lib/Modal.module.css
> +.container-center {
감사합니다! `css` 관련 수정 내역은 `design`을 사용해야겠네요. 다른 타입들도 다시 한 번 살펴볼 수 있었습니다 :)

2024-05-05 09:28 UTC, chysis commented on components/src/lib/Modal.tsx
> +          </span>
`aria-label` 속성을 사용해서 스크린 리더 사용자를 고려할 수 있도록 수정했습니다!

2024-05-05 09:30 UTC, chysis commented on components/src/lib/Modal.tsx
> +        </div>
조금 더 리액트스럽게(?) 생각하지 못했던 부분인 것 같아요😅
각 버튼들을 컴포넌트로 분리했습니다!

2024-05-05 09:47 UTC, chysis commented on components/README.md
> +- font-size? `default: 18px`
일반 문서에서는 그렇게 보일 수도 있겠네요!
`optional` 을 명시해주었고, 나아가서 패키지 설치 방법도 README 상단에 언급해두었습니다 :)

2024-05-05 10:04 UTC, chysis commented on hooks/src/lib/useCVCValidation.ts
> +      errors.push(`${maxLength}자로 입력해주세요.`);
묶어서 표현하는 것도 하나의 방법이 될 수 있을 것 같아요!

에러 메시지를 여러 개 표시해주다 보니 사용자가 몇 번 인덱스에 어떤 메시지가 들어있는지를 확인한 후에 사용해야 한다는 불편함이 있을 것 같아요.
그런 점에서 에러 메시지를 전달하는 방법을 조금 더 고민해볼 것 같습니다 :)

2024-05-05 10:13 UTC, chysis commented on components/src/stories/ModalBottom.stories.ts
> +    cancelButton: { content: '취소', onCancel: () => {} },
개발 단계에서 사용자로부터 너무 많은 정보를 받는 것은 아닐지 페어와 함께 고민했던 부분이었는데 이젠 확신을 가질 수 있을 것 같아요🫠

`buttonsDirection`이라는 prop으로 선택할 수 있도록 수정했습니다!

2024-05-05 11:02 UTC, chysis commented on hooks/src/lib/constants.ts
> +};
감사합니다 하루!!

2024-05-05 11:53 UTC, chysis commented on hooks/README.md
> +  ))}
맞아요...! 실수했습니다🥲
꼼꼼한 피드백 감사합니다!

2024-05-05 12:12 UTC, chysis commented on hooks/src/lib/useCardNumberValidation.ts
> +  errorMessage?: string[];
복수형이 좀 더 적절한 것 같네요! 수정했습니다 :)

2024-05-05 12:16 UTC, chysis commented on hooks/src/lib/useCardTypeValidation.ts
> +}
두 가지 이유로 interface를 사용했습니다!

1. 다른 컴포넌트들과의 구조적 통일성을 지키기 위함입니다.
2. 요구 사항이 변경되는 경우 `cardType` 이외의 값을 함께 반환할 수도 있기 때문입니다.

2024-05-05 12:17 UTC, chysis commented on hooks/src/lib/useCardTypeValidation.ts
> +    ) {
반복되는 부분이다 보니 말씀하신 대로 리팩토링하는 것이 적절할 것 같습니다!

2024-05-05 12:47 UTC, chysis commented on hooks/src/test/useCVCValidation.test.ts
> +  it('아직 아무 입력도 수행되지 않았을 때 true를 반환해야 함', () => {
반환하는 값으로 테스트를 하는 것이니 테스트 이름에 반환되는 값의 상태를 구체적으로 언급해야겠네요!
`~true를 반환하고 에러 메시지가 없어야 함` 과 같이 이름을 변경해보았습니다.

2024-05-06 03:11 UTC, chysis commented on components/package.json
> +    "dev": "vite --host",
칭찬 감사합니다 하루😺

2024-05-06 04:21 UTC, chysis commented on hooks/package.json
>    "types": "dist/index.d.ts",
package.json의 types 속성을 통해 라이브러리 사용자에게 인터페이스 등 필요한 타입 정보를 모두 제공할 수 있는 것으로 이해했습니다.

![image](https://github.com/woowacourse/react-modules/assets/64690761/9dd20b74-f6fb-4add-92d9-b3d091999eda)

현재 지정되어 있는 `index.d.ts`에는 default export 구문만 들어있는데요,

각 커스텀 훅의 인터페이스 정보가 들어있는 `use~~.d.ts` 파일들을 `types`로 지정하는 것을 의도하신 게 맞는지 궁금합니다! 조금 더 힌트를 듣고 싶어요 :)

2024-05-06 04:33 UTC, chysis commented on components/src/lib/Modal.tsx
> +            <h1
### 질문
모달창의 "카드사 선택"이나 "약관에 동의해주세요" 등은 본래 페이지와 독립적이라고 생각합니다. 그리고 그 자체만으로 중요한 기능을 수행하기 때문에 h1 태그로 볼 수 있다고 생각해요.

하루의 생각은 어떤지 궁금합니다! 또 고려해야 할 부분이 있을까요?

2024-05-06 06:18 UTC, chysis commented on components/src/stories/ModalCenter.stories.ts
> +import '../index.css';
`.storybook` 폴더의 `preview.ts`에서 `index.css`를 import하도록 설정했습니다!

2024-05-06 06:23 UTC, chysis commented on components/src/stories/ModalCenter.stories.ts
> +  tags: ['autodocs'],
docs 화면이 제대로 보이지 않는 현상은 `decorators`속성을 지정해서 해결할 수 있었습니다!
힌트 감사드려요 ㅎㅎ

2024-05-06 06:24 UTC, chysis commented on components/src/stories/ModalCenter.stories.ts
> +  tags: ['autodocs'],
> 또 요구사항이 확장되어서, 모달의 크기(width, height)또는 최소 높이(min-height) 등을 구체적으로 지정할 수 있어야하면 어떻게 대응하면 좋을까요?

이 부분도 고민했던 내용 중 하나인데요, 모달의 크기를 직접 설정할 수 있게 하는 편이 훨씬 유연한 컴포넌트가 될 수 있을 것 같습니다!
`modalSize`라는 객체로, width, height, minWidth, minHeight를 선택적으로 받을 수 있게 수정했습니다.

2024-05-06 06:26 UTC, chysis commented on components/src/stories/ModalCenter.stories.ts
> +const meta = {
Button 컴포넌트를 사용해서 모달을 열 수 있도록 수정했습니다 :)
그리고 backdrop을 클릭하거나 closeButton을 클릭하면 모달이 닫힙니다!

2024-05-06 07:09 UTC, chysis commented
안녕하세요 하루! 휴일 잘 보내고 계신가요?

피드백 반영을 마치고 돌아왔습니다! 꼼꼼한 피드백 감사드려요😊

## **🌐**배포 주소

[모달 바로가기](https://www.npmjs.com/package/fe-custom-modal)

[모달 스토리북 바로가기](https://6631dad3ab74b00107d09938-bxngtmrfjj.chromatic.com/)

[유효성 검사 훅 바로가기](https://www.npmjs.com/package/fe-card-validation-hooks)

## 🔧수정 사항

### 모달 컴포넌트의 구조화

![image](https://github.com/woowacourse/react-modules/assets/64690761/11063577-8643-4842-83ac-61f8d68765f0)


- 모달을 `ModalHeader`, `ModalContent`, `ModalFooter` 세 부분으로 나누었습니다.
- cancelButton, confirmButton 등을 리액트 컴포넌트로 분리했습니다.

### 더 유연해진 모달 컴포넌트

- 사용자가 모달창의 크기(width, height, minWidth, minHeight)를 직접 지정할 수 있습니다.
- 사용자가 취소 버튼과 확인 버튼의 배치 방향을 선택할 수 있습니다.

### README 보완

- 모달 컴포넌트에서 optional parameter임을 `(optional)`로 명시했습니다.
- 모달과 훅 README에 모두 npm 설치 방법을 첨부했습니다.

### 기타 수정사항

- 코드의 가독성 향상을 위한 리팩토링
- 테스트 이름이 테스트하는 값을 모두 포함하도록 변경
- 훅에서 반환하는 변수명 변경(errorMessage -> errorMessages)

## ⁉️고민한 내용

- 스토리북 사용은 아직 어려운 것 같습니다😅 힌트를 주셔서 docs에서 미리보기 화면이 나오지 않는 문제를 해결했어요.

## ❓질문

- 남겨주신 코멘트에 추가 질문들 남겨두었습니다!

2024-05-06 07:23 UTC, 365kim commented on components/src/lib/Modal.tsx
> +              style={{ fontSize: title.fontSize || '18px', color: title.color || 'black' }}
에고 제가 연달아 리뷰하면서 이름을 질못 썼었네요 정말 죄송합니다 😭

2024-05-06 07:34 UTC, 365kim commented on components/package.json
> +  "name": "fe-custom-modal",
오우 이름 깐지나네용 😎

2024-05-06 07:51 UTC, 365kim commented on hooks/package.json
>    "types": "dist/index.d.ts",
앗 제가 설명이 너무 부족했네요 죄송합니다...! 저는 아래의 의도로 질문드려본 것이었고, 잘 살펴봐 주신 것 같습니다.

- 현재 라이브러리에서 제공하는 타입이 어떤 것이 있는지,
- 실제 라이브러리 사용자가 어떤 타입 필요로할지도 함께 살펴보기

예를 들어, 에프이가 제공하는 `fe-custom-modal`라이브러리의 경우, 에디터에서 'Add missing attributes' 로 자동완성을 시켰을 때, Modal.d.ts에서 필요한 타입정보를 확인할 수 있었어요 👍

https://github.com/woowacourse/react-modules/assets/60066472/0329e6c3-ca2d-40a0-bff3-fb0907b604b7

`fe-card-validation-hooks`에서 만약 `CardType`을 사용하고 싶은 경우에는 다음과 같이 사용해야겠지요. (혹은 CardType 또한 export해서 타입정보를 제공할 수도 있겠고요.)

<img width="834" alt="image" src="https://github.com/woowacourse/react-modules/assets/60066472/4506dab1-4269-4978-a46d-900b774f6ee7">

2024-05-06 08:00 UTC, 365kim commented on components/src/lib/Modal.tsx
> +          {confirmButton && <ConfirmButton {...confirmButton} />}
👍

2024-05-06 08:03 UTC, 365kim commented on components/README.md
> +- font-size? `default: 18px`
👏👏👏👏👏

| modal | components |
| --- | --- |
|  <img width="598" alt="image" src="https://github.com/woowacourse/react-modules/assets/60066472/7847604c-c0da-4c12-a2cd-9cf5430ca517"> | <img width="595" alt="image" src="https://github.com/woowacourse/react-modules/assets/60066472/c2d9aa75-2899-46db-b0b7-d61955000dbb"> |

2024-05-06 08:04 UTC, 365kim commented on hooks/src/lib/useCardTypeValidation.ts
> +}
> 다른 컴포넌트들과의 구조적 통일성을 지키기 위함입니다

아하, `ValidationResult`는 항상 객체로 반환한다는 것이군요 이해했습니다.

2024-05-06 08:12 UTC, 365kim commented on components/src/stories/ModalCenter.stories.ts
> +const meta = {
오 잘되네요 👍

https://github.com/woowacourse/react-modules/assets/60066472/70027c33-29af-472f-a0a2-e8b657806c33

2024-05-06 08:21 UTC, 365kim commented on components/src/lib/Modal.tsx
> +            <h1
> 모달창의 "카드사 선택"이나 "약관에 동의해주세요" 등은 본래 페이지와 독립적이라고 생각합니다. 

아하 음, 모달 컴포넌트의 모달리티(모달 외의 요소와는 인터랙션 할 수 없음)로 인해 '독립적'인 성격이 분명히 있어보입니다. 

그러나 **문서 구조**상 '독립적'이라고 할 수 있을지(상위 맥락인 '카드 등록'을 벗어나서 이 모달의 의미를 얘기할 수 있을지) 잘 모르겠습니다.

저는 `앱 > 카드 등록 > 폼 작성하기 > 카드사 선택` 이런 식의 **문서 구조** 하에, 해당 문서의 가장 메인이 되는 내용은 "카드 등록(h1)"이고, "카드사 선택"은 이를 보조하는 형태로 보입니다. 

또 만일 h1으로 작성한다면, 모달이 렌더링 된 순간 기존 페이지를 숨겨버리지 않는 한 그 순간 h1 태그는 여러 개가 될 것입니다. 다중 모달을 사용하는 경우에도 h1은 여러 개가 되겠지요. 이런 점도 같이 고려해주시면 좋을 것 같습니다 :)

2024-05-06 08:29 UTC, 365kim commented on components/src/stories/ModalBottom.stories.ts
> +    cancelButton: { content: '취소', onCancel: () => {} },
아하 그런 고민이 있으셨군요.

아래처럼 모달 컴포넌트를 구조화해서 작업해주신 방향 너무 좋습니다. 👍

<img width="826" alt="image" src="https://github.com/woowacourse/react-modules/assets/60066472/b955b775-3927-433c-a897-858e6c08cc5a">

<br />
<br />
<br />
<br />

이미 ModalProps에서 관리하는 prop이 많지만, 
앞으로 Modal 컴포넌트는 다양한 요구사항을 충족하기 위해 prop이 추가될 것으로 보여요. 

그 때는 모든 props를 Modal에서 `ModalProps` 관리하기보다, 각 하위 컴포넌트가 해당 prop을 관리하도록(e.g. `ModalHeaderProps`, ...) 관심사를 분리하는 방법도 추천드려봅니다 :)

```tsx
interface ModalProps {
  modalSize?: ModalSizeProps;
  backgroundColor?: string;
  borderRadius?: string;
  modalPosition: 'center' | 'bottom';
  preventCloseOnOutsideClick?: boolean;

  title?: TitleProps; // -> 모달헤더
  subtitle?: SubtitleProps; // -> 모달헤더
  closeButton: CloseButtonProps; // -> 모달헤더

  children: React.ReactNode;  // -> 모달컨텐트

  confirmButton?: ConfirmButtonProps;  // -> 모달푸터
  cancelButton?: CancelButtonProps;  // -> 모달푸터
  buttonsDirection?: 'row' | 'column';  // -> 모달푸터
}
```

2024-05-06 08:32 UTC, 365kim commented on components/src/lib/CancelButton.tsx
> +        backgroundColor: `${props.backgroundColor || 'lightgrey'}`,
<img width="974" alt="image" src="https://github.com/woowacourse/react-modules/assets/60066472/e90a4b41-8dde-4ac5-b462-35af95f06c98">

사소한데, 현재의 `CancelButton` 스타일은 '취소' 보다는 '비활성화' 스타일에 가까워보입니다.
`CancelButton` 의 기본 스타일을 피그마 시안에 맞춰도 좋을 것 같습니다 :)



<img width="415" alt="image" src="https://github.com/woowacourse/react-modules/assets/60066472/143d84c0-84f5-4dc4-8bd1-f6c26f3f522f">

2024-05-06 08:38 UTC, 365kim commented on components/src/stories/ModalCenter.stories.ts
> +const meta = {
마지막으로 아래 두 가지 스타일 확인 부탁드려도 될까요 🙏🏻

|  1️⃣ 'Click to open modal'버튼은 Dimmed에 덮이지 않고 있음 |  2️⃣ buttonsDirection="column"일 때 버튼 너비 |
| --- | --- |
| <img width="647" alt="image" src="https://github.com/woowacourse/react-modules/assets/60066472/f7a728cb-5802-494c-aa05-7e5b313dec66"> | <img width="523" alt="Screenshot 2024-05-06 at 5 35 14 PM" src="https://github.com/woowacourse/react-modules/assets/60066472/9237e9e7-e905-413b-b1d1-0cf6221c2b77"> |

2024-05-06 08:43 UTC, 365kim requested changes
미스터 프론트엔드, 빠르게 리뷰 반영해주셔서 감사합니다 😄

제가 드린 피드백 능동적이고 주도적으로 반영해주시는 모습 너무 멋집니다 😎

이미 충분히 Approve해도 될 것 같지만서도, 
다음 단계로 넘어가기전에 모달 패키지 관련 이 [피드백](https://github.com/woowacourse/react-modules/pull/28#discussion_r1590705095) 딱 하나만 더 반영해보면 좋을 것 같아, 마지막으로 반영 요청드려보아요 🙌

2024-05-06 08:52 UTC, chysis commented on components/src/index.css
>  }
저도 지금 사용하는 `reset.css` 파일에서 변동 가능성이 있는 스타일은 제외하고 기본적인 스타일만 남겨둬야겠네요! 감사합니다 :)

2024-05-06 12:08 UTC, chysis commented on components/package.json
> +  "name": "fe-custom-modal",
프론트엔드 커스텀 모달이라는 착각을 줍니다🤣

2024-05-06 14:07 UTC, chysis commented on components/src/lib/Modal.tsx
> +            <h1
이해했습니다! 단순히 독립적으로 동작한다고 문서 구조까지 독립적으로 볼 수는 없겠네요.

>  저는 앱 > 카드 등록 > 폼 작성하기 > 카드사 선택 이런 식의 문서 구조 하에, 해당 문서의 가장 메인이 되는 내용은 "카드 등록(h1)"이고, "카드사 선택"은 이를 보조하는 형태로 보입니다.

부분에 동의합니다!

![image](https://github.com/woowacourse/react-modules/assets/64690761/13314175-cad9-4ddf-b89a-9a4ed6d42669)

신한카드의 카드사용등록 페이지를 찾아보았는데요, 말씀하신 것처럼 `카드사용등록` 문구가 h1이고, 하위의 input을 눌렀을 때 모달창에서 선택이 이루어지게 된다면 그것은 h1로 볼 수 없을 것 같습니다.

### 질문
`폼 작성하기`와 같은 depth에 헤딩 태그가 들어갈 것을 고려해서 `h3` 태그로 모달 title을 구성한다면 적절할지 궁금합니다 :)
헤딩 태그를 사용할 때는 문서 구조를 먼저 확인해봐야겠네요.

2024-05-06 14:41 UTC, chysis commented on components/src/lib/CancelButton.tsx
> +        backgroundColor: `${props.backgroundColor || 'lightgrey'}`,
### 질문
처음엔 피그마 시안대로 따라가려 했으나 모달 배경색과 같아서 어디까지가 버튼인지 모호하다는 느낌을 받았습니다. 구별을 위해 넣은 색인데, 비활성화 스타일과 비슷한 느낌이긴 하네요😅

![image](https://github.com/woowacourse/react-modules/assets/64690761/d07e1288-adf1-4f82-a2ee-dcae1b36c111)
기존 색상

![image](https://github.com/woowacourse/react-modules/assets/64690761/29150744-025c-48a6-b0de-c7f453dfcb62)
▲ backgroundColor: inherit

![image](https://github.com/woowacourse/react-modules/assets/64690761/99340f1f-0d42-43d3-8d44-67ae5b8e9f19)
▲ backgroundColor: #eee (바꾼 결과)

기본 배경색과 완전히 일치하지는 않으면서 취소 느낌을 줄 수 있는 색상을 선택해보았습니다.
하루가 보시기엔 어떤지 궁금합니다 :)

2024-05-06 14:43 UTC, chysis commented on components/src/stories/ModalCenter.stories.ts
> +const meta = {
2번째 `buttonsDirection="column"`인 경우를 먼저 수정했습니다.
각 버튼의 width를 95%로 설정해서 row일 때와 column일 때 모두 원하는 스타일이 나오도록 설정했습니다.

![image](https://github.com/woowacourse/react-modules/assets/64690761/adc1c0a7-6808-46b4-8fcc-00ef9bedc1c8)

2024-05-06 14:59 UTC, chysis commented on components/src/stories/ModalCenter.stories.ts
> +const meta = {
`Click to open modal` 버튼이 dimmed 영역에 덮이도록 `Modal`의 스타일을 수정했습니다.

![image](https://github.com/woowacourse/react-modules/assets/64690761/756662bc-9f08-4738-af63-e481f68716ce)

2024-05-06 15:59 UTC, chysis commented
안녕하세요 하루! 피드백을 다시 빠르게 반영했습니다 :)

## **🌐**배포 주소

[모달 바로가기](https://www.npmjs.com/package/fe-custom-modal)

[모달 스토리북 바로가기](https://6631dad3ab74b00107d09938-nbspnffqkp.chromatic.com/)

[유효성 검사 훅 바로가기](https://www.npmjs.com/package/fe-card-validation-hooks)

## 🔧수정 사항

### 모달 취소 버튼과 확인 버튼 변화

- 배치 순서를 피그마 시안대로 변경했습니다.
- 피그마 시안에서 취소 버튼이 모달 배경 색상과 일치해서 그 경계가 모호합니다. 따라서 구분되면서 `비활성화` 느낌이 나지 않을 정도의 밝은 색상을 선택했습니다.

### 모달 title, subtitle 헤딩 태그 변경

- 기존에 모달 title이 `h1` 태그였다가, 문서 구조 상 h1가 적합하지 않다고 판단했습니다.
    - title은 `h3`, subtitle은 `h4` 태그를 사용했습니다.

### 유효성 검사 훅의 반환 타입 export

- 훅에서 반환하는 객체의 타입을 export해서 사용자에게 제공합니다.

## ❓질문

- 코멘트에 이어서 추가 질문을 남겼습니다! 감사합니다.

2024-05-06 16:04 UTC, 365kim commented on components/src/lib/CancelButton.tsx
> +        backgroundColor: `${props.backgroundColor || 'lightgrey'}`,
오우 적극적으로 반영해주셔서 감사합니다 :) 

개선해주신 지금도 충분한데 굳이굳이 의견을 보태보자면
취소 텍스트 컬러를 black으로 하거나, 혹은 filled가 아닌 outline 스타일로 작성하는 방법도 있을 것 같습니다 :)

2024-05-06 16:06 UTC, 365kim commented on components/src/lib/Modal.tsx
> +            <h1
> h3 태그로 모달 title을 구성한다면 적절할지

h2가 될지, h3가 될지는 (혹은 h5가 될지) 이 패키지를 사용하는 사용자의 문서 구조에 따라 충분히 달라질 수 있을 것 같습니다. 
이렇게 사용자가 '태그 자체'를 커스텀하려는 니즈를 커버하기 위해 `as` prop을 제공하는 방법도 있겠습니다 :)

2024-05-06 16:08 UTC, 365kim commented on components/src/lib/ModalHeader.tsx
> +      <span aria-label={'모달 닫기 버튼'} className={styles['button-close']} onClick={closeButton.onClose}>
혹시 버튼인데 `button` 태그가 아니라 `span` 태그를 사용해주신 이유가 있을까요?

`cursor: pointer` 스타일 적용을 제안드리러 왔다가 태그 보고 코멘트 남겨보아용

2024-05-06 16:17 UTC, 365kim commented on components/src/stories/ModalCenter.stories.ts
> +const meta = {
작업해주신 것 확인했습니다 빠르게 작업해주셔서 감사해요 ☺️

2024-05-06 16:19 UTC, 365kim commented on hooks/src/lib/index.ts
> +export type { CardType } from './useCardTypeValidation';
👍

2024-05-06 16:27 UTC, 365kim approved these changes
에프이, 초스피드로 피드백 반영해주셨군용 👍
변경내역 깔끔하게 정리해주신 덕분에 저도 빠르게 확인할 수 있었어요 감사합니다 :)

PR 제출 당시에도 이미 높았던 (사용자 인터페이스의 일관성, 가독성, UI 완성도 등등을 포함한) 라이브러리의 완성도가 더욱 좋아진 것 같아요. 피드백 반영 후에도 적극적으로 피드백 요청해주시는 모습에서 코드에 대한 오너십과 에프이의 적극성이 느껴져서 좋았습니다 ☺️

에프이의 2단계 작업도 매우 기대됩니다. 이어서 즐거운 대화 나누어보아요. 
1단계 고생하셨습니다 👏👏👏

2024-05-06 16:27 UTC, merged

2024-05-07 06:43 UTC, chysis commented on components/src/lib/CancelButton.tsx
> +        backgroundColor: `${props.backgroundColor || 'lightgrey'}`,
outline 스타일도 괜찮을 것 같습니다! 이 부분은 step2를 진행하면서 수정해보겠습니다 :)

2024-05-07 14:42 UTC, chysis commented on components/src/lib/ModalHeader.tsx
> +      <span aria-label={'모달 닫기 버튼'} className={styles['button-close']} onClick={closeButton.onClose}>
단순히 `svg` 태그를 감싸주기 위해 `span` 태그를 사용했습니다! button 태그를 사용하는 것이 의미 전달이 확실하겠네요.