a
woowacourse/react-modules pull request #43
Opened 2024-05-09 13:21 UTC by ss0526100

안녕하세요 호프!
다시 만나뵙게 되어 반갑습니다.

이번 미션에는 심화 미션이 있었는데요.

심화미션까지 진행하면 리뷰 요청시기가 너무 늦어질 것 같았습니다. 또, 심화 미션은 코드리뷰 대상이 아니라고합니다.
>>모듈 통합 및 연동 (심화 요구사항)
현재 단계에서 페이먼츠 스텝1~2를 진행한 저장소 내용은 코드 리뷰 대상이 아닙니다.
학습을 위해 독립적으로 만든 컴포넌트를 배포 및 적용해 보고 자신이 독립적으로 만든 모듈 저장소의 컴포넌트에 대해서 리뷰어에게 피드백을 요청합니다.

일단 우선적으로 필수 요구사항 먼저 구현 후 피드백을 받고 심화미션을 진행해보려고 합니다.

지난 미션에서 (호프의 조언 덕분에 ㅎㅎ) 컴파운드 컴포넌트로 리팩토링을 잘해놔서, 비교적 수월한 미션이었던 것 같습니다.

미션 수행 간 궁금한 사항을 코멘트에 달아놓겠습니다. 코드리뷰 시 참고하시면 좋을 것 같습니다.

그럼 이번에도 잘 부탁드려요!

2024-05-09 13:41 UTC, ss0526100 commented on hooks/src/lib/useCardNumber/getFormattedCardNumber.ts
> +    const lastNumber = acc[acc.length - 1] ?? 0;
이 부분에서는 `at(-1)'을 사용할 수 있었지만 현재 ts버전에서는 지원하지 않는 문법이라 지금처럼 `length-1`을 사용했습니다.

2024-05-09 13:41 UTC, ss0526100 commented on hooks/src/lib/useCardNumber/index.ts
> +    setCardNumber,
지난 리뷰 때 set을 내보내는 것에 대해 호프에게 질문을 드렸었는데요.
이에 대해 set을 내보내지 않는 것이 좋을 것 같다고 해주셨어요.

그런데 생각을 조금 더 해보니 set을 바깥으로 내보내는 이유가 있었습니다.

바로 onChange 시점에 유효성을 검증하는 것이 아니라, onBlur 시점에 유효성을 검증하고 사용자에게 에러메시지를 보여주려는 니즈가 있다는 점이었습니다.

그런데, 리뷰를 쓰는 도중에 생각해보니 그냥 사용자가 사용 단계에서 반환된 onChange를 요소의 onBlur에 넣어주면 되겠다는 생각이 드네요...ㅋㅋ

이 부분은 추후에 수정하겠습니다!

2024-05-09 13:41 UTC, ss0526100 commented on hooks/src/lib/useCardNumber/index.ts
> +      const cardBrand = getCardBrand(cardNumber);
cardBrand를 알아내는 로직은 꽤나 비용이 드는 함수라고 생각이 듭니다.

그런데 가독성과 유효성 검증의 책임 분리를 높이기 위해 카드 브랜드를 확인하는 과정을 추가로 반복 시켰는데요.

이 부분을 위의 부분과 합치는 것이 좋을수도 있겠다는 생각이 듭니다.

이에 대한 호프의 생각이 궁금합니다!

2024-05-09 13:41 UTC, ss0526100 commented on hooks/src/lib/useCardNumber/getCardBrand.ts
> +    return checkIsInRangeString(
사실 여기서 사용된 checkIsRangeString은 저의 잘못된 판단으로 만들어진 유틸 함수입니다.

기존 cardNumber의 값을 잘라서 범위 안에 값이 있는지 확인할 것이였으면, 다음과 같이 구현했어도 괜찮았을 것이라는 생각이 드는데요.

```js
const targetNumber =Number(cardNumber.slice(sliceNumber));

return Number(startWith.from)<=targetNumber&&targetNumber<=Number(startWith.to)
```

그냥 지우기에는 너무 많은 공을 들여서 지우지 않고 그냥 사용해 버렸습니다..
뭔가 이대로 사용해도 가독성 측면에서는 위의 방식보다는 좋지 않지만 크게 나쁘지 않다는 생각도 들었고요.


호프도 저처럼 열심히 만든 놓은 코드가 다른 쉬운 코드로 대체되신 경험이 있으셨을까요?

있으셨다면 다른 쉬운 코드로 대체하셨나요? 아니면 그대로 놔두셨나요?

2024-05-09 13:41 UTC, ss0526100 commented on components/src/lib/CompoundModal/CompoundModalButton.tsx
> +const getOnClick = ({
이 함수의 사용처에서 onClick에 관련된 요소들만 따로 분리해 인자로 넣어주는 방식도 있었지만, props를 그냥 넣어주는 방식을 사용했습니다.

많은 함수를 추가할 일이 있을때는 용이하겠다는 생각이 들었지만, 쓸데없는 인자(ex:buttonTheme)를 넘겨줘서 안정적이지 못하다는 생각이 들었는데요

이에 대한 호프의 생각이 궁금합니다.

2024-05-10 16:09 UTC, moonheekim0118 requested changes
안녕하세요 소파! 리뷰가 늦어서 죄송합니다 🙏 🙏  양해해주셔서 정말 감사해요 :)
이번 단계도 구현해주시느라 정말 고생 많으셨어요. 확실히 전단계에서 잘 개선해놔주셔서 전반적으로 코드가 깔끔하다는 인상을 받았습니다 😄

코멘트 남긴거 확인해주시고, 재리뷰요청 주세요 :) 고생많으셨어요 💪  

(+ 혹시 스토리북 배포 되었을까요? 이전 스텝의 주소로 들어가니 업데이트가 되지 않은 것 같아서요! 확인 부탁드릴게요!)

2024-05-10 16:09 UTC, moonheekim0118 commented on components/src/lib/CompoundModal/CompoundModalButton.tsx
>    return {
그런데 리뷰하면서 확인하니, 아래의 ButtonContainer 에서는 룩업테이블에 설정별로 스타일을 잘 관리해주셨더라고요ㅎㅎ
전체적으로 하나의 방식으로 통일되면 좋을 것 같아요 :)

2024-05-10 16:09 UTC, moonheekim0118 commented on hooks/src/lib/useCardNumber/getFormattedCardNumber.ts
> +};
reduce 내부에서 배열에 push 하고 있는데, map 메서드로 리팩터링 해볼 수 없을까요 ?

2024-05-11 21:20 UTC, ss0526100 commented
안녕하세요 호프 우선 스토리북 제대로 배포를 못했던 점 죄송하다고 전해드립니다... 잘 확인하겠습니다

## 스토리북 배포링크 (https://663348d18a373e4814b557bf-dqetjokszq.chromatic.com/?path=/story/modal--alert-modal-story&args=children:none)

리뷰 반영이 늦었네요... 기다리게 해드려서 죄송합니다.

궁금한 점 코멘트로 남겨놓겠습니다. 그럼 잘부탁드립니다!

2024-05-11 21:46 UTC, ss0526100 commented on components/src/lib/constants/colorHexes.ts
> +  grayTransParent2: '#333333bf',
이런 방식으로 색상값을 관리하는 경우도 있었네요! 하나 또 알아가요.

그러면 추가적으로 궁금한 사항이 있는데요.

제가 transParent로 명명한 상수들은 투명도까지 반영을 한 8자리 색상값이에요. 이렇게 투명도를 구분지을 때에도 별도의 이름이 붙는 경우가 있을까요?

찾아봤는데 잘 안나오는 것 같아 질문드립니다..ㅜ

2024-05-11 21:46 UTC, ss0526100 commented on hooks/src/lib/useCardNumber/getCardNumberValidator.ts
> +        return cardBrand?.numberLength === cardNumber.length;
지난 번에 질문드렸던 부분인데요. 제가 코드를 잘못짜고 질문을 드렸더라구요 ㅠㅠ

35번째 줄의 validator는 브랜드가 있는지를 검중하는 단계였고,

코멘트가 달린 이 줄의 validator는 브랜드에 해당하는 카드 번호 길이와 같은지 검증하는 로직이었습니다.

이 브랜드 확인과 번호 길이 확인 로직을 합쳐도 될까에 대해 궁금했습니다..!

2024-05-11 21:46 UTC, ss0526100 commented on hooks/src/lib/useCardNumber/index.ts
> +  const cardNumberValidators = useMemo(
리뷰 반영을 진행하면서 가장 궁금하다고 많이 들었던 곳이 바로 useCallback과 useMemo를 사용하는 부분이었습니다.

이와 관련된 궁금증은 리액트 공식문서를 찾아보며 어느정도 해결이 된 듯 합니다.

그럼에도 불구하고 eslint에서 나오는 문구들들이 이해가 안되는 경우가 있었습니다.

![image](https://github.com/woowacourse/react-modules/assets/75566149/50b8465c-a657-43de-85c8-7db4056bdf0a)
왜 targetBrandName이 그대로 의존성 배열에 들어갔음에도 불구하고 eslint가 작동하는 것인지 이해가 되지 않습니다.

만약 의존성 배열이 `[targetBrandNames]`가 된다면 `targetBrandNames`의 내부 값들이 변경되더라도 배열의 참조값이 변하지 않는 경우가 있어 유의미한 동작이 이뤄지지 않을 수 있다고 생각이 드는데요.

왜 이런 부분을 eslint가 잡아주는 지 궁금합니다.

2024-05-12 14:35 UTC, moonheekim0118 commented on components/src/lib/constants/colorHexes.ts
> +  grayTransParent2: '#333333bf',
저도 따로 투명도까지 반영된 색상을 구분짓는 경우는 아직 보진 못했는데요,
현재 해주신 것 처럼 `TRASNPARENT`와 같은 단어를 뒤에 붙여주셔도 충분할 것 같아요!

2024-05-12 15:03 UTC, moonheekim0118 requested changes
안녕하세요 소파! 반영해주신 사항 확인했습니다~ 전반적으로 잘 반영해주셨고, 남겨주신 질문에 대해서 답변 남겨놓았어요. 해당 답변만 확인해주시면 바로 어프루브 하러 올게요~!

그럼 고생하셨습니다 :)

2024-05-12 15:03 UTC, moonheekim0118 commented on components/src/stories/ConfirmModal.stories.tsx
> +      mapping: { exist: MODAL_CHILDREN_MESSAGE, none: undefined },
실제로 스토리북 사용해보면서 느낀 점은,
요렇게 exist / none 처럼 on and off 와 같은 역할을 하는 스토리 컨트롤은 radio 보다는 boolean 컨트롤로 관리하면 편할 것 같으네용ㅎㅎ

2024-05-12 17:34 UTC, ss0526100 commented
호프! 말씀해주신 부분 수정했습니다.

이번 리뷰가 우테코에서 받을 수 있는 마지막 리뷰였었겠네요.

그동안 감사드렸습니다. 건강하세요!

2024-05-13 00:33 UTC, moonheekim0118 approved these changes
소파~ 빠르게 반영해주셔서 감사해요 :) 이번 미션은 여기서 마무리해도 될 것 같습니다. 👍 
이번 미션 동안 좋은 이야기 함께 많이 나누어주셨어서 감사했습니다. 저도 덕분에 즐겁게 리뷰했어요.

소파도 건강하시고 앞으로 남은 우테코 생활도 응원할게요 🙂 🍀

2024-05-13 00:33 UTC, merged