[2단계 - 페이먼츠 모듈] 수야(최영수) 미션 제출합니다.
woowacourse/react-modules pull request #52
Opened 2024-05-10 10:08 UTC by cys4585

안녕하세요 브콜! 2단계 PR로 다시 인사 드립니다~
이번 미션은 기존의 코드베이스를 바탕으로 요구사항이 변경되었을 때, 유연하게 확장하기 위해 리팩터링 하는 시나리오로 진행을 했어요.

# 테스트

# 집중한 부분

미션 요구사항에 따라 Modal 컴포넌트와, useCardNumber 훅에  집중했어요. 수정 과정에서 다른 기능들에 영향이 있을 수 있지만, 시간이 짧았다는 점을 감안해서 너그러이 봐주시면 감사하겠습니다...! `Modal 컴포넌트와 useCardNumber 훅에 집중해주시면 감사하겠습니다!`

## Modal 컴포넌트

모듈화된 모달 컴포넌트를 확장하는 데 집중했어요. 확장 목표는 '다양한 크기와 타입을 지원'하는 모달을 제공하는 것이었어요. 
- 크기 옵션
    - small, medium, large
- 타입 옵션
    - alert, confirm, prompt

이 과정에서 크게 두 개의 문제를 마주했어요. 첫 번째는 크기(size) 옵션 기능을 개발할 때였어요. 기존 Modal이 center와 bottom이라는 position 옵션을 제공했었는데, 이 옵션과 size 옵션이 충돌하는 문제가 있었어요. 
- position가 center일 때 → size가 small | medium | large 문제 없음
- position가 bottom일 때 → size가 100%로 고정돼야 하는지, small | medium | large를 줘야 하는지

고민 후 position이 bottom일 때는 size를 100%로 고정하기로 했어요. 그 결정의 이유는, position이 bottom인 Modal은 모바일 환경일 것이고, 모바일 환경에서 Modal이 아래에 뜰 때 크기가 100%가 되어 화면을 꽉 채우는 게 자연스럽다고 판단했어요.
이 부분에서 추가적인 고민이 하나 있었는데, `position이 bottom일 때 size를 설정할 수 없도록 사용처에 알려줄 방법이 없을까?` 였어요. union type으로 position과 size의 케이스를 조합해서 정의하는 방법이 떠오르긴 했는데, 혹시 적절한 다른 방법이 없을지 궁금합니다!

두 번째 마주한 문제는 Modal 컴포넌트에 대한 요구사항이 늘어남에 따라 Modal 컴포넌트가 복잡해지는 것이었어요. 위치, 크기, 타입에 대한 요구사항을 다 만족하는 Modal을 만들어야 하는데, 이것들이 한 곳에 모이니까 생각이 너무 복잡해졌어요. 
그래서 Modal 컴포넌트의 관심사를 분리하기 위해 Modal 컴포넌트의 구조를 Compound Component로 바꿔봤어요. Modal의 최상위 컴포넌트는 모달의 위치와 크기와 같은 전체적인 부분만을 담당하고, Modal 내부의 요소를 각각 Header, Content, Footer 컴포넌트로 구성하여 각 섹션을 별도의 관심사로 분리했어요. 이렇게 구조를 바꾸고 나니, 제 머릿속의 생각이 같이 정리가 돼서 유용함을 느꼈답니다!

## useCardNumber 훅

카드번호와 관련된 입력과 유효성 검사를 담당하는 useCardNumber를 확장하는 데 집중했어요. 확장 목표는 카드사(CardGlobalBrand) 지원이 확장됨에 따라, User가 입력한 카드번호를 바탕으로 실시간으로 카드사를 식별하고, 식별한 카드사를 기준으로 유효성 검사와 카드번호 포맷팅을 달리해줄 수 있는 useCardNumber 훅을 제공하는 것이었어요.
- 카드번호 입력 → 카드사(GlobalBrand) 식별 → 포맷팅, 유효성 검사
    - 4로 시작 → Visa → [4, 4, 4, 4], 16자리
    - 51 ~ 55로 시작 → Master → [4, 4, 4, 4], 16자리
    - 36으로 시작 → Diners → [4, 6, 4], 14자리
    - 34, 37로 시작 → AMEX → [4, 6 ,5], 15자리
    - 622126 ~ 622925 / 624 ~ 626 / 6282 ~ 6288로 시작 →  UnionPay → [4, 4, 4, 4], 16자리

useCardNumber 훅 개발할 때 가장 집중했던 부분은, 1단계 미션에서 브콜이 말씀해주신 '유효성 검사 실패 시 errorType을 알려주는 것'이었어요. ValidationResult의 구조를 `{isValid:true} | [isValid:false; errorType, errorMessage}` 로 변경했어요. errorType은 enum으로 관리하고 있습니다! 추가로, validaiton을 할 때 true, false를 반환하는 것이 아니라, ValidationError를 커스터마이징하여 이 Error를 throw하도록 했어요. 이로 인해 handler 로직을 보다 깔끔하게 관리할 수 있게 됐습니다! 이 부분에 대해서 잘한 점이나, 개선 포인트를 말씀해주시면 좋을 것 같아요!

useCardNumber 개발 과정에 고민 포인트가 하나 더 있었어요! 상태 관리에 관한 내용인데요. cardGlobalBrand(카드사), validCardNumberLength(카드사의 유효한 카드번호 길이)를 [ 상태로 관리하는 것 vs 평범한 변수로 관리하는 것 ] 이 고민 포인트였습니다! 자세한 내용은 코멘트로 따로 남기겠습니다.

2024-05-10 10:45 UTC, cys4585 commented on hooks/src/lib/useCardNumbers/useCardNumbers.ts
> +        calculateValidCardNumberLength(cardGlobalBrand);
cardGlobalBrand(카드사), validCardNumberLength(카드사의 유효한 카드번호 길이)를 [ 상태로 관리하는 것 vs 평범한 변수로 관리하는 것 ] 이 고민 포인트였습니다!

변수로 관리하게 되면, 아래와 같이 반환을 위해 추가적인 재계산 작업이 필요했어요.
```typescript
const { cardGlobalBrand, validCardNumberLength, formattedCardNumber } =
    useMemo(() => {
      const cardGlobalBrand = identifyCardGlobalBrand(cardNumber);
      const validCardNumberLength =
        calculateValidCardNumberLength(cardGlobalBrand);
      const formattedCardNumber = formatCardNumber(cardNumber, cardGlobalBrand);
      return { cardGlobalBrand, validCardNumberLength, formattedCardNumber };
    }, [cardNumber]);
```

2024-05-10 10:47 UTC, cys4585 commented on hooks/src/lib/useCardNumbers/useCardNumbers.ts
> +        calculateValidCardNumberLength(cardGlobalBrand);
cardGlobalBrand(카드사), validCardNumberLength(카드사의 유효한 카드번호 길이)를 [ 상태로 관리하는 것 vs 평범한 변수로 관리하는 것 ] 이 고민 포인트였습니다!

변수로 관리하게 되면, 아래와 같이 반환을 위해 추가적인 재계산 작업이 필요했어요.

const { cardGlobalBrand, validCardNumberLength, formattedCardNumber } =
    useMemo(() => {
      const cardGlobalBrand = identifyCardGlobalBrand(cardNumber);
      const validCardNumberLength =
        calculateValidCardNumberLength(cardGlobalBrand);
      const formattedCardNumber = formatCardNumber(cardNumber, cardGlobalBrand);
      return { cardGlobalBrand, validCardNumberLength, formattedCardNumber };
    }, [cardNumber]);

2024-05-10 10:54 UTC, cys4585 commented on hooks/src/lib/types/ValidationResult.ts
>  export default ValidationResult;
useCardNumber 훅 개발할 때 가장 집중했던 부분은, 1단계 미션에서 브콜이 말씀해주신 '유효성 검사 실패 시 errorType을 알려주는 것'이었어요. ValidationResult의 구조를 {isValid:true} | [isValid:false; errorType, errorMessage} 로 변경했어요. errorType은 enum으로 관리하고 있습니다! 추가로, validaiton을 할 때 true, false를 반환하는 것이 아니라, ValidationError를 커스터마이징하여 이 Error를 throw하도록 했어요. 이로 인해 handler 로직을 보다 깔끔하게 관리할 수 있게 됐습니다! 이 부분에 대해서 잘한 점이나, 개선 포인트를 말씀해주시면 좋을 것 같아요!

2024-05-10 10:58 UTC, cys4585 commented on components/src/lib/Modal/Modal.tsx
>  }
이 부분에서 추가적인 고민이 하나 있었는데, `position이 bottom일 때 size를 설정할 수 없도록 사용처에 알려줄 방법이 없을까?` 였어요. union type으로 position과 size의 케이스를 조합해서 정의하는 방법이 떠오르긴 했는데, 혹시 적절한 다른 방법이 없을지 궁금합니다!

2024-05-10 11:01 UTC, cys4585 commented
Modal 컴포넌트의 관심사를 분리하기 위해 Modal 컴포넌트의 구조를 Compound Component로 바꿔봤어요. Modal의 최상위 컴포넌트는 모달의 위치와 크기와 같은 전체적인 부분만을 담당하고, Modal 내부의 요소를 각각 Header, Content, Footer 컴포넌트로 구성하여 각 섹션을 별도의 관심사로 분리했어요. 이렇게 구조를 바꾸고 나니, 제 머릿속의 생각이 같이 정리가 돼서 유용함을 느꼈답니다!

이 부분에 대해서 추가적인 개선포인트가 있다면 알려주시면 감사하겠습니다!

2024-05-11 18:15 UTC, Tanney-102 requested changes
안녕하세요 수야!
step2 진행하시느라 고생많으셨습니다.
전반적으로 잘 정리된 코드라는 느낌을 받았네요 👍 
남겨주신 고민점들 바탕으로 조금 더 생각해보실만한 코멘트 남겼으니 확인 부탁드립니다!

2024-05-11 18:15 UTC, Tanney-102 commented on hooks/src/lib/useCardNumbers/useCardNumbers.ts
> +        calculateValidCardNumberLength(cardGlobalBrand);
cardGlobalBrand(와 등등..)는 cardNumber에 의존적인 상태이기 때문에 (수야 표현으로) 변수로 관리되는 게 더 나아보여요.
cardNumber를 update하는 시점에 해당 상태가 재계산 되어야 하는 건 어떤 방식이든 자명해보입니다.(불필요한 중복 함수 호출은 잘 이해하지 못했어요)
재계산이야 어차피 일어나야하는 일이고..
`cardNumber가 변경되면 => 메뉴얼하게 setCardGlobalBrand` 보다는 `cardNumber가 업데이트 되는 콜스텍에서 
 자연스럽게 cardGlobalBrand 결정`이 더 나아보입니다. 코드 표현에 있어 뉘앙스 차이도 있지만 cardGlobalBrand를 useState로 선언하는 순간 cardNumber와 독립적으로 업데이트 될 수 있는 여지가 생겨 별로 좋아보이지는 않아요

2024-05-11 18:15 UTC, Tanney-102 commented on hooks/src/lib/useCardNumbers/useCardNumbers.ts
> +      validateAfterUpdate(cardNumber, validCardNumberLength);
다른 validation 함수들은 boolean을 반환하는 것 같던데 이 친구만 error를 throw하는 이유가 궁금해요.
추가로 error를 throw하는 방식과 결과값을 반환하는 방식간 어떤 차이가 있을지도 생각해보시면 좋겠네요!

2024-05-11 18:15 UTC, Tanney-102 commented on hooks/src/lib/useCardNumbers/utils/identifyCardGLobalBrand.test.ts
테스트를 잘 챙겨주시는 게 좋네요 👍

2024-05-12 06:54 UTC, cys4585 commented on hooks/src/lib/useCardNumbers/useCardNumbers.ts
> +        calculateValidCardNumberLength(cardGlobalBrand);
오... 확실히 이해됐습니다! 어느 상태에 의존적인 데이터여야 하는데, 별도로 useState로 선언하면 독립적으로 업데이트될 여지가 있네요... 

> (불필요한 중복 함수 호출은 잘 이해하지 못했어요)

이 부분은 설명이 조금 부족했던 것 같습니다..ㅜ

1. useState로 관리 -> `identifyCardGlobalBrand`, `calculateValidCardNumberLength` 함수를 한 번만 호출해도 됨
```typescript
export default function useCardNumber(
  initialValues: string = ""
): CardNumberValidationResult {
  const [cardNumber, setCardNumber] = useState(initialValues);

  const [validationResult, setValidationResult] = useState<ValidationResult>();

  const { cardGlobalBrand, validCardNumberLength, formattedCardNumber } =
    useMemo(() => {
      const cardGlobalBrand = identifyCardGlobalBrand(cardNumber);
      const validCardNumberLength =
        calculateValidCardNumberLength(cardGlobalBrand);
      const formattedCardNumber = formatCardNumber(cardNumber, cardGlobalBrand);

      return { cardGlobalBrand, validCardNumberLength, formattedCardNumber };
    }, [cardNumber]);

  const handleUpdateCardNumber = (cardNumber: string) => {
    try {
      const cardGlobalBrand = identifyCardGlobalBrand(cardNumber);
      const validCardNumberLength =
        calculateValidCardNumberLength(cardGlobalBrand);

      validateBeforeUpdate(cardNumber, validCardNumberLength);

      setCardNumber(cardNumber);

      setValidationResult({ isValid: true });

      validateAfterUpdate(cardNumber, validCardNumberLength);
    } catch (error) {
      if (error instanceof ValidationError) {
        setValidationResult({
          isValid: false,
          errorType: error.errorType,
          errorMessage: error.errorMessage,
        });
      }
    }
  };
```

2. 변수로 관리(memoization) -> `identifyCardGlobalBrand`, `calculateValidCardNumberLength` 함수를 두 번 호출해야 함
```typescript
export default function useCardNumber(
  initialValues: string = ""
): CardNumberValidationResult {
  const [cardNumber, setCardNumber] = useState(initialValues);

  const [validationResult, setValidationResult] = useState<ValidationResult>();

  const { cardGlobalBrand, validCardNumberLength, formattedCardNumber } =
    useMemo(() => {
      const cardGlobalBrand = identifyCardGlobalBrand(cardNumber);
      const validCardNumberLength =
        calculateValidCardNumberLength(cardGlobalBrand);
      const formattedCardNumber = formatCardNumber(cardNumber, cardGlobalBrand);

      return { cardGlobalBrand, validCardNumberLength, formattedCardNumber };
    }, [cardNumber]);

  const handleUpdateCardNumber = (cardNumber: string) => {
    try {
      const cardGlobalBrand = identifyCardGlobalBrand(cardNumber);
      const validCardNumberLength =
        calculateValidCardNumberLength(cardGlobalBrand);

      validateBeforeUpdate(cardNumber, validCardNumberLength);

      setCardNumber(cardNumber);

      setValidationResult({ isValid: true });

      validateAfterUpdate(cardNumber, validCardNumberLength);
    } catch (error) {
      if (error instanceof ValidationError) {
        setValidationResult({
          isValid: false,
          errorType: error.errorType,
          errorMessage: error.errorMessage,
        });
      }
    }
  };

  return {
    cardNumber,
    validationResult,
    cardGlobalBrand,
    maxLength: validCardNumberLength,
    formattedCardNumber,
    handleUpdateCardNumber,
  };
}
```

2024-05-12 07:09 UTC, cys4585 commented on hooks/src/lib/types/ValidationResult.ts
>  export default ValidationResult;
앗! hook 외부에는 항상 `ValidationResult`를 반환하고 있습니다.
`ValidationError`는 hook 내부에서 유효성 검사를 하는 내부 모듈을 `boolean`을 return하는 방식에서 `error`를 throw를 하는 방식으로 바꾸려고 했어요! 그 이유는, 메인 로직(`handleUpdateCardNumber`)을 좀 더 쉽게 이해할 수 있도록 하기 위해서였습니다!

즉, 사용처에는 항상 `ValidationResult`를 반환하고 있고, `ValidationError`는 모듈 내부에서 사용됩니다!

혹시 아래 코드와 같이 validate 함수가 error를 throw하는 게 아니라, boolean을 반환하도록 하는 것을 의도한 말씀이셨을까요..?
```typescript
  const handleUpdateCardNumber = (cardNumber: string) => {
    const cardGlobalBrand = identifyCardGlobalBrand(cardNumber);
    const validCardNumberLength =
      calculateValidCardNumberLength(cardGlobalBrand);

    if (!validateBeforeUpdate(cardNumber, validCardNumberLength)) {
      setValidationResult({
        isValid: false,
        errorType: error.errorType,
        errorMessage: error.errorMessage,
      });
      return;
    }

    setCardNumber(cardNumber);

    if (!validateAfterUpdate(cardNumber, validCardNumberLength)) {
      setValidationResult({
        isValid: false,
        errorType: error.errorType,
        errorMessage: error.errorMessage,
      });
      return;
    }

    setValidationResult({ isValid: true });
  };
```

2024-05-12 07:39 UTC, cys4585 commented on components/src/lib/Modal/Modal.tsx
> +  zIndex = 999,
깊은 고민을 하고 적용하지 않았습니다..! `zIndex`를 사용처에서 주입할 수 있도록 했고, 만약 사용자가 아무런 값도 주지 않는다면 적당히 높은 값(이게 999였습니다)을 default로 두려고 했습니다!

1단계 구현에서 zIndex를 prop으로 정의하지 않아 Modal의 높이를 사용자가 제어할 수 없었던 문제가 있어 2단계에서 개선하려는 의도였습니다!

2024-05-12 07:48 UTC, cys4585 commented on components/src/lib/Modal/Modal.tsx
> +  zIndex = 999,
레이어별로 의미있게 관리하고 사용처에서 사용할 수 있게 한다는 게, 여러 모달이 있을 때 각 모달의 높이를 상수로 관리할 수 있게 한다는 의미가 맞을까요??? (사용자가 'A 모달은 Low! B 모달은 Middle! C 모달은 High!' 생각하고 적용할 수 있도록)

2024-05-12 08:07 UTC, cys4585 commented on hooks/src/lib/useCardNumbers/useCardNumbers.ts
> +      validateAfterUpdate(cardNumber, validCardNumberLength);
error를 throw하는 방식은 -> 예외 케이스일 경우 실행할 동작을 catch 문으로 분리하게 되어, 메인 로직(handleUpdateCardNumber)을 깔끔하게 관리할 수 있다고 생각합니다!

다른 코멘트에도 답변을 달긴 했지만, validation 함수가 error를 throw하든 boolean을 반환하든, custom hook은 항상 'ValidationResult'를 반환하고 있습니다.

다른 validation은 1단계 미션에서 페어와 함께 구현할 때 통일성을 위해 boolean을 반환하는 방식을 적용했습니다! 
이번 2단계 미션에서는 error를 throw 하는 방식이 정상 케이스와 예외 케이스를 더 명확히 분리해서 파악할 수 있다고 판단해서 적용했어요!
이 부분에 대한 브콜의 생각도 들어보고 싶습니다 :)

2024-05-12 09:02 UTC, cys4585 commented on components/src/lib/Modal/Modal.tsx
>  }
적용해보려 했는데, 실패했네요..ㅜ
union type을 적용해서 아래와 같이 수정해봤는데,
```typescript
export type ModalPositionType = 'center' | 'bottom';
export type ModalSizeType = 'small' | 'medium' | 'large';
type ModalConfig = { position: 'center'; size: ModalSizeType } | { position: 'bottom' };
```

position과 size를 한 객체로 묶어서 전달해줘야 하다 보니, 사용처에서 position, size 중 어느 하나를 누락하면 안되는 문제가 있었습니다...
예를 들면, 
```typescript
 <Modal
        isOpen={isOpenCenterModal}
        config={{ position: 'center' }}  // 이렇게 전달하면, size가 누락됩니다.
        zIndex={100}
        onClose={() => setIsOpenCenterModal(false)}
      >
```
```typescript
      <Modal
        isOpen={isOpenSmallModal}
        config={{ size: 'small' }}  // 이렇게 전달하면, position이 누락됩니다.
        onClose={() => setIsOpenSmallModal(false)}
      >
```

해결 방법을 찾지 못해... 아쉽네요 ㅜㅜ

2024-05-13 18:54 UTC, Tanney-102 commented on hooks/src/lib/types/ValidationResult.ts
>  export default ValidationResult;
코멘트를 모호하게 했군요!
- 첫번째 요지는 일관성에 대한 이야기 였어요! 지금은 validationExpireMonth 같은 아이들은 특정 결과를 반환하고 어떤 validation 함수들은 error를 throw 하고 있어서요!
- 두번째는 코드가 조금 복잡해지는 것 같다는 생각이었습니다. validation에서 에러를 throw => 이걸 result로 만들어서 반환 하는 과정을 거치고 있는데 어차피 validation에서 error type을 알도록 할거라면 그냥 validation쪽에서 result까지 만들어 반환해주고훅은 그냥 이걸 그대로 반환하기만 해도 되지 않았을까하는 러프한 생각이었습니다.

2024-05-13 19:01 UTC, Tanney-102 commented on components/src/lib/Modal/Modal.tsx
>  }
> position과 size를 한 객체로 묶어서 전달해줘야 하다 보니, 사용처에서 position, size 중 어느 하나를 누락하면 안되는 문제가 있었습니다...

무슨 말인지 잘 이해하지 못했습니다..!
첫번째 예시처럼 position: 'center'만 전달하면 당연히 ts가 size 를 요구하지 않을까요? 타입을 그렇게 정의 했으니까요.
원래 의도가 position이 center인 경우에는 size를 받고 bottom인 경우에는 size를 받지 않도록 하는 것으로 이해하고 있었는데 아닌가요~?
(정확히는 position이 bottom 일 때 size를 설정하지 '못 하도록 알려줄' 방법이라고 표현하셨죠!)
지금도 타입은 의도한대로 잘 알려주고 있는 것 같아요

<img width="882" alt="스크린샷 2024-05-14 오전 3 57 27" src="https://github.com/woowacourse/react-modules/assets/57767891/cd73ec6d-4997-4e37-8a6b-2263a64ef95e">

<img width="618" alt="스크린샷 2024-05-14 오전 4 00 08" src="https://github.com/woowacourse/react-modules/assets/57767891/eb70d5e9-f40f-4a56-94f0-15399fff8cca">

2024-05-13 19:19 UTC, Tanney-102 commented on hooks/src/lib/useCardNumbers/useCardNumbers.ts
> +      validateAfterUpdate(cardNumber, validCardNumberLength);
error를 throw하는 방식을 '선택' 했다면 왜 기존 함수에는 적용하지 않았는지가 정확한 질문이었겠네요~
error를 throw 더 낫겠다고 했던 판단이 boolean을 반환하는 함수에는 유효하지 않았던 건지? 그렇다면 그 이유는 무엇인지? 궁금해요.

추가적으로 그냥 error throw 방식에 대한 의견을 말씀드려볼게요.
throw한 에러를 catch 블럭에 모아서 처리할 수 있음이 장점이라고 말씀하신 것으로 이해했습니다.
어떤 방식이 확실히 더 좋다고 말씀드리기는 어렵지만 error를 던지는 게 마냥 장점만 있지는 않습니다. 함수 입장에서야 error를 throw하면 그만이지만 사용처에서는 함수가 에러를 던진다는 사실을 알고 있어야 하고 의식적으로 catch 해주어야 합니다. 휴먼에러로 catch하지 못하면 자칫 런타임에 uncaught error를 보게 될 수도 있겠죠. 반면 result 객체 같이 특정 결과값을 반환하면 사용처가 성공/실패 여부에 따라 분기를 하도록 강제할 수 있다는 점이 장점이에요. 안정적인 코드로 유명한 rust는 Result, Option 같은 enum을 사용해 함수의 결과 값에 따라 강제하는 방식을 제공하기도 합니다.(실제로 많이 사용함) 복잡하지만 적어도 안전하거든요. 
애초에 js 자체가 그리 안정적인 언어도 아니고.. 일반적인 함수라면 뭐 아무래도 상관 없다고는 생각하지만 validation 처럼 성공/실패 라는 결과가 명확히 존재하는 함수에서는 error를 던지기 보다 명확하게 결과를 반환하는 편이 좋지 않았을까 하는 생각이드네요.

2024-05-13 19:21 UTC, Tanney-102 requested changes
안녕하세요 수야! 리뷰 반영 고생 많으셨습니다!
질문 주신 내용 포함하여 몇몇 reply 남겨두었어요.
사실 추가적으로 더 반영은 하지 않아도 될 것 같은데 혹시 더 욕심내고 싶은 부분이 있다면 말씀해주세요.
없다면 바로 머지하겠습니다!

2024-05-15 02:38 UTC, cys4585 commented on components/src/lib/Modal/Modal.tsx
>  }
아.. 제가 말씀을 모호하게 드린 것 같네요!!

사용처에서 모달을 사용할 떄 `position`과 `size` props는 주지 않아도 기본 값(`position = 'center', size = 'medium'`)이 적용되도록 하고 싶습니다.
근데 객체(`ModalConfig`)로 감싸게 됐을 때, `position`과 `size` 둘 다 전달하지 않았을 때는 대응할 수 있었는데, `position`은 주고 `size`는 주지 않을 때 / `size`는 주고 `position`은 주지 않을 때 대응이 되지 않았어요.

2024-05-15 03:01 UTC, cys4585 commented on hooks/src/lib/useCardNumbers/useCardNumbers.ts
> +      validateAfterUpdate(cardNumber, validCardNumberLength);
먼저, 다른 hook을 수정하지 않은 것은 미션 요구 사항과 관련 없는 코드는 수정하지 않으려 했습니다. diff를 보고 리뷰할 때 방해가 될 거라 생각했어요. 같은 이유로 useCardNumbers 파일 이름도 그대로 두었답니다 :)

error throw 방식의 예외 처리의 단점에 대해 브콜의 의견을 말씀해 주셔서 정말 감사합니다!! 브콜의 말씀을 듣고 보니, 안정성 측면에서 단점이 있는 js에서 validaiton을 할 때 error를 throw 하는 것 보다, 명확한 결과(성공/실패)를 반환하도록 하는 게 좋겠다는 생각이 드네요!

2024-05-15 03:06 UTC, cys4585 commented on hooks/src/lib/useCardNumbers/useCardNumbers.ts
> +      validateAfterUpdate(cardNumber, validCardNumberLength);
다만, 다음 미션을 진행해야 해서 코드 수정을 하진 않았습니다...ㅜ 그래도 괜찮다면 머지..를 해주시면 감사하겠습니다.....!!

2024-05-15 03:06 UTC, cys4585 commented on components/src/lib/Modal/Modal.tsx
>  }
**추가 시도**
```typescript
export type ModalPositionType = 'center' | 'bottom';
export type ModalSizeType = 'small' | 'medium' | 'large';
type ModalConfig =
  | { position: ModalPositionType }
  | { size: ModalSizeType }
  | { position: 'center'; size: ModalSizeType };

export interface ModalProps {
  isOpen: boolean;
  config?: ModalConfig;
  zIndex?: ModalZIndex | number;
  children: React.ReactNode;
  onClose: () => void;
}

```

위와 같이, ModalConfig를 추가 정의해서 모든 position, size 전달 케이스에 대응했습니다. 근데, default값을 부여하기 위한 Modal 내부 구현체가 만족스럽지 못하네요.... 일단 제 수준에서 구현 가능한 퀄리티로 구현했습니다..!

2024-05-16 01:38 UTC, Tanney-102 approved these changes
마지막까지 고생많으셨어요! 바로 머지하도록 하겠습니다!

2024-05-16 01:38 UTC, Tanney-102 commented on components/src/lib/Modal/Modal.tsx
> +  | { position: 'center'; size: ModalSizeType };
👍

2024-05-16 01:39 UTC, merged