[2단계 - 페이먼츠 모듈] 마스터위(명재위) 미션 제출합니다.
woowacourse/react-modules pull request #59
Opened 2024-05-11 02:46 UTC by Jaymyong66

안녕하세요 케빈!

## 다음 목표에 집중했습니다.

### 모달

- 모달 컴포넌트 재사용(Alert, Confirm, Prompt 모달), 크기 옵션 추가(large, medium, small)
- 커스텀 가능한 부분 늘리기
- 스토리북 작성

### 페이먼츠 커스텀 훅

- 카드 브랜드 식별 및 유효성 검사
- 사용자 입력 시, 카드 번호 구분하여 표시
- 카드사별 카드 번호 포맷팅 규칙을 적용
- RTL 적용

### 패키지 npm 배포 주소

[페이먼츠 커스텀 훅](https://www.npmjs.com/package/@jaymyong66/payments-hooks)

[모달 컴포넌트](https://www.npmjs.com/package/@jaymyong66/simple-modal)

### 스토리북 배포 주소

[스토리북](https://66334cce181d6ad998aac0c9-bhazzqojih.chromatic.com/?path=/story/modal-alertmodal--large-)centered

### 로컬 실행

```bash
# modal 테스트
cd component
npm install
npm run storybook 

# custom hook 테스트
cd hooks
npm install
npm run test
```

질문 사항은 코멘트로 남기겠습니다!

2024-05-11 05:42 UTC, Jaymyong66 commented on hooks/src/lib/useCardNumber/useCardNumber.util.ts
> + */
여기서 returns 의 타입을 이렇게 지정해도 되는지 궁금하네요.

2024-05-11 05:47 UTC, Jaymyong66 commented on hooks/src/lib/useCardNumber/useCardNumber.util.ts
>  export const isFulledCardNumber = (cardNumber: string) => cardNumber.length === 4;
사용자가 useCardNumber의 cardNumbers:string[] 를 반환받아 다음 gif처럼 포매팅하여 보여주는 함수인데요.
해당 함수도 유틸함수 느낌으로 사용할 수 있도록 라이브러리가 제공하는게 좋을까요?

![화면 기록 2024-05-11 오후 2 42 58](https://github.com/woowacourse/react-modules/assets/78201530/f0a77954-c028-434c-bce3-fab6594acfba)

2024-05-11 05:51 UTC, Jaymyong66 commented on components/src/lib/PromptModal/PromptModal.tsx
> +        <Modal.ModalInput className={styles[inputClass]} value={value} onChange={onChange} ref={inputRef} />
ModalInput에서 onSubmit시, 해당 값을 반환시켜주기 위해 useRef를 사용했습니다. 해당 부분이 괜찮은지, 혹은 더 좋은 방법이 있는지 궁금합니다.

2024-05-11 05:57 UTC, Jaymyong66 commented on hooks/src/lib/useCardNumber/useCardNumber.ts
> +    cardNumbers: formattingCardNumbers(cardNumbers, cardFormat),
카드 번호를 카드 브랜드에 따라 포매팅하라는 요구사항이 있어서, 문자열의 배열로 반환하도록 하였습니다.

2024-05-12 04:35 UTC, JeongBin0227 commented
> rest props의 DX 관련

저는 개인적으로 DX 는 정말 중요하다고 생각하는 사람중에 한명인데, 이렇게 rest props를 전달하는 방식은 라이브러리나 UI 컴포넌트를 더 유연하고 확장 가능하게 만드는데 좋은거 같아요. 하지만 여기서 rest props를 통해 넘겨지는 프로퍼티들이 컴포넌트 내부에서 어떻게 사용되는지 문서화하지 않으면, 사용자가 한번더 검증하는 과정을 거쳐야해서 오히려 불편하지 않을까 생각됩니다.

2024-05-12 04:43 UTC, JeongBin0227 commented
https://www.npmjs.com/package/@jaymyong66/payments-hooks

-> 각 훅마다 간단한 사용 예제가 제공되어 있어서, 사용자가 어떻게 해당 훅을 사용할 수 있는지 쉽게 이해할 수 있고, 각 훅의 반환값에 대해 자세한 설명이 있어 사용자가 반환되는 객체의 구조와 각 속성의 용도를 명확히 이해할 수 있는점에서는 좋은거 같아요. 

-> 훅의 결과는 잘 표현했는데, 각 훅의 내부 동작 방식이나 로직에대한 기술적인 설명도 있으면 어떨까 생각들었습니다.
그리고 영어로 적혀있어서 그런지 모르겠는데.. 개인적으로 각 훅에서 입력값 제한등의 대한 설명이 있었지만, 눈에 잘 들어오지 않는거 같아 중요한 내용이니 강조하거나 좀더 상세한 로직을 제공하면 더 좋겠다라는 생각이 들었습니다.

2024-05-12 04:44 UTC, JeongBin0227 commented
각 모달에서 버튼의 문구를 변경할수 있으면 좋을거 같아요. 그래야지 활용도가 높아질거 같아요
<img width="289" alt="image" src="https://github.com/woowacourse/react-modules/assets/45503248/202e0201-c53e-4bb4-a513-1ab0d151cf8b">

2024-05-12 04:52 UTC, JeongBin0227 commented
https://www.npmjs.com/package/@jaymyong66/simple-modal

-> 역시 각 모달 유형(Alert, Confirm, Prompt) 및 기본 모달(Base Modal)의 사용법이 잘 정리되어 있고, 각 컴포넌트의 props에 대한 상세 설명이 포함되어 있어 좋은 거같아요. 또한 사용 예제도 좋네요.

-> 각 모달의 반환값에 대한 정보가 조금 더 상세하게 제공되면 좋을 것 같아요. 예를 들어, 이벤트 핸들러의 파라미터 형식이나, 각 이벤트가 어떤 상황에서 호출되는지 등의 추가 정보가 있으면 이 문서를 보는 사람들에게 도움이 될거 같아요

2024-05-12 05:05 UTC, JeongBin0227 requested changes
안녕하세요 마스터위.

라이브러리를 잘 만들기 위해 많은 고민을 한게 보여서 좋았습니다 👍 PR에서 적어주신것처럼 마스터위 고민 위주로 리뷰를 했는데, 혹시 이해가 안되는 부분이나 설명이 더 필요한 부분이 있으면 편하게 말해주세요~

미션하느라 고생많으셨습니다~ 💯

2024-05-12 05:05 UTC, JeongBin0227 commented on hooks/src/lib/useCardNumber/useCardNumber.util.ts
>  export const isFulledCardNumber = (cardNumber: string) => cardNumber.length === 4;
근데, isFulledCardNumber와 isFulledCardNumbers 함수 이름이 비슷하여 헷갈리수도 있을거 같은데, 각 함수의 역할을 좀 더 명확하게 표현할 수 있는 이름으로 변경하면 어떨까요

2024-05-12 05:05 UTC, JeongBin0227 commented on components/src/lib/PromptModal/PromptModal.tsx
> +        <Modal.ModalInput className={styles[inputClass]} value={value} onChange={onChange} ref={inputRef} />
구현을 살펴보면, useRef를 사용하여 input의 참조를 가져오고, 그 값을 onSubmit 함수에 전달하는 방식은 React에서 입력 항목의 값을 처리하고 있는데, 이는 복잡한 상태관리에서 합리적인 방법인거 같아요. 

근데 코드를 보면 value와 onChange를 이미 PromptModal의 props로 받고 있어서, useState를 사용하여 입력 값을 관리하는 방법도 고려할 수 있을거 같아요. 

적절한 상황에서 useRef 방식을 쓰는건, 합리적이고 당연하지만, React의 기조가 상태 리프트업 방식이기 때문에 가능하면 useState를 사용하는 것을 추천드립니다. 이러면, 코드를 새로 보는 사람들은 어플리케이션에서 상태의 흐름을 추적하고 디버깅하기가 더 쉽게 만드는거 같아요

2024-05-12 14:19 UTC, Jaymyong66 commented on hooks/src/lib/useCardNumber/useCardNumber.util.ts
> +  cardNumbers.length === cardNumbersLength;
다음 커밋에서 변경하였는데요. 확실히 변수로 만들고 사용하니 가독성도 올라가는 것 같습니다.
amex 검사 부분의 Includes 사용도 좋았는데 그러면 타입때문에
`else if ([CARD_BRAND.amex.signature[0], CARD_BRAND.amex.signature[1]].includes(firstTwoDigits as 34 | 37))`
로 바꿔야할 것 같더라구요. 혹시 해결법이 맞을까요?
`(Argument of type 'number' is not assignable to parameter of type '34 | 37'.ts(2345)
const firstTwoDigits: number - ts에러)`

입력 값을 타입 단언 한다는게 부자연스러워서 지금과 같은 일반적인 OR문으로 바꾸었습니다.
`else if (CARD_BRAND.amex.signature[0] === firstTwoDigits || CARD_BRAND.amex.signature[1] === firstTwoDigits)`

다른 얘기로 케빈은 이 부분을 어떻게 보아야 이렇게 바꿀 생각을 하시는지 궁금하네요..! 🤣

[refactor(useCardNumber.utll.ts): 카드 브랜드 검사 로직 변경](https://github.com/woowacourse/react-modules/pull/59/commits/7162b930a6d42e44b9f82fb7dc1151f1c4fa4979)

2024-05-12 14:23 UTC, Jaymyong66 commented on components/src/App.tsx
>  }
로컬에서 실행시켜보시기 편하지 않을까 하는 생각에 우선 남겼는데 지우는게 깔끔해보이긴 하네요..! 
의미 없는 주석들은 모두 지웠습니다!

2024-05-12 14:26 UTC, Jaymyong66 commented on hooks/src/lib/useCardNumber/useCardNumber.util.ts
>  export const isFulledCardNumber = (cardNumber: string) => cardNumber.length === 4;
해당 `isFulledCardNumber` 함수는 리팩토링 과정에서 사용하지 않는 함수라 삭제했습니다.
만약 나중에 해당 함수가 필요해져서 구분이 필요하다면 isFulledCardNumber, areAllCardNumberFulled  이런식으로 구분하면 좋겠네요!

2024-05-12 14:36 UTC, Jaymyong66 commented on hooks/src/lib/useCardNumber/useCardNumber.util.ts
>  export const isFulledCardNumber = (cardNumber: string) => cardNumber.length === 4;
formattingValue 에 대한 docs 문서도 업데이트 해보았습니다!

2024-05-12 14:49 UTC, Jaymyong66 commented on components/src/lib/PromptModal/PromptModal.tsx
> +        <Modal.ModalInput className={styles[inputClass]} value={value} onChange={onChange} ref={inputRef} />
케빈의 말을 보니 useRef를 쓰지 않고 이렇게도 쓸 수 있을 것 같네요! 
반영한 커밋 : [refactor(PromptModal.tsx): onSubmit에서 useState로 value 관리](https://github.com/woowacourse/react-modules/pull/59/commits/4c660f4754f8e5a6b3345173abd65aa017ae3474)
이런 의도의 피드백이 맞나요?

혹은 어차피 이 라이브러리의 사용자가 value를 PromptModal에 다음과 같이 주입을 해줘야하니, 사용자가 onSubmit 시 상태를 알아서 관리하면 된다는 말일까요?

```tsx
// PromptModal 사용 예시
const OtherModal = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [value, setValue] = useState('');
  const handleToggle = () => setIsOpen((prev) => !prev);
  const handleChange = (e: ChangeEvent<HTMLInputElement>) => setValue(e.target.value);
  const handleSubmit = (value: string) => console.log(value);

  return (
    <PromptModal
      position="bottom"
      size="medium"
      isOpen={isOpen}
      onToggle={handleToggle}
      title="쿠폰 번호를 입력해 주세요."
      value={value}
      onChange={handleChange}
      onSubmit={handleSubmit}
    />
  );
};
```

2024-05-12 15:35 UTC, Jaymyong66 commented
안녕하세요 케빈!
피드백 모두 반영하였습니다~!

피드백 반영하며 궁금한 부분은 코멘트 답변으로 달아두었습니다.
혹시 제가 놓친 부분이나 추가적인 피드백이 있으시다면 알려주세요!

감사합니다.

### 피드백 반영 패키지 npm 배포 주소

[페이먼츠 커스텀 훅](https://www.npmjs.com/package/@jaymyong66/payments-hooks)

[모달 컴포넌트](https://www.npmjs.com/package/@jaymyong66/simple-modal)

### 스토리북 배포 주소

[스토리북](https://66334cce181d6ad998aac0c9-grppptilvl.chromatic.com/?path=/story/modal-alertmodal--large-centered)

2024-05-13 16:43 UTC, JeongBin0227 commented on components/src/lib/PromptModal/PromptModal.tsx
> +        <Modal.ModalInput className={styles[inputClass]} value={value} onChange={onChange} ref={inputRef} />
아니요! 반영한 커밋대로 하신게 전달하려는 의도가 맞습니다 👍

2024-05-13 17:12 UTC, JeongBin0227 approved these changes
안녕하세요 마스터위!

코드 반영해주신거 잘 확인했습니다. 수정 하신 내용들을 모두 확인했는데, 혹시 제가 놓친게 있다면 알려주세요! 

문서도 코드도 충분히 잘했다고 생각해서 머지할게요! 비교적 이른 머지가 됐는데, 추가적으로 궁금한 내용이나 더 얘기하고 싶은 내용이 있다면 알려주세요! 2단계 미션 완료하신거 축하드려요~ 💯

2024-05-13 17:12 UTC, merged