[2단계 - 페이먼츠 모듈] 썬데이(김유선) 미션 제출합니다.
woowacourse/react-modules pull request #64
Opened 2024-05-11 13:18 UTC by useon

안녕하세요 지그 ! 주말 잘 보내고 계신가요 ? 주말 내내 비가 오지만 마음은 화창한 하루 되시길 바라요 .. 🌞
이번 2단계 미션에서 모달 컴포넌트의 재사용과 확장성에 대해 고민해볼 수 있는 시간이었습니다 😊 
# 🚀실행 방법 
- 모달
```
cd components
npm install

// 로컬 환경 실행
npm run dev

// 스토리북 실행
npm run storybook
```
- 커스텀 훅
```
cd hooks
npm install

// 로컬 환경 실행
npm run dev

// RTL 테스트 실행
npm test
```
# 🔗 배포 링크
- [스토리북](https://useon.github.io/react-modules/?path=/docs/components-modal--docs)
- [모달 링크](https://www.npmjs.com/package/@roqkftjs/react-payments-module)
- [커스텀 훅 링크](https://www.npmjs.com/package/@roqkftjs/react-payments-custom-hooks)

2024-05-11 14:59 UTC, useon commented on components/src/lib/modal/AlertModal.tsx
> +export default AlertModal;
사용자가 간편하게 사용할 수 있도록 기본적인 모달 컴포넌트(확인 모달, 확인/취소 모달, 입력 모달)를 만들었는데, 이 모달 컴포넌트(ConfirmModal, PromptModal 포함)의 자유도는 얼마나 주어야 할 지에 대한 고민이 들었습니다. 지금까지의 결론은 사용자가 자유롭게 구성할 수 있는 커스텀 모달이 이미 존재하니 간편하게 사용할 수 있는 모달을 제공하는 것이 좋지 않을까 판단하여, 기본적인 확인 모달, 확인/취소 모달, 입력 모달은 사용자가 간편하게 사용할 수 있도록 기본 값을 주어 구현하였습니다. 사용자 관점에서 어떤 부분을 개선하면 더 편리하게 사용할 수 있을지 알려주시면 감사하겠습니다 😊

2024-05-12 00:16 UTC, zigsong commented
안녕하세요 썬데이~ 오늘 종일 스케줄이 있어 내일(5/13) 오전에 리뷰 남기도록 하겠습니다 :)

2024-05-13 00:28 UTC, zigsong requested changes
안녕하세요 썬데이~ 2단계 과제까지 수고하셨습니다! 

새로 추가된 미션 요구사항을 꼼꼼하게 반영하고 컴포넌트의 개선도 이뤄진 것 같아요 ㅎㅎ 

질문하신 내용에 대한 답과 제가 생각한 몇 가지 제안사항 남겼으니 확인 부탁드려요!

2024-05-13 00:28 UTC, zigsong commented on components/README.md
> +
리드미가 정말 섬세해서 사용하고 싶어지네요 :D

2024-05-13 00:28 UTC, zigsong commented on components/src/lib/modal/AlertModal.tsx
> +export default AlertModal;
지금 썬데이가 구현하신 대로 alert, confir, prompt 등 특정한 기능을 제공하는 모달은 어느 정도 사용방법에 제약을 두되 기본값을 제공하는 형식이 좋다고 생각합니다. 

지금 상태도 충분히 괜찮지만, 만약 사용자에게 자유도를 조금 더 부여한다면

- `확인`, `취소` 등의 텍스트는 기본값으로 제공하고 버튼의 텍스트를 직접 설정할 수도 있게끔
- 버튼의 색상을 설정할 수 있게끔 

하는 추가 방식들이 있을 것 같네요.

하지만 지금으로도 충분히 좋습니다 😉

2024-05-13 00:28 UTC, zigsong commented on components/src/lib/modal/ConfirmModal.tsx
> +          actionFn={onClose}
`취소`와 `확인`을 눌렀을 때는 서로 다른 함수가 호출될 수 있게끔 해줘야 해요~ 

그리고 `actionFn`이라는 이름은 어떤 액션을 취할 것인지 의미를 알기 어렵습니다.

button에 붙는 이벤트인 만큼 `onClick` 등의 네이밍으로 명확하게 사용하는 것을 권장드려요

2024-05-13 00:28 UTC, zigsong commented on components/src/lib/modal/Modal.tsx
> +    Pick<HTMLAttributes<HTMLElement>, 'style'> {
`HTMLAttributes<HTMLElement>`에서 가져온 `style`은 어디에서 쓰이나요? 

반드시 `HTMLAttributes<HTMLElement>`에서 가져와야 했던 프로퍼티인가요?

2024-05-13 00:28 UTC, zigsong commented on components/src/lib/modal/Modal.tsx
> +      fontColor?: string;
이만큼도 양이 너무나 많아져 타입을 유추하기 어려워, 별도의 인터페이스로 묶어보면 어떨까요?

2024-05-13 00:28 UTC, zigsong commented on hooks/src/lib/test/useCardNumbers.test.ts
> +describe('useCardNumbers 커스텀 훅 테스트', () => {
새로운 요구사항에 대한 테스트도 잘 적어주셨네요 😊

2024-05-13 00:28 UTC, zigsong commented on hooks/src/lib/validators/newCardInputValidator.ts
> +export const validateCardNumber = (brand: string, value: string) => {
validation이 엄청 많고 복잡해졌네요 😵

2024-05-13 12:57 UTC, useon commented on components/README.md
> +
그렇다면 정말 다행이에요 😆 !!!!!!!!!!!!

2024-05-13 12:57 UTC, useon commented on components/src/lib/modal/ConfirmModal.tsx
> +          actionFn={onClose}
지그 말씀대로 의미를 알기 어려울 것 같네요! 😅 버튼의 의도에 따라 함수를 호출하도록 코드를 수정하였습니다 😉 [a9e46ee](https://github.com/woowacourse/react-modules/pull/64/commits/a9e46eee5cb5a7596b5f33dc44564260ed369fed)
[091d85a](https://github.com/woowacourse/react-modules/pull/64/commits/091d85abb225a1ec6f23afcee271e95fa3d4f5d3)

2024-05-13 12:57 UTC, useon commented on components/src/lib/modal/Modal.tsx
> +    Pick<HTMLAttributes<HTMLElement>, 'style'> {
style 프로퍼티를 명시하지 않고 이렇게 써볼 수도 있지 않을까해서 작성하였습니다! 
```ts
export interface ModalProps extends React.PropsWithChildren {
  children?: React.ReactNode;
  isOpen: boolean;
  position: 'top' | 'bottom' | 'center';
  size?: 'small' | 'medium' | 'large';
  style?: React.CSSProperties;
  onClose: () => void;
  onConfirm?: () => void;
}
```
style 프로퍼티와 타입을 명시하도록 수정하였습니다 😊 [a9e46ee](https://github.com/woowacourse/react-modules/pull/64/commits/a9e46eee5cb5a7596b5f33dc44564260ed369fed)

2024-05-13 12:57 UTC, useon commented on components/src/lib/modal/Modal.tsx
> +      fontColor?: string;
아직 어느 정도의 타입들을 얼마나 분리해야 하는지 기준이 잡혀있지 않아서 함께 작성해도 좋지 않을까 해서 적었는데 타입을 유추하기 힘들 수도 있겠군요 !! 😅 보통 별도의 인터페이스로 묶는 기준이 있는지 궁금합니다 😊 리뷰 반영하여 수정했습니다 ! [83109f8](https://github.com/woowacourse/react-modules/pull/64/commits/83109f88b72f99decf65baeb6a5b5d3cc141a0c3)

2024-05-13 12:57 UTC, useon commented on hooks/src/lib/validators/newCardInputValidator.ts
> +export const validateCardNumber = (brand: string, value: string) => {
validator가 많고, 길어짐에 따라 가독성이 떨어진다고 느껴 validate를 파일별로 분리해보았습니다 😉 [f3946d7](https://github.com/woowacourse/react-modules/pull/64/commits/f3946d72449300a13871e74be56877c39f3dd5d6)

2024-05-13 14:39 UTC, useon commented
안녕하세요 지그! 이번 리팩토링에서는 특정 기능을 제공하는 모달이 **어느 정도의 자유도를 가지면 좋을지**에 대해 더 고민해 보는 시간이었어요. 프로퍼티를 더 추가하면서 자유도를 더 주었지만 적절한 기준을 잡아 어디까지 열어두어야 할지에 대해서는 여전히 고민이 되네요! 아마 정답이 없는 문제라 앞으로도 여러 경험과 함께 만드는 사람끼리 기준을 만들어 가는 것이 중요하다는 생각을 했습니다. 

주신 리뷰를 읽고 어떻게 개선하면 좋을지 고민해 보며 코드를 수정했는데 제가 잘못 이해한 부분이 있거나 추가로 개선하면 좋을 부분이 있다면 코멘트 남겨주시면 또 열심히 고민해 보도록 하겠습니다 😊 !!!
**댓글에 리뷰 반영 커밋과 질문**을 남겼습니다! 이번 주도 파이팅이에요 지그 감사합니다 🌞 !!!!!

2024-05-14 08:35 UTC, zigsong commented on components/src/lib/modal/Modal.tsx
> +      fontColor?: string;
인터페이스로 묶는 정해진 기준이 있다기보다는, 그냥 `{ ... }`처럼 리터럴로 선언한 내용물이 너무 많아지면 (제 기준에는 3~4개 이상?)
별도로 분리하여 가독성을 높이고자 하는 것 같습니다 :)

2024-05-14 08:38 UTC, zigsong requested changes
안녕하세요 썬데이~ 리뷰 모두 잘 반영해주신 것 확인했습니다! 

실제 사용을 해보려고 썬데이의 모듈 npm 배포 링크를 받아 README에 있는대로 코드 작성해보았는데요, 다음 에러가 뜨네요

![image](https://github.com/woowacourse/react-modules/assets/44080404/7940f670-30fa-4bce-b9ca-849da2f0ba3b)

`JSX element type 'Modal' does not have any construct or call signatures`

혹시 썬데이가 직접 모듈을 받아 실행해보았을 때는 잘 되었나요?

2024-05-15 11:07 UTC, zigsong approved these changes
안녕하세요 썬데이! 

마지막으로 문서 업데이트까지 잘 챙겨주셔서 감사합니다 🤗 

2단계까지 오시느라 수고 많으셨고, 알차게 배워가셨길 바래요! 

다음 미션도 화이팅입니다

2024-05-15 11:07 UTC, merged