[2단계 - 페이먼츠 모듈] 헤인(방세린) 미션 제출합니다.
woowacourse/react-modules pull request #66
Opened 2024-05-11 14:48 UTC by Hain-tain

안녕하세요, 6기 FE 헤인입니다.☺️
2단계 주요 요구사항은 아래와 같습니다.

---
## 📍 배포 주소
[🎀 components 스토리북 배포 주소](https://6638ad0a3b7cb5cd9e5e2fde-svhcxpkhnw.chromatic.com/?path=/docs/button--docs)
[💚 모달 컴포넌트 모듈 `hain-tain-components`](https://www.npmjs.com/package/hain-tain-components)
[💜 페이먼츠 모듈 `hain-tain-hooks`](https://www.npmjs.com/package/hain-tain-hooks)

## 🤔 고민했던 점 및 질문
### 1. 카드 브랜드, 상태로 관리해야 할까?
- 2단계에서 새롭게 추가된 주요 요구사항은 `Visa`, `Mastercard`, `AMEX`, `Diners`, `UnionPay`와 같이 카드 번호에 따라 카드 브랜드를 구분하고, 카드 브랜드에 따라 포멧팅을 하는 것이었습니다. 따라서 카드 번호에 따라 카드 브랜드를 식별하는 로직이 필요했고, 당연하게도 식별한 카드 브랜드를 함께 사용자에게 제공해야 했습니다.
- [리엑트 공식문서](https://ko.react.dev/learn/thinking-in-react#step-3-find-the-minimal-but-complete-representation-of-ui-state)에서 컴포넌트 안의 다른 state를 가지고 계산이 가능하다면 state로 관리할 필요가 없다는 글을 보았습니다. 저는 카드 브랜드는 카드 번호(state)로 계산 가능하다고 생각하여 별도의 상태로 만들지 않고 구현하게 되었습니다.
  >컴포넌트 안의 다른 state나 props를 가지고 계산 가능한가요? 그렇다면 절대로 state가 아닙니다!
- 그런데 한편으로는 카드 번호를 이용하기 위해 `useCardNumber`에서 한꺼번에 너무 많은 것들을 관리하고 있는 것은 아닐까 고민이 되었습니다. 카드 브랜드를 별도의 상태로 만들고, `useCardBrand`와 같은 훅을 이용하여 관리해주는 것이 더 좋았을까? 그런데, 카드 브랜드는 상태로 굳이 관리될 필요가 없는 친구이지 않나? 라는 생각이 계속 반복되었습니다. 결국 상태로 관리하고 싶지 않다는 마음이 더 커서 현재 상태를 유지하게 되었습니다.

### 2. 모달, 현재처럼 props 로 받는 방식 vs 합성 컴포넌트 방식
- 모달을 사용하는 입장에서 어떤 방식이 더 편하게 사용할 수 있을지 고민이 되었습니다. `props 로 받는 방식`의 경우에는 반드시 넣어야하는 필수 프로퍼티를 제외하고는 default 값이 있기 때문에 하나의 태그안에 원하는 프로퍼티만 넣어서 편하게 만들 수 있다는 장점이 있다고 생각하였습니다. 반면, 옵션을 많이 지정하기 위해서는 props가 길어지게 되고, 각각의 props가 어디에 어떻게 필요한 것인지 단번에 파악하기 어렵다는 단점이 있다고 생각하였습니다.
- 반면, `합성 컴포넌트 방식`의 경우에는 자유롭게 모달 내부의 레이아웃을 구성할 수 있고, 무엇보다 관심사 분리가 보다 명확하게 되어 각각의 props를 넣어줄 수 있다는 장점이 있다고 생각하였습니다. 반면, 정말 간단한 모달을 만들고 싶어도, `ModalHeader`, `ModalBody`, `ModalFooter` 등 내부를 모두 지정해주어야 한다는 단점이 있다고 생각하였습니다.
- 저는 두 방식 중, props가 많더라도 하나의 태그로 편리하게 모달을 생성할 수 있게 해주는 것이 모듈을 사용하는 사람들에게 더 편하고 쉬운 경험을 제공할 수 있다고 생각하여 props 를 주는 방식으로 개발하게 되었습니다. 그런데 요구사항이 점점 늘어나면서 props가 지나치게 많아지자 오히려 더 불편해졌다는 생각이 들기 시작하였습니다.
- 프로그래밍 세계에 정답은 없지만, 컴포넌트 라이브러리로서 어떤 경험을 제공하는 것이 더 좋을지 고민이 많이 됩니다. (현재, Modal 컴포넌트의 경우에는 합성컴포넌트 방식으로 변경하고싶었으나 시간적 여유가 부족하여 일단 기능 요구 사항을 충족하는대로 제출하게 되었습니다. ) 이것에 대해 조언해주실 부분이 있으실까요?

- props 로 받는 방식
  ```js
   <Modal
        isOpened={isOpened}
        closeModal={handelModalClose}
        title="제목"
        primaryButton={{
          text: '확인',
          onClick: () => {
            alert('확인');
          },
        }}
        secondaryButton={{
          text: '닫기',
          onClick: handelModalClose,
        }}
      />
  ```
- 합성 컴포넌트 방식
  ```js
    <Modal>
      <Modal.ModalHeader>
      {...}
      </Modal.ModalHeader>
      </Modal.ModalBody>
      {...}
      </Modal.ModalBody>
      <Modal.ModalFooter>
      {...}
      </Modal.ModalFooter>
  </Modal>
  ```

### 3. 만약, 개발을 처음 배우는 사람이 처음 이 모듈을 접했다면, 어떤 점이 헷갈리고 실수하기 쉬울까?
- 이번 미션은 이것을 쓰는 사람들이 존재한다고 가정하고 구현을 해보았습니다. 그러므로 제가 가장 신경쓴 점은 `다른 사람들이 이해하기 쉽고, 쓰기 쉽게 만들자!` 였습니다. (모듈인만큼 UX 뿐만 아니라 DX 측면에서도 좋은 경험을 제공하고 싶었습니다.) 이를 위해 스토리북에 docs 및 viewport도 추가하고, npm docs 도 상세하게 작성하기 위해 노력하였습니다. 그러나 여전히 부족한 점이 많으리라 생각됩니다.
- 특히, IT에 대해 잘 모르거나, 개발을 처음 배우는 사람이 이 모듈을 사용하려고 한다면, 어떤 점이 개선되면 더 쉽게 이 모듈을 사용할 수 있을까요? 이 모듈을 사용해야 한다면, 어떤 점이 가장 불편하게 느껴질까요? 다음 단계에서 개선할 수 있도록 새롭고 환기된 시각으로 바라봐주시면 감사하겠습니다.
---
고민이 많아 변경사항에 비해 시간이 오래 걸린 것 같습니다ㅠㅠ 
+) 현재 `useCardNumber` 에서 `formattingValue`을 input value 로 사용할 경우, 카드 번호의 중간 부분을 바꿔도 커서가 맨 뒤로 이동한다는 문제가 있습니다. UX 적으로 몹시 좋지 않다고 생각하지만, 이를 고치기엔 시간이 많이 걸릴 것 같고, 일단 기능요구사항은 충족하였기에 우선적으로 리뷰요청 보냅니다. 추후 시간이 되면 구현해보도록 하겠습니다.
감사합니다🙏

2024-05-12 03:58 UTC, 365kim commented on components/src/lib/Modal/Modal.tsx
> +  size?: ModalSize;
기본값이 있는 prop은 주석으로 안내해줘도 좋을 것 같습니다 :)

  /**
   * @defaultValue 'large'
   */
  size?: ModalSize;

- 참고: https://tsdoc.org/pages/tags/defaultvalue/

2024-05-12 04:25 UTC, 365kim commented on components/src/lib/Modal/Modal.tsx
> +  buttonJustifyContent?: ButtonJustifyContent;
> 모달, 현재처럼 props 로 받는 방식 vs 합성 컴포넌트 방식
(중략)
저는 두 방식 중, props가 많더라도 하나의 태그로 편리하게 모달을 생성할 수 있게 해주는 것이 모듈을 사용하는 사람들에게 더 편하고 쉬운 경험을 제공할 수 있다고 생각하여 props 를 주는 방식으로 개발하게 되었습니다. 그런데 요구사항이 점점 늘어나면서 props가 지나치게 많아지자 오히려 더 불편해졌다는 생각이 들기 시작하였습니다.


모달 컴포넌트를 설계할 때,  각 방식의 장단점을 이미 잘 파악하고 계신 것 같아요 👍

컴포넌트의 복잡도가 크지 않다면 헤인이 말씀해주신 것처럼 props 방식이 좋아보입니다. 특히 구성요소가 비교적 단순하거나 커스터마이징의 필요성이 낮은 경우, 개발하는 입장에서도 더 빠르게 구현할 수 있어 보여요.

제 개인적인 의견으로는 현재 props의 개수로는 현재 구현해주신 방식을 유지해도 좋다고 생각합니다. 그래서 코드 변경을 요청드리는 것은 아니지만, 이 방식의 앞으로의 확장성에 대해서는 한번 같이 이야기 나눠보고 싶습니다.  


<br/>

`buttonJustifyContent`와 같은 구체적인 스타일링 옵션을 Modal이 직접 관리하는 것을 보고, Modal이라는 중앙 관리자가 너무 많은 구체적인 정보를 직접 관리하고 있다는 생각이 들었습니다. (예를 들어, 우테코의 캡틴 포비가, '6기 크루 헤인' 을 아는 것이 아니라 '6기 크루 헤인이 선릉 캠퍼스 근처 카페에서 먹는 커피메뉴' 정도를 직접 관리하는 느낌으로...)

코드의 유지보수성과 확장성을 높이기 위해서는 관심사의 분리가 중요합니다. 코드베이스에서 일관성 있는 추상화 레벨을 유지해야 하는 이유이지요. 합성 컴포넌트 방식은 각 구성요소의 역할이 분명하게 분리되어 유지보수가 더 용이해질 것입니다. 초기 구현 비용이 더 들 수 있지만, 장기적으로 더 다양한 요구사항에 대응할 수 있겠지요.

한편, 각 컴포넌트 구조를 명확하게 "선언"하고, 각 부분의 구성이 어떻게 이루어져 있는지 직관적으로 이해할 수 있도록 도와주는 측면도 있습니다. 라이브러리 사용자의 러닝커브가 우려된다면, 충분한 예제를 제공하는 방법으로 보완해도 좋을 것 같습니다 :)

```tsx
<Modal>
  <Modal.Header />
  <Modal.Boday />
  <Modal.Footer />
</Modal>
```

2024-05-12 04:29 UTC, 365kim commented on components/.storybook/preview.ts
> +      viewports: {
👍

![image](https://github.com/woowacourse/react-modules/assets/60066472/436b533b-5324-4fe7-92d8-32fc2b7f8ca7)

2024-05-12 04:30 UTC, 365kim commented on components/.storybook/preview.ts
> +} from '@storybook/addon-viewport';
오`@storybook/addon-viewport` 이건 package.json 의존성이나 .storybook/main.ts addons에 명시하지 않아도 되나요?

2024-05-12 04:31 UTC, 365kim commented on components/src/lib/Button/Button.stories.tsx
> +    ...Default.args,
👍

2024-05-12 04:33 UTC, 365kim commented on components/src/lib/Modal/AlertModal/AlertModal.tsx
> +      </>
`Fragment`를 안써도 되도록 `ModalProps`에 정의된 `children` 타입을 변경해볼 수도 있을까요?

2024-05-12 04:35 UTC, 365kim commented on components/src/lib/Modal/AlertModal/AlertModal.tsx
> +        {children}
`content`와 `children`을 동시에 쓸 수도 있을까요?

2024-05-12 04:37 UTC, 365kim commented on components/src/lib/Input/Input.tsx
> +        primaryColor={primaryColor || '#333333'}
(기본값을 한데 모아 보기 위해)
이것도 다른 prop 처럼 22 line에서 `primaryColor = '#333333'`로 기본값 지정해주면 어떨까요?

2024-05-12 04:38 UTC, 365kim commented on components/src/lib/Input/Input.tsx
> +  labelText?: string;
labelText를 optional(기본값 빈문자열'')로 지정해주신 이유가 궁금합니다 :)

2024-05-12 04:40 UTC, 365kim commented on components/src/lib/hooks/useInput.ts
> +const useInput = (initValue: string = '') => {
기본값만으로 충분히 타입 추론이 되어서 생략해도 괜찮을 것 같습니다 :)

![image](https://github.com/woowacourse/react-modules/assets/60066472/480a3d34-bb1c-4f46-a6e3-ef772fa0c576)

2024-05-12 04:40 UTC, 365kim commented on components/src/lib/hooks/useModal.ts
> +const useModal = (initState: boolean = false) => {
요기도 마찬가지입니당

![image](https://github.com/woowacourse/react-modules/assets/60066472/65cf181b-b9c5-4d41-a54c-5e510ad72682)

2024-05-12 04:42 UTC, 365kim commented on components/src/lib/hooks/useModal.ts
> +export default useModal;
이번에 추가된 `useInput` `useModal` 훅 굉장히 깔끔하게 잘 작성되었네요 👏

2024-05-12 04:44 UTC, 365kim commented on components/src/App.tsx
> +      <UsagePromptModal />
단순 궁금) `Usage-*` 컴포넌트는 어떤 용도인가요? 이 `App.tsx`의 용도도 궁금합니다.

2024-05-12 04:47 UTC, 365kim commented on hooks/src/lib/constants/cardBrand.ts
> +  | 'NONE';
요기는 type의 네이밍에 상수 값 네이밍 컨벤션이 적용된 것 같아 확인부탁드려요. `keyof`로 `CARD_BRAND`의 key값을 활용해서 타이핑해봐도 좋을 것 같습니당

2024-05-12 04:51 UTC, 365kim commented on hooks/src/lib/useValidateInput/useValidateInput.ts
> +    setValue(decorator(newValue));
단순 궁금)`decorator`는 `formatter`의 역할일까요?

2024-05-12 04:51 UTC, 365kim commented on hooks/src/lib/useCardNumber/useCardNumber.test.ts
> +  describe('카드 브랜드 식별', () => {
테스트까지 꼼꼼하게 잘 작성해주셨네요 👍

2024-05-12 04:54 UTC, 365kim commented on hooks/README.md
> +> Therefore, useCardNumber can be used with one **`input`**, and useCardNumbers can be used with multiple **`inputs`**.
> 그러므로 제가 가장 신경쓴 점은 다른 사람들이 이해하기 쉽고, 쓰기 쉽게 만들자! 였습니다. (모듈인만큼 UX 뿐만 아니라 DX 측면에서도 좋은 경험을 제공하고 싶었습니다.) 이를 위해 스토리북에 docs 및 viewport도 추가하고, npm docs 도 상세하게 작성하기 위해 노력하였습니다. 



![image](https://github.com/woowacourse/react-modules/assets/60066472/0b530ab1-3289-4402-9ae6-f98fc80655d1)

말씀해주신 대로 사용자 입장에서 헷갈릴 수 있을 포인트를 친절하게 다루어주신 흔적이 여기저기서 보이네요 👍 
나중에 서술할 내용이 많아지면 하단에 `FAQ` 섹션을 구성해도 좋을 것 같습니다 :)

2024-05-12 04:56 UTC, 365kim commented on hooks/README.md
> +> Therefore, useCardNumber can be used with one **`input`**, and useCardNumbers can be used with multiple **`inputs`**.
> 질문3) 특히, IT에 대해 잘 모르거나, 개발을 처음 배우는 사람이 이 모듈을 사용하려고 한다면, 어떤 점이 개선되면 더 쉽게 이 모듈을 사용할 수 있을까요? 이 모듈을 사용해야 한다면, 어떤 점이 가장 불편하게 느껴질까요? 다음 단계에서 개선할 수 있도록 새롭고 환기된 시각으로 바라봐주시면 감사하겠습니다.

오, 이것은 제가 답변 드리기 어려운 부분인 것 같아요. 저는 항상 어느 정도 개발 경험이 있다는 가정 하에 코드를 작성해온 것 같습니다. 🥲 개발 초심자의 사용성까지 고려한 헤인의 배려에 저도 배워갑니다 💙

2024-05-12 04:58 UTC, 365kim commented on components/src/lib/Button/Button.stories.tsx
> +  tags: ['autodocs'],
모든 스토리에서 autodocs를 사용할 상황이라면, 
새로 추가하는 `stories.tsx` 마다 'autodocs'를 설정하지 않고 일괄적으로 설정해봐도 좋을 것 같습니다.

- 참고: https://storybook.js.org/docs/writing-docs/autodocs

2024-05-12 05:27 UTC, 365kim commented on hooks/src/lib/useCardNumber/useCardNumber.ts
> +    const cardBrand = judgeCardBrand(value);
> 질문1) 카드 브랜드, 상태로 관리해야 할까?
카드 번호를 이용하기 위해 useCardNumber에서 한꺼번에 너무 많은 것들을 관리하고 있는 것은 아닐까 고민이 되었습니다. 카드 브랜드를 별도의 상태로 만들고, useCardBrand와 같은 훅을 이용하여 관리해주는 것이 더 좋았을까? 그런데, 카드 브랜드는 상태로 굳이 관리될 필요가 없는 친구이지 않나? 라는 생각이 계속 반복되었습니다. 결국 상태로 관리하고 싶지 않다는 마음이 더 커서 현재 상태를 유지하게 되었습니다.

아하, 카드 브랜드를 상태로 관리해야할지에 대한 고민이 있으셨군요. 저는 현재 헤인이 구현해주신 방식이 정답에 가까운 구현이라고 생각합니다. 

> 리엑트 공식문서에서 컴포넌트 안의 다른 state를 가지고 계산이 가능하다면 state로 관리할 필요가 없다는 글을 보았습니다. 저

이 표현에서 조금 정정해야할 부분이 있다면,  
다른 state를 가지고 계산이 가능하다면, 별도의 상태로 관리할 '필요가 없다'기보다 별도의 상태로 관리해서는 안됩니다. (아마 그 의도로 작성해주셨을 것 같지만요)

리액트에서는 상태가 변경될 때마다 컴포넌트 리렌더링이 발생하지요. 이 렌더링 흐름을 예측 가능하도록 관리하는 측면에서도 최소한의 상태를 관리하는 것이 좋겠습니다. 만약 카드 브랜드를 별도의 상태로 관리한다면, 카드 번호가 변경될 때마다 카드 브랜드도 함께 갱신되어야합니다. 두 상태를 동기화해주는 추가적인 로직이 필요한데, 일부 코드에서 누락되거나 하는 등의 이유로 버그가 발생할 가능성도 높아질 것입니다.

2024-05-12 05:31 UTC, 365kim requested changes
헤인, 안녕하세요 🌳
2단계 작업 잘봤습니다.

너무 좋은 질문과 고민 나누어 주셔서 좋았습니다 👍 이번 PR이 헤인과 나누는 마지막 PR이라는 게 아쉽다는 마음이 드네요. 제 피드백 전에 이미 정답에 가깝게 구현해주신 것도 인상적이었습니다 ㅎ_ㅎ 

몇 가지 코멘트 남겼는데, 천천히 보시고 확인 완료되시면 리뷰 재요청 부탁드릴게요~!
고생하셨습니다 👏👏👏

2024-05-12 07:24 UTC, Hain-tain commented on components/.storybook/preview.ts
> +} from '@storybook/addon-viewport';
현재 스토리북 내부에 viewport 가 포함되어있어서 별도로 다운로드하거나 명시하지 않아도 사용할 수 있는 것 같습니다...!
>Viewport is part of [essentials](https://storybook.js.org/docs/react/essentials) and so is installed in all new Storybooks by default. If you need to add it to your Storybook, you can run:
참고: [addon-viewport](https://storybook.js.org/addons/@storybook/addon-viewport)

2024-05-12 07:24 UTC, Hain-tain commented on components/.storybook/preview.ts
> +      viewports: {
모두 하루가 좋은 자료를 보내주신 덕분입니다...💙

2024-05-12 09:27 UTC, Hain-tain commented on components/src/App.tsx
> +      <UsagePromptModal />
`App.tsx` 는 하루에게 제가 만든 모듈의 사용 방법 및 사용 예시를 편하게 보여드리기 위해 만들게 되었습니다! 그리고 여러 개의 모달을 보여드리려고 하다보니, App 내부에서 컴포넌트 분리가 필요하다는 생각이 들어 Usage-* 컴포넌트들로 분리하게 되었습니다.

+) 이외에도 npm docs 에서도 Quick start 에서 사용 방법을 보여주기 위해 작성해두었던 Usage-* 컴포넌트들을 사용할 수 있었습니다..!

2024-05-13 11:41 UTC, Hain-tain commented on components/src/lib/Modal/Modal.tsx
> +  size?: ModalSize;
라이브러리인만큼 tsDos를 잘 활용하면 좋을 것 같네요! 👍

👉 아래 커밋에 반영되었습니다
[dcf9332](https://github.com/woowacourse/react-modules/pull/66/commits/dcf933286a14668091bd94d0189c1e3e2e213e9a)[dcf9332](https://github.com/woowacourse/react-modules/pull/66/commits/dcf933286a14668091bd94d0189c1e3e2e213e9a)

2024-05-13 11:43 UTC, Hain-tain commented on components/src/lib/Modal/AlertModal/AlertModal.tsx
> +      </>
`React.PropsWithChildren` 타입을 적용하여 해결할 수 있었습니다! ☺️

👉 아래 커밋에 반영되었습니다.
[609b94f](https://github.com/woowacourse/react-modules/pull/66/commits/609b94f21195521c70f5ec4ad4d821b28c408634)[609b94f](https://github.com/woowacourse/react-modules/pull/66/commits/609b94f21195521c70f5ec4ad4d821b28c408634)

2024-05-13 11:49 UTC, Hain-tain commented on components/src/lib/Input/Input.tsx
> +        primaryColor={primaryColor || '#333333'}
👉 아래 커밋에 반영되었습니다.
[4040465](https://github.com/woowacourse/react-modules/pull/66/commits/4040465c03f56bfa63df88d6fb9c88f050373861)[4040465](https://github.com/woowacourse/react-modules/pull/66/commits/4040465c03f56bfa63df88d6fb9c88f050373861)

2024-05-13 11:59 UTC, Hain-tain commented on components/src/lib/Input/Input.tsx
> +  labelText?: string;
input과 label을 연결하기 위해서는 htmlFor 를 사용하여 input 정보를 label에 연결해주어야 합니다.
그렇지 않을 경우 label로 연결하고 싶은 input을 감싸서 연결할 수도 있죠. 

저는 사용자가 input의 정보를 굳이 label에 넘겨주지 않아도 자동으로 연결되도록 label 이 input을 감싸고 있도록 구현하게 되었습니다. 따라서 만약 label을 사용하지 않을 사람들을 위해 기본값으로 빈문자열을 넣어주게 되었습니다.

그러나 리펙토링을 하는 과정에서 (각 모달의 `content`를 조건부 랜더링으로 변경하면서) **`사용하지 않는 태그를 html상에 남겨두는 것이 과연 옳은가?`** 라는 질문을 스스로 던져보았고, `사용하지도 않고, 필요하지도 않은 태그를 생성하여 남겨두는 것은 옳지 않다`고 결론을 내리게 되었습니다. 코드 가독성이 조금 떨어지더라도 당위성있게 작성하는 것이 옳다는 생각이 들어
 아래와 같이 labelText가 없을 때는 아예 label 이 생기지 않도록 변경해보았습니다.

```js
const Input = ({
...
}: InputProps) => {
  return labelText ? (
    <Styled.Label labelPosition={labelPosition}>
      {labelText}
      <Styled.Input {...}/>
    </Styled.Label>
  ) : (
    <Styled.Input {...} />
  );
};
```

2024-05-13 12:00 UTC, Hain-tain commented on components/src/lib/hooks/useInput.ts
> +const useInput = (initValue: string = '') => {
👉 아래 커밋에 반영되었습니다.
[0f78f48](https://github.com/woowacourse/react-modules/pull/66/commits/0f78f480e2b2d5200da4b7246f2895a257bb55f3)[0f78f48](https://github.com/woowacourse/react-modules/pull/66/commits/0f78f480e2b2d5200da4b7246f2895a257bb55f3)

2024-05-13 12:01 UTC, Hain-tain commented on components/src/lib/hooks/useModal.ts
> +const useModal = (initState: boolean = false) => {
👉 위와 동일하게 이 커밋에 함께 반영되었습니다.
[0f78f48](https://github.com/woowacourse/react-modules/pull/66/commits/0f78f480e2b2d5200da4b7246f2895a257bb55f3)[0f78f48](https://github.com/woowacourse/react-modules/pull/66/commits/0f78f480e2b2d5200da4b7246f2895a257bb55f3)

2024-05-13 12:04 UTC, Hain-tain commented on components/src/lib/hooks/useModal.ts
> +export default useModal;
사실 `컴포넌트 모듈에서 hook도 같이 내보내주는 것이 맞을까? 별도의 hook 모듈로 내보내주어야 하나?` 라는 고민을 하였지만,
제가 만든 컴포넌트를 보다 편리하고 잘 쓸 수 있도록 도와준다면 같은 모듈 내에서 기능을 제공하는 것이 사용하는 입장에서 더 좋을 것이라고 생각하여 커스텀 훅도 함께 배포하게 되었습니다...! ☺️

2024-05-13 12:15 UTC, Hain-tain commented on hooks/src/lib/constants/cardBrand.ts
> +  | 'NONE';
> **Keyof Type Operator**
>keyof 연산자는 객체 타입에서 객체의 키 값들을 숫자나 문자열 리터럴 유니언을 생성합니다. 
[keyof 연산자](https://www.typescriptlang.org/ko/docs/handbook/2/keyof-types.html)

<사용 예시>
<img width="257" alt="image" src="https://github.com/woowacourse/react-modules/assets/157036488/0db45404-a055-4d44-a3f8-6f3ccd1ca220">

**🌟 따라서 typeof 와 함께 keyof를 사용하면, 객체의 키를 유니온 타입으로 반환받을 수 있다**

덕분에 너무너무너무 중요하고 유용한 연산자를 알게되었어요! 감사합니다 🙏
방학 기간에 타입스크립트를 더 열심히 공부해야겠다는 생각이 드네요🫠

2024-05-13 12:21 UTC, Hain-tain commented on hooks/README.md
> +> Therefore, useCardNumber can be used with one **`input`**, and useCardNumbers can be used with multiple **`inputs`**.
>  서술할 내용이 많아지면 하단에 FAQ 섹션을 구성해도 좋을 것 같습니다 :)
너무 좋은 생각인 것 같네요! 추후 고려해보겠습니다☺️

2024-05-13 12:29 UTC, Hain-tain commented on hooks/src/lib/useCardNumber/useCardNumber.ts
> +    const cardBrand = judgeCardBrand(value);
고민을 많이 했었는데, 좋은 방향의 결정이었다니 너무 안심이 되네요...☺️

특히 아래 문장이 정말 인상깊었습니다! 상태가 변경되면 리랜더링이 트리거된다는 것은 알고 있었는데, 렌더링 흐름에 대해서는 생각해보지 못했던 것 같아요! 앞으로 코드를 작성할 때, 이 부분을 명심하며 작성해보도록 하겠습니다!
> 렌더링 흐름을 예측 가능하도록 관리하는 측면에서도 최소한의 상태를 관리하는 것이 좋겠습니다.

상세한 설명 너무 감사합니다 🙏

2024-05-13 12:37 UTC, Hain-tain commented on components/src/lib/Modal/AlertModal/AlertModal.tsx
> +        {children}
content와 children 두개 다 props 로 넘겨주어 두 개 다 동시에 사용할 수 있습니다! (`content` 라는 props 가 추가된 이유는 children을 사용하지 않고 짧게 글만 넣고 싶은 사람을 위해서입니다!)

👉 아래 커밋에 반영되었습니다
[e3bb5f7](https://github.com/woowacourse/react-modules/pull/66/commits/e3bb5f7cf79fd92b94da4b94cda1970b21dcd761)[e3bb5f7](https://github.com/woowacourse/react-modules/pull/66/commits/e3bb5f7cf79fd92b94da4b94cda1970b21dcd761)

2024-05-13 12:39 UTC, Hain-tain commented on components/src/lib/Modal/AlertModal/AlertModal.tsx
> +        {children}
아래는 저의 물음에 하루가 DM으로 보내주신 내용이 너무 좋아 pr에 남겨두고 싶어 제가 살포시 복붙해왔습니다...❤️

지금보니 content 를 prop으로 지정하지 않아도 항상 p 태그가 렌더링 될 것 같아서, 조건부 렌더링 처리하면 좋을 것 같습니다.

의견을 더 보태보자면,
만약 ModalTextBody 스타일을 입힌 content 상단에 이미지 등을 배치하고 싶은 경우에는
```js
{children}
<ModalTextBody>{content}</ModalTextBody>
```
이렇게 순서가 변경되어야할 것 같기도 합니다.
따라서 지금의 ModalTextBody의 스타일은, 아예 독립적인 Typography 같은 컴포넌트로 제공하고,
필요에 따라 사용자가 children 위치에 직접 구성하는 방식이 더 확장성 있을 것 같습니다.
(코드 변경을 요청드리는 것은 아닙니다. 하나의 생각해볼 거리를 공유하는 취지로 말씀드립니다.)

2024-05-13 12:42 UTC, Hain-tain commented on hooks/src/lib/useValidateInput/useValidateInput.ts
> +    setValue(decorator(newValue));
네! 해당 함수는 value 를 변경해주기 때문에, value를 꾸며준다는 의미에서 decorator 라고 이름을 지어보았습니다. (추후 다른 커스텀 훅에서는 포멧팅이 아니라 value의 값을 꾸며주기 위해서도 사용할 수 있을 것이라고 생각했기 때문입니다.)

2024-05-13 12:51 UTC, Hain-tain commented on components/src/lib/Button/Button.stories.tsx
> +  tags: ['autodocs'],
👉 아래 커밋에 반영되었습니다.
[74ce286](https://github.com/woowacourse/react-modules/pull/66/commits/74ce28689a4d99100b08a87e867d6bfe032c30df)[74ce286](https://github.com/woowacourse/react-modules/pull/66/commits/74ce28689a4d99100b08a87e867d6bfe032c30df)

2024-05-13 13:50 UTC, 365kim commented on components/src/lib/Button/Button.tsx
>    size?: ButtonSize;
💯

2024-05-13 13:57 UTC, 365kim commented on components/src/lib/Button/Button.tsx
>    size?: ButtonSize;
`@remarks`는 summary section 에 담기에는 좀 더 디테일한 내용, 주로 메서드의 동작이 복잡하거나, 다른 개발자가 유의해야할 부분 등을 담는 용도로 확인했어요

- 참고: https://tsdoc.org/pages/tags/remarks/

타입정보를 제공해도 좋지만, 주석 또한 관리의 대상이기 때문에 (타입 변경 시 최신화가 안될 경우 오히려 혼란을 줄 수 있는) hover 로 확인할 수 있는 정보라면 생략해도 괜찮을 것 같습니다.

<img width="459" alt="image" src="https://github.com/woowacourse/react-modules/assets/60066472/2703546c-e756-43bf-9ece-31da4320cf65">

2024-05-13 13:58 UTC, 365kim commented on components/.storybook/preview.ts
> +} from '@storybook/addon-viewport';
아하, 저도 배워갑니다 링크 감사합니다 ☺️

2024-05-13 13:59 UTC, 365kim commented on components/src/lib/Modal/AlertModal/AlertModal.tsx
> +      {content && <ModalTextBody>{content}</ModalTextBody>}
조건부 렌더링 반영해주셨군용 👍

2024-05-13 14:08 UTC, 365kim commented on components/src/lib/Input/Input.tsx
> +  labelText?: string;
구현해주신 방향 좋습니다 👍 가독성도 제가보기엔 괜찮은 것 같습니다.

2024-05-13 14:08 UTC, 365kim commented on components/src/lib/Input/Input.tsx
> +  labelText?: string;
조금 심화적인 내용이지만 참고차 코멘트 추가해둡니다. 

헤인이 알고 계신 것처럼 input과 label을 짝 지어주는 방법에는 2가지가 있지요.

- 1번) label 요소가 input 요소를 품도록 작성하는 방법 ( <- 현재 코드)
- 2번) htmlFor, id로 서로를 연결하는 방법

이 두 가지 방법은 완전히 동일한 효과를 내는 것은 아니에요. 2번 방법과 같이 label에 for를 지정하는 경우에만 모든 스크린 리더에서 정확하게 사용자에게 정보를 제공할 수 있어요. (실제로 테스트해보면 1번 방법의 경우 input의 정보를 제대로 읽어주지 않는 경우가 있습니다.) 이 차이를 알게 된 후부터 저는 1번 방법보다는 2번 방법을 사용하는 편이에요.

2024-05-13 14:09 UTC, 365kim commented on components/src/App.tsx
> +      <UsagePromptModal />
아하 그런 거였군용~! 친절한 설명 감사합니다 ☺️

2024-05-14 04:42 UTC, Hain-tain commented on components/src/lib/Input/Input.tsx
> +  labelText?: string;
웹 접근성 측면에서 2번이 좋군요! 앞으로 저도 2번 방법을 사용해야겠네요!

2024-05-14 04:54 UTC, Hain-tain commented on hooks/src/lib/useValidateInput/useValidateInput.ts
> +    setValue(decorator(newValue));
앗, `decorator` 라는 디자인 패턴이 있군요..! 그렇다면 읽는 사람들이 오해할 여지가 있으므로 이름을 변경하는 것이 좋을 것 같네요. (`formatter` 로 변경하였습니다!)

현재 적용하지는 못했지만, 제가 생각한 value의 값을 꾸며주는 것의 예시는 아래와 같습니다.
- 카드 소유자 이름 toLowerCase() 또는 toUpperCase() 해주기
- 비밀번호 입력시 바로 직전에 입력한 1자리 빼로 `*`로 변환해주기

2024-05-14 05:07 UTC, Hain-tain commented on components/src/lib/Modal/Modal.tsx
> +  buttonJustifyContent?: ButtonJustifyContent;
> Modal이라는 중앙 관리자가 너무 많은 구체적인 정보를 직접 관리하고 있다는 생각이 들었습니다. (예를 들어, 우테코의 캡틴 포비가, '6기 크루 헤인' 을 아는 것이 아니라 '6기 크루 헤인이 선릉 캠퍼스 근처 카페에서 먹는 커피메뉴' 정도를 직접 관리하는 느낌으로...)

저도 제가 만든 모듈을 사용해보면서 고민 되었던 부분이라 하루의 코멘트가 무척 공감이 되었습니다. (괄호에 담긴 예시도 너무 찰떡이라 재미있었어요ㅎㅎ) 그러나 현재 코드를 합성 컴포넌트 방식으로 전부 바꾸기에는 시간적 여유도 부족하고, 사실 하루가 코멘트를 남겨주신 이유도 코드의 변경보다는 `앞으로 확장성을 높이기 위해서는 이런 방향도 생각해보면 좋다!` 라는 의미이셨기에 코드를 크게 수정하지는 않았습니다.

다만, 하루의 코멘트에 깊게 공감하였는데도 불구하고 아무것도 변경하지 않을 수 없어 `현재 상황에서 합성컴포넌트로 변경하게 된다면, 이렇게 고려해볼 수 있을 것 같아요!` 라는 느낌으로 `CustomModal` 을 만들어보았습니다..! 

또한 `코드베이스에서 일관성 있는 추상화 레벨을 유지해야 한다`는 말이 굉장히 인상깊었어요. 그동안 추상화를 해야하는가 말아야 하는가에 대해서는 깊게 고민하였으나, 추상화 레벨을 맞춘다는 것에 대해서는 많이 고려해보지 못했던 것 같아요! 이 부분은 앞으로 미션을 해나가면서 고려해보겠습니다!!

2024-05-14 05:20 UTC, Hain-tain commented
안녕하세요, 하루! 
리뷰 재요청이 늦어져서 죄송합니다🙏
(리뷰 요청을 보내지 않았는데도 이렇게 먼저 리뷰를 남겨주시다니..🥺 정말 감사해요! )
덕분에 생각해보지 못했던 지점에 대해서도 생각해보고, 고민했던 부분에 대해 나름대로의 답을 내릴 수 있게 되었습니다.

하루와 함께할 수 있어 정말 영광이었습니다!💙

2024-05-14 05:22 UTC, Hain-tain commented on components/src/lib/Button/Button.tsx
>    size?: ButtonSize;
`주석 또한 관리의 대상이기 때문에` 라는 말이 인상적이었어요! 너무 많은 것을 담는다고 다 좋은 것이 아니군요!

👉 아래 커밋에 반영되었습니다.
[fceb1c6](https://github.com/woowacourse/react-modules/pull/66/commits/fceb1c6feabc58dc2521ca4a7f127c173d2ce58b)

2024-05-15 05:43 UTC, 365kim commented on components/src/lib/Input/Input.tsx
> +  primaryColor = '#333333',
👍

2024-05-15 05:44 UTC, 365kim commented on components/src/usage/UsageCustomModal.tsx
> +        </CustomModal.Body>
이런 사용이 가능한 컴포넌트군요 👍

2024-05-15 05:45 UTC, 365kim commented on components/src/usage/UsageCustomModal.tsx
> +        </CustomModal.Body>
> 다만, 하루의 코멘트에 깊게 공감하였는데도 불구하고 아무것도 변경하지 않을 수 없어 현재 상황에서 합성컴포넌트로 변경하게 된다면, 이렇게 고려해볼 수 있을 것 같아요! 라는 느낌으로 CustomModal 을 만들어보았습니다..!

피드백 적극적으로 고려해주시고 또 반영해주셔서 감사합니다 💙

2024-05-15 05:47 UTC, 365kim commented on hooks/src/lib/useValidateInput/useValidateInput.ts
> +    setValue(decorator(newValue));
아하 예시 설명 감사합니다. (upper case 적용이나 '*'로 적용하는 것 모두 formatting의 일환으로 봐도 괜찮을 것 같습니다)

2024-05-15 05:59 UTC, 365kim approved these changes
<img width="346" alt="image" src="https://github.com/woowacourse/react-modules/assets/60066472/3575e32c-47c5-49f1-8c5c-931e7baeed81">

헤인, 미션 완료 축하드립니다 🎉

새로운 미션 시작으로 바쁘실 텐데도 마지막까지 꼼꼼하게 피드백 반영해주셔서 감사합니다 💯
(1단계에 이어) 2단계에서도 너무나도 훌륭하게 해주셔서 제가 피드백 드린 이상으로 많은 것을 얻어가셨을 것 같아요. 덕분에 저도 많이 배울 수 있었습니다 👍

이어지는 헤인의 새로운 미션도 응원합니다. 고생하셨습니다 👏👏👏

2024-05-15 05:59 UTC, merged